### ISSUE TITLE
USER ISSUE: steam tractor - not able to "drive"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10003]
**Version:** 0.7.8.0 beta
You can not seat to it, and cannot drive.
Stream tractor broken :( 
![20181114093218_1](https://user-images.githubusercontent.com/4980243/48464351-563ff700-e7f0-11e8-81f9-c884cba798da.jpg)

**Comment by elfl0rd** [comment]
In addition, steam tractor engive works everytime.
![20181114093401_1](https://user-images.githubusercontent.com/4980243/48464396-7b346a00-e7f0-11e8-960b-cda6d3d60603.jpg)

**Comment by johnkslg** [comment]
Hotfix incoming!

**Comment by pamduncan** [comment]
Hi there we were told that this was fixed and would be into today's hotfix (7.8.2)  However there was also a similar bug making so a player could not open there large windowed door or garage door. We were told that it was also in as a fix.  The doors appear to not belong to anyone and are on plot that is unowned although the players say they are on property that say it belongs to them.

Getting many people coming in the have updated to the tractor and saying they still have the same bug and I see from the change log that tractor fix is not mentioned so maybe it did not make it in?

**Comment by elfl0rd** [comment]
Yes, i can confirm - issue with tractor is NOT fixed.
now the tractor engine starts when you try to get into it, and stops when you try again

But you still can't sit in it and can't control it.

**Comment by elfl0rd** [comment]
@D3nnis3n can you reopen?

**Comment by pamduncan** [comment]
I have contacted Quadbro  who said he would try to take a look at it.  I am sure he will open it back up once he does

**Comment by Quadbro** [comment]
![image](https://user-images.githubusercontent.com/6802030/48618278-72e45680-e9cb-11e8-86b9-f3777de59c99.png) 
Commited to release svn by myself now, hope fix will be counted in nex release, maybe build wasn't update svn content...
