### ISSUE TITLE
5.3 Elections /+ignoring results as if they never happened/

### ISSUE THREAD

**Issue by NeoKuro** [StrangeLoopGames/EcoIssues#1037]
We have ran 2 elections on this server (both of them started before a town hall was built, one of them before a town hall was finished) and despite there being a clear winner of 4:2, the browser states there has been no previous election. As shown below

![untitled](https://cloud.githubusercontent.com/assets/9193994/22046434/7eb987da-dd18-11e6-9518-9b439de20986.png)

 If an election is started again, the results at the end of the previous election are recovered and the election 'resumes' as normal for another 24 hours as shown below. This is the third election that has started, all with the same 2 people running (the first time "Supremeninjaz" started the election. The second two times I did. In each case all the votes from the previous election have carried over.)

 I can understand the 'incumbent' being automatically added to the candidates list, that makes sense (unless there is a law preventing X amount of consecutive terms like iRL or something). But previous candidates who were not elected should not be 're-registered automatically. 

 'Majority acquired' is unlikely to ever really happen, as I'm assuming it goes off total population, rather than 'total active' population. This server has ~50 citizens with only 5-7 of them actively playing, no where near a majority.

 "Projected Results" on the right in the second screenshot, it says "NeoKuro wins with 4 votes and will replace NeoKuro as world leader" however there is no world leader according to the 'welcome' chat tab, and there has been no previous election (note: it said the same thing in the first election before anyone else had ran before)

![untitled](https://cloud.githubusercontent.com/assets/9193994/22046457/aa16b7ea-dd18-11e6-8f9f-7a0f49581910.png)

**Comment by rainfarmer** [comment]
@NeoKuro hey, I haven't been able to reproduce this error. 
Is it still happening on your server?

**Comment by MarjieAVolk** [comment]
I'm wondering if this isn't due to lack of an error message about the minimum number of votes required for the election to succeed?

Currently, web api election objects have a field "StatusMessage" which I implemented a while ago, which does not seem to be in use.  This message should be displayed instead of the "Ends in 23 hours or when majority is acquired" message I currently see on the web page, which seems to be generated client side.

I'm also going to go ahead and send out a chat message if the election ends without a winner, giving a reason, which will also help a lot.

**Comment by rainfarmer** [comment]
Still cant recreate. I updated election page to use 'StatusMessage'

**Comment by NeoKuro** [comment]
Hey sorry I only just now have seen these responses.

I'm not sure I can help anymore in all honesty. To my knowledge the server is gone (wasn't mine) and I can't recall specifics anymore. Sorry.
