### ISSUE TITLE
Master: too many skillpoints. Again.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10768]
Fresh master, fresh world...
![default](https://user-images.githubusercontent.com/4980243/51425461-8db29180-1bed-11e9-8394-f21a7d896fdb.png)
![default](https://user-images.githubusercontent.com/4980243/51425467-97d49000-1bed-11e9-9293-eba0c07945ff.png)

https://github.com/StrangeLoopGames/EcoIssues/issues/10335
https://github.com/StrangeLoopGames/EcoIssues/issues/10364

**Comment by johnkslg** [comment]
Try again! Should be fixed

**Comment by elfl0rd** [comment]
okay, lol
![default](https://user-images.githubusercontent.com/4980243/51556088-3bda6780-1e8a-11e9-88e1-f6d58e2f7acd.png)
Still at "no collaboration" server preset. @johnkslg

**Comment by elfl0rd** [comment]
Recheck after @mirasrael PR
![default](https://user-images.githubusercontent.com/4980243/51559046-f91c8d80-1e91-11e9-8f25-979e68996921.png)

**Comment by johnkslg** [comment]
Fixed

**Comment by elfl0rd** [comment]
not fixed.
![default](https://user-images.githubusercontent.com/4980243/51588539-9b219180-1ef5-11e9-83b7-9e956ae55cc0.png)

**Comment by elfl0rd** [comment]
fixed.
