### ISSUE TITLE
Fps Drops 8.0

### ISSUE THREAD

**Issue by ludovi71** [StrangeLoopGames/EcoIssues#11248]
fps dropping regulary when looking at the new grass textures, also even worse drops when looking at the redwood trees.
My 2gb 755m graphic card is at 99% usage,
It may have been at the same usage before 8.0 update, but i didnt notice any fps drops before, It was always atleast 40fps on 7.8

Look at the video for more detail
[https://youtu.be/l1RbeW6K0_o](url)

**Comment by loaykr** [comment]
same issue here, I can't play the game anymore, I used to get 20-30 fps on 7.8.9, now I can't even move from point A to B, I stopped playing the game since it's unplayable at all for me

I have intel HD 4000

**Comment by ludovi71** [comment]
Seems like its same in the jungle biome, I have like 15 - 20 fps when in jungle biome, but when i cut down these high trees, my fps are back at 40

**Comment by ThisFlynn** [comment]
Logging into our server, I start at a beautiful 60fps, but after several minutes the fps rate starts to drop and eventually settles around 14fps. Disconnecting and logging back in (without closing the program) brings it back up to 60....but only for a little while. This has been the case for a few days since we started the server - regardless of how many people are on.

**Comment by loaykr** [comment]
After the 0.8.0.1 update, I can play for the first 30 minutes without any issue then I will start laging so badly that I can't do anything in the game, I didnt get that on older versions of the game 7.8.9 and before, it's happening on all servers + singleplayer

**Comment by loaykr** [comment]
the game now is even worse than before, update 0.8.0.2
fps drops alot in this update, unplayable again

**Comment by ludovi71** [comment]
I totaly agree, 8.0.2 i have nonstop fps at like 20, Also it seems like my ram usage is higher now,
I think it is caused by my render distance, I have it set to lowest setting possible but when i look at my game , i am pretty sure it shows way more world around me than it used to before.

**Comment by redwyre** [comment]
Hi @ludovi71, @loaykr and @ThisFlynn. we have released 8.1 which has a number of performance improvements, could you try it out and report back?

**Comment by seccombew** [comment]
Reopen if issue persists.

**Comment by ThisFlynn** [comment]
Thanks, will do

**Comment by D3nnis3n** [comment]
This reports low fps in junges, which is persisting for me.

**Comment by johnkslg** [comment]
@BlazeGuy2 can you follow up and see if the new build helps?

**Comment by BlazeGuy2** [comment]
@D3nnis3n Are you still having this FPS issue in the jungle with the staging builds?

**Comment by keegan-o** [comment]
Fixed the material settings on the ceiba vines in staging and master, hopefully that helps with jungle performance.

**Comment by seccombew** [comment]
@beastyn @SlayksWood Would you please test to see if issue persists with tonight's upcoming build.

**Comment by redwyre** [comment]
If you can check frame-rates per-biome that will let us know what to target

**Comment by SlayksWood** [comment]
Intel core i5-6550CPU, 3.2 GHz
RAM - 16Gb
Nvidia GeForce GTX 970- 4 Gb
Win 10 - 64
Biome test (after the game for some time, so that the FPS fall to the minimum values):
Cold Forest: 20-25. Sometimes when running from debris and grass FPS fall to 10.
Deep Ocean: 50-100.
Desert: 40-50. Sometimes when running from grass FPS fall to 30.
Grassland: 20-30. Often FPS fall to 15.
Ice: 30-40. Sometimes FPS fall to 20.
Ocean: 40-60. Sometimes FPS fall to 25.
Rainforest: 25-35. Often FPS fall to 15.
Boreal Forest: 35-40. Sometimes FPS fall to 20.
Tundra: Rainforest: 30-40. Sometimes FPS fall to 15.
Warm Forest: 20-30. Sometimes FPS fall to 15.

FPS falling is freeze which appears when you run from debris or grass. 
As example one of worst biome (Grassland): 
https://drive.google.com/file/d/1XP9HRd-jxY1Og3Dt7s0Y5ArEiIYNSe01/view?usp=sharing

**Comment by beastyn** [comment]
Intel core i7-4790CPU, 3.6 GHz
RAM - 16Gb
Radeon RX 550 - 4 Gb
Win 10 - 64

After 1 hour play

Cold Forest 20-25fps
Deep Ocean 30-40fps
Desert Biome 35-50fps 
GrassLand ~20 - 25fps
Ice - 30-35fps
Ocean - 30-40fps
Rainforest - 20-25fps
Boreal Forest - 25-33fps
Tundra 25-30fps
Warm Forest - 20-25fps

There are freezes (dropping to about 15fps). Mostly at the Grassland, Raiforest.

**Comment by D3nnis3n** [comment]
Ryzen 2700 @ 4,0 GHz
RTX 2080 8 GB
32 GB RAM
Windows 10 May Update 2019
Resolution: WQHD

Grasslands: 100 - 120 FPS
Forest: 120 - 140 FPS
Cold Forest: 120 - 140 FPS
Desert: 160 - 190 FPS
Deep Ocean: 140 - 160 FPS
Ice: 100 - 120 FPS
Rainforest: 70 - 90 FPS

Whenever chunkloading occurs, though, my fps drop to 30 and i get a minor or major lag.
Values from a new world, values on a world with lots of buildings will definately be way worse.

**Comment by SlayksWood** [comment]
@johnkslg 
may need to be assigned to 9.0? for further improvements

**Comment by Praefator** [comment]
Figured I'd pitch in here as well. I've let the game run for a bit, traveling between a desert and a grasslands, which is usually enough for the following numbers. 
Peak fps can be as high as 90+ in a busy area whenever I freshly relaunch the client, although I've had to disable vsync to do so. Every bell and whistle is enabled apart from Global Illumination and Anti-aliasing, which are both turned off, and view distance is at 150. Running 8.2.9 as of this writing:

Ryzen 1700x @ stock
RTX 2080ti
16 GB RAM
Windows 10 May Update 2019
Resolution: 4K

Grasslands: 17 - 24 FPS
Forest: 10 - 19 FPS
Cold Forest:  19 - 34 FPS
Desert: 23 - 36 FPS
Deep Ocean: 34 - 41 FPS
Ice: 48 - 80 FPS
Rainforest: 29 - 52 FPS

**Comment by douglasg14b** [comment]
Also receiving cripplingly bad FPS.

Getting ~23FPS with max graphics settings, and 27FPS with with them on minimum, which doesn't seem to make much sense?

My buddy is on Windows with an RTX 2080, getting ~25-35FPS, with <30% utilization.

```
Operating System: KDE neon 5.17
KDE Plasma Version: 5.17.2
KDE Frameworks Version: 5.63.0
Qt Version: 5.13.1
Kernel Version: 5.0.0-32-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
```

**Comment by D3nnis3n** [comment]
I have nearly the same hardware as you, Eco is permanently CPU limited, hence the little change with GPU. Best results you get on high single core frequency cpus, like i9900KS.

**Comment by douglasg14b** [comment]
@D3nnis3n That's what I was thinking, though I watched my CPU utilization, and none of my Core's broke 25% utilization, while my RX 580 was capped. Which seems to point at the GPU, especially since the FPS changes depending on what I'm looking at (On top of a hill I might get 10FPS, looking at the ground I might get up to 40FPS)

On that note though, the 2700x doesn't seem have poor per-thread performance, nor does the i7-8900k which is what my buddy has.

CPU Utilization While Playing:

![image](https://user-images.githubusercontent.com/1400380/69992603-e2f24b80-14fe-11ea-93de-31b1a55c95c4.png)

**Comment by D3nnis3n** [comment]
It's surely not poor. Eco just uses way too much of it. Think of it being the most CPU resource intensive game you've ever encountered. That's we're trying to fix.

You two might have different issues, but the main issue people experience is what i told. Just like me with 2700X and 2080Ti. My graphics card is bored, the CPU is 75% on one thread and i get 12.5 fps in big cities.

**Comment by D3nnis3n** [comment]
If you could provide usage screens from your friend, that might be helpful.

**Comment by mirasrael** [comment]
Should we close it in favor of similar issues? @WeaselDog

**Comment by WeaselDog** [comment]
We have had significant improvements in FPS since this time. Closing in favor of other more specific FPS tasks

**Comment by Praefator** [comment]
Cannot say I agree. Even with a 3900x and a 2080ti (at 4K) there are still
frequent areas where my fps drops from the high 60's to the low-mid 40's.
Especially grass is a culprit, but haven't tested for longer-term
consistency yet.

**Comment by D3nnis3n** [comment]
Yes, hence the 'more specific' FPS issues. My FPS increased notably, I'm only stuck with Cities (many stockpiles) and grass to a degree now.
