### ISSUE TITLE
Old Growth Redwood Saplings

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#11263]
From what I have been told the giant **Old Growth Redwood** trees aren't suppose to ever regrow.

I just logged in after the server rebooted to v0.8.0.1 and saw a new Old Growth Redwood tree outside my house, I ran over to chop it, but it vanished after one hit. One guess would be that it was sapling? Maybe the wrong model?

**Comment by Deantwo** [comment]
Today I login to the server to see another player on my server having just cut down the "fake" tree that vanished for me yesterday.

But I know for a fact that the location of the now giant tree stump did not have a giant redwood tree at the start of the world, that location was even higher at the beginning as I made room for a road. So the giant great redwood tree must have spawned somehow.

**Comment by elfl0rd** [comment]
Yes, it's saplings - periodically spawn aster stump removing.
![20190213003428_1](https://user-images.githubusercontent.com/4980243/52670120-d62d4880-2f28-11e9-89fc-87cbc7a42124.jpg)

**Comment by Deantwo** [comment]
Meanwhile a **Old Growth Redwood** tree I had protected with a claim seem to have vanished. But that might be a separate issue.

**Comment by metachronism** [comment]
fixed these.  old growth redwoods are not meant to be growable, they only exist at spawn of the world.

problem was is that some of them were "young" old trees, which meant they died with one axe chop (like other young trees do)

**Comment by Deantwo** [comment]
It seems that players are still experiencing this in v0.8.0.3, can you confirm if the bugfix was included in v0.8.0.3 or not?

**Comment by Deantwo** [comment]
As described in #12125, this is not fixed.
