### ISSUE TITLE
Latest rubble "optimization" patch broke Skid-steer mining

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11594]
0.8.0.5 beta

Steps to Reproduce:
Get a skid steer and mine. you will get stuck.

Since the patch 0.8.0.4, when rubble reaches zero velocity it freezes solid to prevent unnecessary physics calculations.
The problem with this is, when you dig with your skid-steer rubble falls under and behind it, freezes and your skid steer is stuck until someone removes the rubble.

possible fixes are unfreezing of rubble once its nearby the skid-steer or disabling collision between them.

this also applies to the excavator.

**Comment by GekkeGerit** [comment]
so how  is this a Low Priority?....almost all end game is destroyed this way....none is ganna handmine till lazers...so make it high again and pls fix it fast...we still have 8 days left before astroid inpact and would like to save our world :)

**Comment by gamerpaddy** [comment]
it has been hotfixed, which broke it again which has been fixed again (hopefully)
basically the rubble became solid after the optimization patch, skidsteer got stuck on it.
after hotfix, the rubble didnt collide with the skidsteer anymore so it wouldnt get stuck but also you couldnt pick it up. (#11729 )
now you can drive trough the rubble (sort of) but also pick it up.

**Comment by GekkeGerit** [comment]
forced update on server because i dont see any patch info anywhere....still have issues with skid steer not picking up solid rubble, removed all old rubble to be sure but  still get frozen and not picked up, so either where doing something wrong or it issnt fixed...if i look at server data it says Eco Server 0.8.0.7 beta...is there a new version that my server host doesnt provide? because in our 0.8.0.7 server skidsteer dont work.

**Comment by D3nnis3n** [comment]
Duplicate of #11654

Fix is available in upcoming 8.1 release.
