### ISSUE TITLE
Animal flee should look good

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11829]
Work with Milenko and Lach to make animal's 'getup and flee' look great.

**Comment by SlayksWood** [comment]
I like that the animals are pretty fast 'getup and flee' now.

**Comment by johnkslg** [comment]
This has been addressed and can be reevaluated

**Comment by beastyn** [comment]
still an issue
https://drive.google.com/file/d/1SXJVq7hNCTJ0YJvgFm5rHvQ4b2Hcszhg/view?usp=sharing
