### ISSUE TITLE
[0.8.2.0 staging-17] Minor bug with unmute another player at voice chat

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12306]
Click to icon and nothing happens
![image](https://user-images.githubusercontent.com/45708377/57782427-e4ac1b80-7734-11e9-958a-2288d6979ab4.png)

**Comment by SlayksWood** [comment]
You can't unmute player. Step to reproduce:
- Open Esc Menu
![image](https://user-images.githubusercontent.com/45708377/58081360-9f1ca200-7bbd-11e9-84b3-047268c02787.png)
- Mute Player
![image](https://user-images.githubusercontent.com/45708377/58081382-ac399100-7bbd-11e9-9c20-1ea31fee0302.png)
- Close and open again Esc Menu. An icon without mute is displayed. Icon isn't clickable
![image](https://user-images.githubusercontent.com/45708377/58081446-c70c0580-7bbd-11e9-9c5b-4cc0118db09b.png)

**Comment by SlayksWood** [comment]
1.You still can't unmute player for this step.
2. When you mute player Tooltip appears at top and blocks icon.
![image](https://user-images.githubusercontent.com/45708377/58306239-94ebe500-7e03-11e9-8c6e-29942ea937af.png)

**Comment by redwyre** [comment]
The blocking issue is a problem with the tooltip, but I've fixed that but I've moved it to the right for unmuting to be consistent with muting.

**Comment by SlayksWood** [comment]
@redwyre 
Everything is fine with tooltips now.
But still an issue with unmute when reopen Esc menu.
Step to reproduce:
- open Esc menu
- mute player (mute icon displays)
- close Esc menu
- open Esc menu
- **Icon without mute is displayed instead mute icon.** Icon isn't clickable.

**Comment by redwyre** [comment]
@SlayksWood can you add a log for that?

**Comment by SlayksWood** [comment]
There is still a minor bug. Step to reproduce:

- open Esc Menu and mute player.
![image](https://user-images.githubusercontent.com/45708377/58932253-b5a12c80-876b-11e9-8b3e-0c253978a4ff.png)
- you can close or not Esc menu, no difference. Another player runs away from you until he disappears in Voice Users
![image](https://user-images.githubusercontent.com/45708377/58934506-53e4c080-8773-11e9-8e37-b5746eb7a5a2.png)
- As soon as another player disappears into Voice Users, he should go back. When he reappears in Voice Users, he will not have a mute icon. He will have unmute icon.
![image](https://user-images.githubusercontent.com/45708377/58934659-ca81be00-8773-11e9-9db1-5d26beb8dc7c.png)
- to unmute player, you need mute player(one more time) and then unmute him.

**Comment by redwyre** [comment]
_Finally_ :P
