### ISSUE TITLE
[0.8.2.0 staging-14-n-2] Incorrect display tax in exchanger

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12421]
Text from mine:
![58459187-7bb0a480-8133-11e9-86e5-984a966c0a54](https://user-images.githubusercontent.com/45708377/58459835-f8904e00-8134-11e9-9f43-117847cb313b.png)
Text from Anna:
![58459250-9a16a000-8133-11e9-9a42-b6d4e5588e0b](https://user-images.githubusercontent.com/45708377/58459837-f9c17b00-8134-11e9-9299-d3e112f65d85.png)

For me, tax 0 for this text should be 3.
For Anna, tax 0 for this text should be 1.
But I suspect that there is something else. Take, for example, store:
Tax in the store pays the one who gets the money.
![image](https://user-images.githubusercontent.com/45708377/58460236-e4008580-8135-11e9-91a2-30d72c92f040.png)
![image](https://user-images.githubusercontent.com/45708377/58460264-eebb1a80-8135-11e9-836b-fd70e1b7fb06.png)

These zeros are displayed because it is confused who pays what tax. I must pay 3 beastynShells in tax. Anna should pay 1 beastynDollars in tax. Since I don't pay tax for beastynDollars It's display zero. Since Anna doesn't pay tax for beastynShells It's display zero.

The exchanger shows a very tangled text. I think it should be displayed  as:
1. For me:
You gave 10 beastynDollars to beastyn in exchange for 30 beastynShells.
You paid 3 beastynShells in tax. Treasury balance: 3014,76 beastynShells (I pay tax from currency which i get)
beastyn paid 1 beastynDollars in tax. Treasury balance: 3033,39 beastynDollars. (Anna pays tax from currency which she get)
For Anna:
Slayks gave 10 beastynDollars to you in exchange for 30 beastynShells.
Slayks paid 3 beastynShells in tax. Treasury balance: 3014,76 beastynShells (I pay tax from currency which i get)
You paid 1 beastynDollars in tax. Treasury balance: 3033,39 beastynDollars.

2. Or for all the same:
Slayks gave 10 beastynDollars to beastyn in exchange for 30 beastynShells.
Slayks paid 3 beastynShells in tax. Treasury balance: 3014,76 beastynShells (I pay tax from currency which i get)
beastyn paid 1 beastynDollars in tax. Treasury balance: 3033,39 beastynDollars.

This is more than enough. And clearer.
P.S. Charging money to the account and in the treasury is correct.

**Comment by WeaselDog** [comment]
@SlayksWood Can you confirm this is still an issue?

**Comment by SlayksWood** [comment]
This is still an issue, we need to make this notifications better.
buyer:
![image](https://user-images.githubusercontent.com/45708377/100216157-03db5a00-2f23-11eb-9103-975ef0595a91.png)
![image](https://user-images.githubusercontent.com/45708377/100216249-1ce40b00-2f23-11eb-94cd-1267edb70754.png)
seller:
![image](https://user-images.githubusercontent.com/45708377/100216302-2c635400-2f23-11eb-93b6-4f7718c965d2.png)
![image](https://user-images.githubusercontent.com/45708377/100216342-39804300-2f23-11eb-85d4-5bc4467ab25d.png)

**Comment by Mattprass** [comment]
Not able to reproduce issues
![ss](https://user-images.githubusercontent.com/31013483/104631997-0e84b680-566b-11eb-978d-9eb3725f0718.png)

**Comment by SlayksWood** [comment]
You can't reproduce it because tax in exchanger doesn't wotk. It should be like in store:
![image](https://user-images.githubusercontent.com/45708377/107361505-89b17f00-6ae8-11eb-9331-bf46bea27bef.png)

**Comment by SlayksWood** [comment]
Tax was partially added, but message don't include it.
![image](https://user-images.githubusercontent.com/45708377/110307285-ca30e980-800f-11eb-84ed-c5d7b56875c3.png)
![image](https://user-images.githubusercontent.com/45708377/110307127-a1a8ef80-800f-11eb-8230-3443e73fcf06.png)
But I guess this issue should be remade a little again #20459

**Comment by WeaselDog** [comment]
Fixed with previous PR. Please recheck in 9.4

**Comment by abaza121** [comment]
Will need to investigate its state after fix in 9,3

**Comment by abaza121** [comment]
This is partially fixed will just need to add the ok box adjustments.

**Comment by abaza121** [comment]
https://github.com/StrangeLoopGames/Eco/pull/8009 tax is added to the confirm box before the ok box based on this pr

**Comment by SlayksWood** [comment]
#21164
