### ISSUE TITLE
[0.8.2.0 staging-14-n] Duplicate text in store

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12425]
![image](https://user-images.githubusercontent.com/45708377/58473394-24b9c800-8151-11e9-8ca5-809e172db2eb.png)

**Comment by beastyn** [comment]
It can't be fixed easily. This messages are from the different actions and going into different channels, so they should have duplicated information for the sake of the sanity.
We will need to reconsider it with chat refactoring

**Comment by johnkslg** [comment]
Probably one is the chat going to global, the other is going to a single user.
You can make the global one exclude the user that is getting a personal message, i think theres an exclusion list you can fill in already (and if not can add it)

**Comment by beastyn** [comment]
I really do not think that this should be solved this kind of way.
This picture is from customer point of view.

First message is the only yours for Your Trades channel.
And the second one  is for the common Transfers channel and everyone will see it. Both of them should contain information about triggering action. Why customer should not get it? This info for everyone right now.
We should solve overall logic for the chat - channels should work like filters and not be switched on by default.
And decide if we want to show trades actions for everyone at all, maybe just Seller-Customer is enough
We actually will have a lot of message from kind of one action: 1- from buying-selling action, 2- from transferring money, from paying taxes. All of then we are showing to everyone in some way.

So I prefer to make general Chat refactoring and improvement epic.

**Comment by WeaselDog** [comment]
Please fix this so it only goes into the trade channel. I can reassign if it is not possible.

**Comment by johnkslg** [comment]
Showing everything to everyone is by design; it gives the feeling of life and activity in a server.
We can hide the 'global' one from the notifications but it can still appear in the history.
Ill make a bug for separating 'activity' notifications from more important ones.

**Comment by beastyn** [comment]
Now by default we have one message in trade chat for everyone.
There is still one temporary message from info popup that is looks the same but it won't stay in the log. We will discuss is more commonly here https://github.com/StrangeLoopGames/EcoIssues/issues/19536
