### ISSUE TITLE
[0.8.2.1] Biome and YieldPotential Layers lost

### ISSUE THREAD

**Issue by owghard** [StrangeLoopGames/EcoIssues#12592]
[SLG] Giant Tortoise https://i.vgy.me/wXxp04.png
[SLG] Sea Otter https://i.vgy.me/MQGxMT.png
etc. (all servers)

Added by @mirasrael:

Actual issue happens with worlds which didn't update EcoSim.eco file (you can actually just remove it, because it will populate values from EcoSim.eco.template by default).
So actual steps to fix it on live server:

Update EcoSim.eco to latest version (either remove or copy from EcoSim.eco.template)
Restart the server
Run following admin commands:
/regenlayer ColdForestBiome
/regenlayer DesertBiome
/regenlayer GrasslandBiome
/regenlayer IceBiome
/regenlayer RainforestBiome
/regenlayer TundraBiome
/regenlayer WarmForestBiome
/regenlayer OceanBiome
/regenlayer TaigaBiome

Check if biomes appeared on map
Eventually biomes will return they colors.

**Comment by redwyre** [comment]
Do you mean just in the minimap?

**Comment by owghard** [comment]
Not only on the minimap, but the effect on the whole world is just like on this screenshot
https://i.vgy.me/J5cV6I.jpg

Just enable the game and enter any 0.8.2.1 server

**Comment by D3nnis3n** [comment]
Medium for now, i don't know if that has any effects on actual gameplay despite looks.

**Comment by D3nnis3n** [comment]
Actually all world layers despite ocean and deep ocean are gone, i think that deserves critical, too.

**Comment by owghard** [comment]
It seems to me that a mass wipe will follow soon

**Comment by D3nnis3n** [comment]
It's only getting brown though, plant life is not affected.

**Comment by mirasrael** [comment]
Actual issue happens with worlds which didn't update EcoSim.eco file (you can actually just remove it, because it will populate values from EcoSim.eco.template by default).
So actual steps to fix it on live server:
1. Update EcoSim.eco to latest version (either remove or copy from EcoSim.eco.template)
2. Restart the server
3. Run following admin commands:
/regenlayer ColdForestBiome
/regenlayer DesertBiome
/regenlayer GrasslandBiome
/regenlayer IceBiome
/regenlayer RainforestBiome
/regenlayer ForestBiome
/regenlayer TundraBiome
/regenlayer WarmForestBiome
/regenlayer WetlandBiome
4. Check if biomes appeared on map
5. Eventually biomes will return they colors.

**Comment by owghard** [comment]
After write command /regenlayer Rainfall
I got
https://i.vgy.me/ariqMu.png

**Comment by Praefator** [comment]
Ran the commands and biomes are returning their colors slowly, but is there any way to expedite the process, like am I supposed to run it multiple times or just let it run its course?

**Comment by mirasrael** [comment]
@Praefator you should just wait. It is a bit random process of replacing blocks with blocks more appropriate for biome. They gone because of biomes was erased, but now they should slowly reappear. Unfortunatelly there are no way to make it faster, but it should only affect visual component, not plants and animals.

**Comment by mirasrael** [comment]
Actually /regenlayer command broken in 8.2.2, so it won't work in all cases. I'm preparing 8.2.3 which will have fixed /regenlayer command and also will automatically fix all broken layers.

**Comment by owghard** [comment]
So this is the reason why in the world of the world nothing regenerates from the morning. :)
If I can ask: 0.8.2.3 when will it be? That's how I ask because people here ask me.

**Comment by mirasrael** [comment]
I can attach here fixed version before 8.2.3, so you haven't wait, but expected release is tomorrow CEST morning

**Comment by owghard** [comment]
We heve time :)

**Comment by mirasrael** [comment]
In case if somebody don't want to wait there are fixed EcoServer.exe compatible with 8.2.2:
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3310431/EcoServer.zip)

**Comment by mirasrael** [comment]
Good news. Seems everything will reappear and it is just visual bug.

**Comment by geek85** [comment]
seems all the biomes are gone in 8.2 I tried commands /regenlayer with the fixed server but no biome are restored.
even Ocean is gone.
https://i.imgur.com/980QSOW.jpg -> used to be a desert. a smal piece keeps standing in yellow because encased with roads and water.

**Comment by mirasrael** [comment]
@geek85 you can send me your save file and I'll check it tomorrow

**Comment by geek85** [comment]
@mirasrael the file is [here](https://framadrop.org/r/2J4ZgqiFf3#O2uRUjebzKV5TJyhaGB1CYXLH6CpxcrRLHikO428sfQ=)

**Comment by D3nnis3n** [comment]
@geek85 Do you also have no more XYZYieldPotential layers for plants?

**Comment by geek85** [comment]
@D3nnis3n how do I verify this?
I have theses informations with Soil Sampler:
https://i.imgur.com/DbE5sdi.png

**Comment by D3nnis3n** [comment]
Open your minimap, to the right there are plant layers, check some of the NAMEOFPLANTYieldPotential layers.

**Comment by geek85** [comment]
No the Yield Potentials seem fine.

**Comment by D3nnis3n** [comment]
Try out some more, especially Corn, Tomatoes and anything that is not a tree.
For me all of that is lost.

**Comment by geek85** [comment]
Corn and Tomatoes are OK too.

**Comment by D3nnis3n** [comment]
Well, my biomes work and yours don't, while my biomes work but the yield layers don't.
@mirasrael Will hopefully find a way to fix all of those issues.

**Comment by mirasrael** [comment]
@geek85 Tried your save on upcoming 8.2.3. It didn't fix automatically, but after running /regen commands it was successfully repaired
![image](https://user-images.githubusercontent.com/475445/59896624-f5b21180-93f1-11e9-999c-4447a8a54e0d.png)

**Comment by mirasrael** [comment]
@D3nnis3n Problem with yield potential related to very low levels of nutrients on this world.
It can't be fixed with /regenlayer, because for nutrients it will set all nutrients to 0.
So new command will be added in 8.2.4: /setlayer

I.e. if you want to have random values over the world you can use following commands:

/setlayer Potassium,0.5,1.0
/setlayer Nitrogen,0.5,1.0
/setlayer Phosphorus,0.5,1.0

or for constant level:

/setlayer Potassium,0.75
/setlayer Nitrogen,0.75
/setlayer Phosphorus,0.75

It will recalculate yield potential for next world tick.

For your world after nutrients fix:
![image](https://user-images.githubusercontent.com/475445/59904269-bf818b80-940b-11e9-87d0-682e58915913.png)

**Comment by mirasrael** [comment]
@D3nnis3n There is a custom build (8.2.2) with /setlayer command:
[EcoServer.zip](https://github.com/StrangeLoopGames/EcoIssues/files/3313364/EcoServer.zip)

**Comment by geek85** [comment]
> @geek85 Tried your save on upcoming 8.2.3. It didn't fix automatically, but after running /regen commands it was successfully repaired

with instructions from https://github.com/StrangeLoopGames/EcoIssues/issues/12592#issuecomment-503934574 , all biomes are back! thanks.

**Comment by geek85** [comment]
Boreal Forest Biome is still missing, Wetland and Forest ones too.

**Comment by mirasrael** [comment]
They are not in game now.

**Comment by mirasrael** [comment]
@geek85 did you have it before?

**Comment by D3nnis3n** [comment]
I do not have wetlands nor forest, but we DO have boreal forest.

**Comment by mirasrael** [comment]
@D3nnis3n your world is new, but @geek85 you can try to run /regenlayer BorealForestBiome

**Comment by geek85** [comment]
@mirasrael I dunno for Forest and Wetland but I do have Boreal. (I used to mine copper in this particular biome)
result of the command: ![image](https://i.imgur.com/FBmPRjI.png)

**Comment by mirasrael** [comment]
Ok. Actually it is /regenlayer TaigaBiome

**Comment by geek85** [comment]
that's it!
![image](https://i.imgur.com/pPtGoLH.png)

**Comment by quequiere** [comment]
![image](https://user-images.githubusercontent.com/2946661/59937334-77398c00-9452-11e9-9e2d-b521a3032439.png)
Not totaly fixed for us, we do regen commands and updated eco files :S

**Comment by mirasrael** [comment]
@quequiere what do you mean saying it wasn't totally fixed? Can you see biomes on minimap with corresponding layers enabled? Colors won't return instantly after fix, instead it will require some time, may be few days for biomes to restore.

**Comment by quequiere** [comment]
@mirasrael 
Oh ok, yes biomes are fixed, so just need to wait ;) Sry !

**Comment by lonely182** [comment]
Deleted the .template file and ran the commands but biomes still not showing :(

**Comment by geek85** [comment]
Do not remove template. Replace .eco with .template

**Comment by lonely182** [comment]
Sorry I meant to say that we deleted the EcoSim.eco file not the template. I dont know why but we dont have the ecosim.eco.template file. The only thing we have is backup.eco.template. Which I dont think is what we need

**Comment by geek85** [comment]
If you installed the game with Steam, delete it and reinstall it. ecosim.eco.template will be installed this way

**Comment by lonely182** [comment]
oh wait do you mean the actual ingame files. Because we use a public host so what we did was go into the files on the server we use not the actual ingame steam folder. Will it help to copy the ingame file to the hosted server files?

**Comment by lonely182** [comment]
Never mind, we figured it out. It turns out had to copy the EcoSim.eco.template from the actual game files into the server config files after deleting the one in there and then running the commands did it.

**Comment by geek85** [comment]
@mirasrael what can I do to greenify islands again?
I have several island on my map which turn marroon when biomes have gone and doesn't turn green again because there is not a single patche of grass anymore on them. 
![image](https://i.imgur.com/UYcqj15.jpg)
Is there a solution to restore these islands?

**Comment by D3nnis3n** [comment]
On a flat area you can use the command /level to spawn grass. Afaik by default it does 6x6 blocks.

**Comment by geek85** [comment]
> 
> 
> On a flat area you can use the command /level to spawn grass. Afaik by default it does 6x6 blocks.

it works for grassland biome but not for Desert/Cold forest/Rainforest ones. :/

**Comment by mirasrael** [comment]
I added fix which will allow to spawn biome blocks even without other biome blocks.

**Comment by D3nnis3n** [comment]
That one works good and also is a nice addition in general, allowing the earth to be more greener for parks.
Closing, reopen if some issues still persist.
