### ISSUE TITLE
[0.8.3.0 staging-1099] Stockpile Highlight Glitch

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12896]
It looks very strange in 8.3.0:
![unknown (4)](https://user-images.githubusercontent.com/45708377/63154912-491f9500-c01a-11e9-8b87-b416ed61c698.png)
If you will move item between two stockpile Highlight can dissapears
![unknown (5)](https://user-images.githubusercontent.com/45708377/63154995-72402580-c01a-11e9-8311-c4e8d3e2d626.png)
![unknown (6)](https://user-images.githubusercontent.com/45708377/63155003-766c4300-c01a-11e9-8608-9a5712bfee87.png)

For comparison 8.2.9:
![image](https://user-images.githubusercontent.com/45708377/63154767-ffcf4580-c019-11e9-8888-4096e4814468.png)

**Comment by mirasrael** [comment]
Fixed in SVN

**Comment by SlayksWood** [comment]
Still an issue.
![image](https://user-images.githubusercontent.com/45708377/63405194-a0dd4800-c3ee-11e9-8330-723ea6013c54.png)
