### ISSUE TITLE
Major Bug Graphics

### ISSUE THREAD

**Issue by tobias443** [StrangeLoopGames/EcoIssues#13032]
Since 8.3.0 Update (MacOS) leaves and small vegetations in desert and jungle bioms are invisible on my server. Also at starting menu of the game.

**Comment by tobias443** [comment]
![pic2](https://user-images.githubusercontent.com/54746860/64066192-2ba41b00-cc17-11e9-94ad-fef7e7d45648.jpg)

**Comment by elfl0rd** [comment]
*offtop
Ecological catastrophe!

**Comment by SlayksWood** [comment]
@tobias443 
Can you show your graphics settings?
Did You start the server on iMac?

**Comment by tobias443** [comment]
Im using only a MacBookAir 2017, also official test servers have invisible vegetations. 

![Bildschirmfoto 2019-09-02 um 17 32 03](https://user-images.githubusercontent.com/54746860/64124716-00046a80-cda8-11e9-8716-4dd5af08a2d2.png)

**Comment by mirasrael** [comment]
1. Do you have latest GPU drivers?
2. Which one video card do you have?

**Comment by tobias443** [comment]
1. as far as i know yes
2. Intel HD Graphics 6000 1536 MB
3. yes, i did reset the graphics to default or "standard"

**Comment by jthill** [comment]
This is not just MacOS, it's Linux also.  On arch, everything up-to-date, 3570K/16GB/1060/3GB, .  A large fraction of the grass on the ground isn't drawn, also sometimes roof tiles placed from below in early buildings.  Can provide a video if you want but take my word for it: it happens early.

**Comment by tobias443** [comment]
![Bildschirmfoto 2019-09-07 um 13 35 31](https://user-images.githubusercontent.com/54746860/64474379-ae2b5e00-d174-11e9-8662-234580617e3b.png)

bluegrass invisible  and tree error in desert biom

**Comment by Solly-W** [comment]
Here are some Player.log files from both 8.2.9 (Where the bug doesn't occur) and 8.3.0 (Where the bug occurs) on Linux. As you can see, the log from 8.3.0 contains extra text repeated multiple times:

`SetConstantBuffer: The current renderer does not support constant buffers. This call will have no effect.`
`(Filename: ./Runtime/Shaders/ShaderPropertySheet.cpp Line: 245)`

If I join a server, it gets spammed thousands of times.

[8.2.9 Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3812030/8.2.9.Player.log)
[8.3.0 Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3812031/8.3.0.Player.log)

**Comment by mirasrael** [comment]
Fixed constant buffer error in 8.3.1. Please let us know if problem with plants fixed after 8.3.1 release.

**Comment by Florian7843** [comment]
> Fixed constant buffer error in 8.3.1. Please let us know if problem with plants fixed after 8.3.1 release.

Bug, is still present in 9.4.3 on Linux. I could check log files, but I don't know where to find them...
