### ISSUE TITLE
[master-preview] Seating problems

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13371]
1.Avatar sitting incorrectly on Chair
![image](https://user-images.githubusercontent.com/45708377/66982834-bce42980-f0bf-11e9-8481-42a937a2bae8.png)
8.3.0:
![unknown (1)](https://user-images.githubusercontent.com/45708377/66982892-dd13e880-f0bf-11e9-903c-0343c053e989.png)
2. Now it’s harder to sit on Сhair and on Padded Chair. You can change sitting system: If you highlight Chair you always Sit. But when you take hammer in hands you always examine Chair (Now this system has Wooden Elevator Call Post and Elevator)
3. Add possibility to sit to old seating: Couch StrangeLoopGames/EcoIssues#10120
4. Add possibility to sit to new seating: all new Ashlar and Wooden Chair/Bench

**Comment by elfl0rd** [comment]
Also about seat.
I think, seating pose need to be improved.
In vechicles (any) just hide backpack and tools from avatar.
At "objects"
Hide, or place backpack on ground, as if the player took it off and put it next to him
![depositphotos_189173512-stock-photo-young-hipster-man-with-backpack](https://user-images.githubusercontent.com/4980243/67001012-8ae3bf00-f0e1-11e9-8696-8bd23020b3da.jpg)

**Comment by keegan-o** [comment]
I agree after trying it that sit and examine should just be two different buttons, like examine versus open for doors is.

**Comment by keegan-o** [comment]
fixed the sit position for the 9.0 chairs

**Comment by elfl0rd** [comment]
As i mention in - https://github.com/StrangeLoopGames/EcoIssues/issues/13371#issuecomment-543110473
still an issue
![изображение](https://user-images.githubusercontent.com/4980243/84380446-06096080-abf0-11ea-906c-3d948c0ccfec.png)

**Comment by elfl0rd** [comment]
also seating on benches...
![изображение](https://user-images.githubusercontent.com/4980243/84380574-3a7d1c80-abf0-11ea-8af4-92c558751f93.png)

**Comment by beastyn** [comment]
@elfl0rd I will make separate issues for that, thanks

**Comment by elfl0rd** [comment]
or not 🤔
