### ISSUE TITLE
0.9 audio settings sliders displacement

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13806]
I think they should be the same length
![изображение](https://user-images.githubusercontent.com/4980243/69225722-efd27f00-0b8f-11ea-94f0-7d07bae8b217.png)

**Comment by beastyn** [comment]
Yeah, but words are running out now )
![bandicam 2019-11-28 15-08-43-765](https://user-images.githubusercontent.com/27898520/69797150-0bbdcc80-11f1-11ea-98b7-666fb90655c7.jpg)

**Comment by SlayksWood** [comment]
when you first time open Audio tab Text overlaps. Step to reproduce:
- open Esc Menu. switch to Audio tab
![image](https://user-images.githubusercontent.com/45708377/70599787-1a4bb100-1bff-11ea-91ea-7f30181b4a8e.png)
- select another tab and then select Audio tab again. All's right:
![image](https://user-images.githubusercontent.com/45708377/70600033-b7a6e500-1bff-11ea-8b11-9924552af8da.png)

**Comment by elfl0rd** [comment]
![изображение](https://user-images.githubusercontent.com/4980243/70600935-0ce3f600-1c02-11ea-876e-60a6d58033ef.png)

**Comment by gzatravkin** [comment]
Should be fixed after https://github.com/StrangeLoopGames/Eco/pull/5354

**Comment by beastyn** [comment]
Still messy in the bottom part
And text should be aligned to the right (is seems to be centered now).

**Comment by SlayksWood** [comment]
@gzatravkin 
I still don’t like this indentation, although functionally it is possibly done well.
![image](https://user-images.githubusercontent.com/45708377/71817435-e4cba380-3096-11ea-9bef-8a17004208fd.png)
