### ISSUE TITLE
[0.9.0 staging-1287] Executive Action Tax Personal Currency cause Crash to Desktop

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#14066]
I made a simple executive action that would tax everyone 100 of their personal currency to the treasury.

![image](https://user-images.githubusercontent.com/2676134/70390259-b42a1880-19c9-11ea-81bf-81ddc33b8cd9.png)
http://95.217.35.61:3031/elections.html?election=5

When I used the `/fin` command my client crashed to desktop. I am unable to rejoin the server, client either freeze on "Entering world..." or crash to desktop.

**Comment by WeaselDog** [comment]
Important information:
- It crashes everyone on the server at the time the action passes and prevents them from reconnecting
- It happens for both pay and tax executive actions
- It only happens when using Personal Currency and not a specific currency
- It does not matter if you use a command to pass it

Really need to investigate this more to see how many laws are affected by this

**Comment by johnkslg** [comment]
Fixed a few things in here.
Split Executive Action into actions run on users, and actions run once.  Made 'Actions run once' specially ignore the 'citizen' context, since there's no such context for that, but 'Actions on Each User' needs it.
![image](https://user-images.githubusercontent.com/3536496/70481317-0a18c200-1a97-11ea-8a11-51b1d38bb734.png)

![image](https://user-images.githubusercontent.com/3536496/70481252-e190c800-1a96-11ea-8908-b758cae6e301.png)
![image](https://user-images.githubusercontent.com/3536496/70481279-efdee400-1a96-11ea-9ac8-837a4788140f.png)


Also fixed up the way it describes it for web:
![image](https://user-images.githubusercontent.com/3536496/70481331-169d1a80-1a97-11ea-9c1d-7cab4aeb5ca1.png)
(there's a forthcoming PR to fix the formatting problems)

**Comment by beastyn** [comment]
Didn't actually get it.
1. How citizen condition work?
If you apply Action on each citizen - it will count only citizen from condition part?
2. Why do we need distinguish actions, if I can apply target anyway in Action on Each Citizen?
3. I can't choose Citizen in Target for Action on each user (its here only by default)

**Comment by beastyn** [comment]
Still crashing on the desktop with executive action like this
![bandicam 2019-12-11 17-51-26-346](https://user-images.githubusercontent.com/27898520/70623089-1d669180-1c3f-11ea-8123-385eb30f49af.jpg)

**Comment by johnkslg** [comment]
I was able to select citizen:
![image](https://user-images.githubusercontent.com/3536496/71133935-404df400-21b1-11ea-9bf2-3ec48167b53f.png)

This action didnt cause any problems for me:
![image](https://user-images.githubusercontent.com/3536496/71133957-56f44b00-21b1-11ea-8d95-e7c38935cd2d.png)

I clarified help text more on the properties, hopefully it explains it better.
Can you see if latest version is giving you a problem?

**Comment by beastyn** [comment]
I don't have problems with crashing part anymore.
But this Demographic context is missed for me.
![bandicam 2019-12-19 14-20-49-668](https://user-images.githubusercontent.com/27898520/71164351-ad748e80-2270-11ea-841a-f44e31217a96.jpg)

And still don't get the difference of these two actions )
