### ISSUE TITLE
[0.9.0 staging-1291] Balance for Food

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14088]
without including #14036

- [x] 1. Charred Beans use nutrients from Charred Beet. Need to change nutrients as it was in 8.3.0:
![image](https://user-images.githubusercontent.com/45708377/70523729-b66cae00-1b54-11ea-9d8b-6c56080576e7.png)
Early It called Campfire Beans.

- [x] 2. Perhaps the wrong number of items on recipes. By analogy with 8.3.0:
Charred Beans - 4 Beans.
![image](https://user-images.githubusercontent.com/45708377/70524216-c0db7780-1b55-11ea-86e0-af34add67713.png)
Charred Fireweed Shoots - 2 Fireweed Shoots.
![image](https://user-images.githubusercontent.com/45708377/70524237-cafd7600-1b55-11ea-90e2-96361cd3d71e.png)
Charred Taro - 2 Taro.
![image](https://user-images.githubusercontent.com/45708377/70524090-807bf980-1b55-11ea-80b9-baf6087387c1.png)
Wilted Fiddleheads - 6 Fiddleheads.
![image](https://user-images.githubusercontent.com/45708377/70524075-79ed8200-1b55-11ea-968d-41514b56a4ef.png)

- [x] 3. Bannock change Tallow to t.i. "Fat".

- [x] 4. Campfire Salad. We have 5 recipes with same nutrients. Are we need in this recipes? I theink it enough one recipe: Campfire Salad. But if you want to use 5 reecipes you need to change nutrients in all recipes.
![image](https://user-images.githubusercontent.com/45708377/70524540-6c84c780-1b56-11ea-9da6-e04decead0be.png)

- [x] 5. Fried Vegatables. Use t.i. "Fat" instead Tallow:
![image](https://user-images.githubusercontent.com/45708377/70524713-d309e580-1b56-11ea-88cd-ad26d0406111.png)
Change nutrients in recipes. Now this recipes use nutrients from Fried Tomatoes.
![image](https://user-images.githubusercontent.com/45708377/70524925-457ac580-1b57-11ea-958b-b832cd69f485.png)

- [x] 6. Need change nutrients in Topped Porridge recipes:
![image](https://user-images.githubusercontent.com/45708377/70526306-5a0c8d00-1b5a-11ea-9c4d-4d2413a2bb12.png)

- [x] 7. Need change nutrients in Campfire Stew recipes and Use t.i. "Fat" instead Tallow:
![image](https://user-images.githubusercontent.com/45708377/70526343-701a4d80-1b5a-11ea-93de-509d0156e19e.png)

Also wrong ingredients for Wild Stew. You need to add 6 Charred Beans (Campfire Beans analog) to the recipe. In 8.3.0:
![image](https://user-images.githubusercontent.com/45708377/70526682-33028b00-1b5b-11ea-9345-e39efc997e80.png)

**Comment by SlayksWood** [comment]
- [ ] Delete Wheat and Rice from Charred Food recipe (from RawFood), because we have separate Boiled Grains recipe. It isn't profit to craft with Boiled Grains while we have Charred Food from Wheat and Rice.

**Comment by Sekor2600** [comment]
1. Baked Meat use 10 tagged items (t.i.) "Meat" instead 5 Raw Meat in 8.3.0:

image
If you decide to increase the cost of the recipe and use more expensive meat, you should not combine in t.i. "Meat" meat with different values. You must use only Prepared Meat or only Prime Cut. The difference in their crafting is almost 4 times.
image
For crafting Baked Meat you used only Meat, but Nutriens we have with Carbs and Vitamins:
image
In 8.3.0 we have only Fat and Protein:
image
Or Add some Vegatable to craft or change Nutriens.

2. Baked Roast. We have another recipe in 0.9.0 staging-1291. The recipe contains only meat:
image
I think we should return something like old recipe:
image
You can use t.i "Vegetable", "Greens" inseat Fiddleheads, Corn.

3. Many new Baked Vegatable recipes have been added. But the nutrients in new recipes are used as in Baked Agave (Carbs:12, Protein:2, Fat:6, Vitamins:8.). It is necessary to change nutrients for Baked Vegatable, Baked Beet, Baked Corn, Baked Heart of Palm, Baked Taro, Baked Tomato.

4. Same for Fruit Muffin. The Nutriens used as in Huckleberry Muffin (Carbs:10, Protein:5, Fat:4, Vitamins:11.). It is necessary to change nutrients for Fruit Muffin, Papaya Muffin, Pumpkin Muffin.

5. Huckleberry Pie. Use t.i "Fat" instead Tallow.

6. You add new recipe Leavened Dough but it's never used. I suppose that you plan to use it in recipes like Bread, Camas Bread, may be Elk Wellington and Macaroons, and may be for new recipes in future. I think it needs to move it to Advanced Baking. Because all recipes where it can be used in Advanced Baking.
With this in mind, you need to review the ingredients for these recipes: Bread, Camas Bread, Elk Wellington and Macaroons.

7. Meat Pie. Use t.i "Fat" instead Tallow.

8. Change nutriens for Pastry, Fruit Tart and Pirozhki (It is in the plural. Better use as "Pirozhok"). Now it used Bearclaw nutriens.

**Comment by Sekor2600** [comment]
- [x] 1. Baked Meat use 10 tagged items (t.i.) "Meat" instead 5 Raw Meat in 8.3.0:

![image](https://user-images.githubusercontent.com/45708377/70504261-6da5fc80-1b36-11ea-89c0-25016e830e66.png)
If you decide to increase the cost of the recipe and use more expensive meat, you should not combine in t.i. "Meat" meat with different values. You must use only Prepared Meat or only Prime Cut. The difference in their crafting is almost 4 times.
![image](https://user-images.githubusercontent.com/45708377/70504408-ca091c00-1b36-11ea-8ce3-1a0a29dd2d92.png)
For crafting Baked Meat you used only Meat, but Nutriens we have with Carbs and Vitamins:
![image](https://user-images.githubusercontent.com/45708377/70504632-2b30ef80-1b37-11ea-9103-9c0f08c0b91d.png)
In 8.3.0 we have only Fat and Protein:
![image](https://user-images.githubusercontent.com/45708377/70504728-60d5d880-1b37-11ea-9ed1-b15ff6bfb6b2.png)
Or Add some Vegatable to craft or change Nutriens.

- [x] 2. Baked Roast. We have another recipe in 0.9.0 staging-1291. The recipe contains only meat:
![image](https://user-images.githubusercontent.com/45708377/70504901-c1fdac00-1b37-11ea-983b-75e89875b28b.png)
I think we should return something like old recipe:
![image](https://user-images.githubusercontent.com/45708377/70504992-f2dde100-1b37-11ea-8b18-a38f46925647.png)
You can use t.i "Vegetable", "Greens" inseat Fiddleheads, Corn.

- [x] 3. Many new Baked Vegatable recipes have been added. But the nutrients in new recipes are used as in Baked Agave (Carbs:12, Protein:2, Fat:6, Vitamins:8.). It is necessary to change nutrients for Baked Vegatable, Baked Beet, Baked Corn, Baked Heart of Palm, Baked Taro, Baked Tomato.

- [x] 4. Same for Fruit Muffin. The Nutriens used as in Huckleberry Muffin (Carbs:10, Protein:5, Fat:4, Vitamins:11.). It is necessary to change nutrients for Fruit Muffin, Papaya Muffin, Pumpkin Muffin.

- [x] 5. Huckleberry Pie. Use t.i "Fat" instead Tallow.

- [x] 6. You add new recipe Leavened Dough but it's never used. I suppose that you plan to use it in recipes like Bread, Camas Bread, may be Elk Wellington and Macaroons, and may be for new recipes in future. I think it needs to move it to Advanced Baking. Because all recipes where it can be used in Advanced Baking. 
With this in mind, you need to review the ingredients for these recipes: Bread, Camas Bread, Elk Wellington and Macaroons.

- [x] 7. Meat Pie. Use t.i "Fat" instead Tallow.

- [x] 8. Change nutriens for Pastry, Fruit Tart and Pirozhki (It is in the plural. Better use as "Pirozhok"). Now it used Bearclaw nutriens.

**Comment by Sekor2600** [comment]
[]Review all Cooking Recipe in values and Recipe

**Comment by WeaselDog** [comment]
Move Rice Sludge, Wheat Sludge, Wilted Fiddleheads to Advanced Campfire Cooking skill 0

**Comment by WeaselDog** [comment]
All are fixed except swapping plural name for Pirozhki. Will include this is a separate issue focusing on plural names.

**Comment by SlayksWood** [comment]
I will take out to here old points that are not fixed:

- [ ] Need change nutrients in Campfire Stew:
![image](https://user-images.githubusercontent.com/45708377/72788605-3cdfd980-3c43-11ea-8ead-a00eae95abfd.png)
We have same nutriens for 4 recipe. Also Campfire Stew have same ingredients with Jungle Stew. We can use in Jungle Stew Fruits instead Vegetables.

- [ ] 2. Baked Roast. We have another recipe in 0.9.0 staging-1291. The recipe contains only meat: ![image](https://user-images.githubusercontent.com/45708377/70504901-c1fdac00-1b37-11ea-983b-75e89875b28b.png)
I think we should return something like old recipe:
 ![image](https://user-images.githubusercontent.com/45708377/70504992-f2dde100-1b37-11ea-8b18-a38f46925647.png)
You can use t.i "Vegetable", "Greens" inseat Fiddleheads, Corn.

- [ ] Fried Fiddleheads has 26 nutriens instead 23:
![image](https://user-images.githubusercontent.com/45708377/72788922-c2fc2000-3c43-11ea-8149-4063a98eaeb4.png)
Also Fiddleheads isn't vegetable it's Greens. So you need move this recipe. And Add Recipes for All vegitables.

**Comment by WeaselDog** [comment]
Baked Roast change is intentional. The recipe is unused with the current costs. Compared it to Campfire Roast. 
Jungle Stew is a duplicate recipe that needs to be removed. It was marked in PR notes.
There is no category for Fried Greens, so we could make it so it does not have a category.

**Comment by WeaselDog** [comment]
I will include the remaining changes with the PR that includes the Raw Food balance
