### ISSUE TITLE
USER ISSUE: ECO Map randomly no longer works, No maps will open without this Error

### ISSUE THREAD

**Issue by UncleBirb** [StrangeLoopGames/EcoIssues#14107]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
1. Opened Game 2. Hit Continue 3. Connection Failure.

**Expected behavior:**
Opened my map, instead it says it can't connect, PC and Steam are ONLINE and only this game is aallegedly not Connecting. Forums show this as a bug that still hasnt been patched.

**Actual behavior:**
Failed to COnnect - Connection Timed out

**Do you have mods installed? Does issue happen when no mods are installed?:**
Failed to COnnect - Connection Timed out

**Comment by UncleBirb** [comment]
This is a purely Vanilla map, no mods or anything. Thought that might be important to note.

**Comment by UncleBirb** [comment]
<size=150%>Connection Failed</size>

Failed to connect - connection timed out.

Log File:
Initialize engine version: 2019.1.6f1 (f2970305fe1c)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c82)
    Vendor:   
    VRAM:     4018 MB
    Driver:   26.21.14.3615
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.802500 ms
MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 275)

Logging in as 76561198049011651 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NjAyNjIyMywidnhhIjoibG9naW4iLCJ2eGkiOjMxMzI0MSwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwNDkwMTE2NTEuQG10MXAudml2b3guY29tIn0.MnPCDkMz7ErxbJVh5ANOmazr_eYjthdmVDa6khKVJMQ
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
 
(Filename: C:\buildslave\unity\build\PlatformDependent/WinPlayer/ScreenManagerWin.cpp Line: 275)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to connect - connection timed out.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to establish connection - no response from remote host
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
Unity.Entities.F_C`1:Invoke(T0)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 16 unused Assets to reduce memory usage. Loaded Objects now: 86986.
Total: 226.157600 ms (FindLiveObjects: 6.865100 ms CreateObjectMapping: 5.231700 ms MarkObjects: 213.418900 ms  DeleteObjects: 0.641300 ms)

Logging in as 76561198049011651 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NjAyNjMyNSwidnhhIjoibG9naW4iLCJ2eGkiOjMxMzI2MiwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwNDkwMTE2NTEuQG10MXAudml2b3guY29tIn0.eNzpSo2rK9ACzS9dnJT1Vfo2gTn_AMYUyaOTWDP86TA
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to connect - connection timed out.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to establish connection - no response from remote host
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
Unity.Entities.F_C`1:Invoke(T0)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 87174.
Total: 223.506200 ms (FindLiveObjects: 6.397600 ms CreateObjectMapping: 3.919500 ms MarkObjects: 212.805500 ms  DeleteObjects: 0.383300 ms)

Logging in as 76561198049011651 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NjAyNjY0NywidnhhIjoibG9naW4iLCJ2eGkiOjMxMzI5MSwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwNDkwMTE2NTEuQG10MXAudml2b3guY29tIn0.2r4FLoyWLeMF6O6Ol3HUW8XVL5WC4HhFDezy7UMjOOE
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to connect - connection timed out.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to establish connection - no response from remote host
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
Unity.Entities.F_C`1:Invoke(T0)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 87231.
Total: 228.989300 ms (FindLiveObjects: 7.577200 ms CreateObjectMapping: 3.970700 ms MarkObjects: 217.040300 ms  DeleteObjects: 0.400500 ms)

Logging in as 76561198049011651 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NjAyNjcwOSwidnhhIjoibG9naW4iLCJ2eGkiOjMxMzI5NCwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwNDkwMTE2NTEuQG10MXAudml2b3guY29tIn0.J0fjRqus-CLNmHEMKlBaPtAl4_SeldkPCdoZqIH74E4
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)

Unloading 6673 unused Assets to reduce memory usage. Loaded Objects now: 154371.
Total: 403.380800 ms (FindLiveObjects: 17.234000 ms CreateObjectMapping: 11.328400 ms MarkObjects: 349.624100 ms  DeleteObjects: 25.193400 ms)

Logging in as 76561198049011651 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NjAyNzI2MSwidnhhIjoibG9naW4iLCJ2eGkiOjMxMzM3MSwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwNDkwMTE2NTEuQG10MXAudml2b3guY29tIn0.v0QZ_ETDDOCjXIjkn0iDZYjGy1lwhRkw8Mtg_Qtc2n8
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to local host.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connecting to 127.0.0.1:3000...

UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:WriteLine(LocString)
Eco.Shared.Networking.NetworkClient:ConnectInternal(IPEndPoint)
Eco.Shared.Networking.NetworkClient:Connect(IPEndPoint)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Connection complete.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UI.ConnectionUI:ManualUpdate()
UI.UIManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Disconnected with error: Failed to connect - connection timed out.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleTimeout()
Eco.Shared.Networking.NetworkClient:Update()
NetworkManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Disconnected with error: Failed to establish connection - no response from remote host
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
RootMotion.FinalIK.GrounderDelegate:Invoke()
Unity.Entities.F_C`1:Invoke(T0)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
RootMotion.FinalIK.GrounderDelegate:Invoke()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)


Unloading 42 unused Assets to reduce memory usage. Loaded Objects now: 154563.
Total: 350.386000 ms (FindLiveObjects: 13.997000 ms CreateObjectMapping: 6.966500 ms MarkObjects: 328.208600 ms  DeleteObjects: 1.213200 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 154563.
Total: 343.012200 ms (FindLiveObjects: 12.907600 ms CreateObjectMapping: 6.602600 ms MarkObjects: 323.142600 ms  DeleteObjects: 0.358800 ms)

Logging in as 76561198049011651 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NjAyNzMwNiwidnhhIjoibG9naW4iLCJ2eGkiOjMxMzM3NSwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwNDkwMTE2NTEuQG10MXAudml2b3guY29tIn0.DPPcQ8pRFVzSrS_jTsrXtz5Oo5El89Ni5um6YX5o17o
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logging in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.LoginSession:BeginLogin(Uri, String, AsyncCallback)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Logging in as 76561198049011651 using token e30.eyJpc3MiOiJzdHJhbmdlbG9vcGdhbWVzLWVjbyIsImV4cCI6MTU3NjAyNzMwNiwidnhhIjoibG9naW4iLCJ2eGkiOjMxMzM3NiwiZiI6InNpcDouc3RyYW5nZWxvb3BnYW1lcy1lY28uNzY1NjExOTgwNDkwMTE2NTEuQG10MXAudml2b3guY29tIn0.t3dVaTW3qoybwyfiz5s3-Zr3j_4pzurPdap72CFgi7Q
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
VoiceManager:LoginUser(String, String, String)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Error parsing voice login reponse
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
<LoginCoroutine>d__45:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

Voice chat logged in
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Eco.Shared.Utils.Log:Debug(String, Object[])
VoiceManager:LoginSession_PropertyChanged(Object, PropertyChangedEventArgs)
System.Collections.Specialized.NotifyCollectionChangedEventHandler:Invoke(Object, NotifyCollectionChangedEventArgs)
VivoxUnity.Private.LoginSession:set_State(LoginState)
VivoxUnity.Private.<>c__DisplayClass39_0:<Login>b__0(IAsyncResult)
DraggableHandler:Invoke(Draggable)
VivoxUnity.AsyncResult`1:SetComplete(T)
VivoxUnity.VxClient:InstanceOnMainLoopRun(Boolean&)
Mono.Unity.unitytls_x509list_free_t:Invoke(unitytls_x509list*)
VivoxUnity.Client:RunOnce()
VoiceManager:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

**Comment by beastyn** [comment]
1. Can you try to connect to official servers (Sea Otter and Giant Tortoise) and provide log files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
2. Can you see servers in list normally? With ping and server info?
3. Do you have Firewall or Antivirus enabled?
4. Which kind of internet connection are you using?
5. Please provide your PC specification (include Operating System).
6. Did you meet this issue after updating to the "latest build" or you had it before?
7. Do you have external IP address and did you use it in config file?

Also, can you try to load your world with Load button in the main menu.

**Comment by UncleBirb** [comment]
I’m able to connect to official servers, they list normally and my ping is
around 20, I use a Ethernet connection to a broadband network (Comcast),
the issue I have is that by hitting continue or load. I get the connection
error. However I CAN open a brand new map up with 0 issues. From what I’ve
read on forums this seems to be a bug that occurs to maps randomly making
them unplayable. I’m on the most recent stable update with my maps, as I
just recently purchased the game. My firewall isn’t up when I play Eco, and
I use Windows 10.

**Comment by beastyn** [comment]
Which port do you use for server?
Did you try to launch server from folder?

**Comment by UncleBirb** [comment]
I use the multiplayers default port, I launch multiplayer though the game
“load map” that was set to 3-10 players.

**Comment by SlayksWood** [comment]
Thank you for report.
dup #12763. This issue already fixed in 0.9.0.

**Comment by UncleBirb** [comment]
It most certainly was not fixed. I logged on last night and the same error
occurred yet I could join servers just fine.

**Comment by SlayksWood** [comment]
@UncleBirb It fixed in 0.9.0 staging-1314. For you it will fixed after release 0.9.0.
