### ISSUE TITLE
[0.9.0 staging-1309] Laws: some triggers won't work

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14226]
1. Place or pickup object (with matching obj and condition).
A law is like this
![bandicam 2019-12-25 12-28-57-360](https://user-images.githubusercontent.com/27898520/71437268-b7840a80-2712-11ea-8fdf-19366a2444e7.jpg)

When I am about to place a bloomery, tigger fails
![bandicam 2019-12-25 12-30-50-718](https://user-images.githubusercontent.com/27898520/71437318-f74af200-2712-11ea-859f-165def9b185d.jpg)
2. Drop or Pickup   (with matching obj and condition).
A law is like this
![bandicam 2019-12-25 12-41-33-180](https://user-images.githubusercontent.com/27898520/71437567-1ac26c80-2714-11ea-95cf-2b6f620ae819.jpg)
![bandicam 2019-12-25 12-41-39-443](https://user-images.githubusercontent.com/27898520/71437577-2ada4c00-2714-11ea-9fed-3b7fe4f1b222.jpg)

And looks like all trigers with the matching objects won't work

**Comment by johnkslg** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3536496/71534379-47f95100-28b3-11ea-8c1e-03d34b80f543.png)

Also renamed to DropOrPickupBlock to differentiate it better from Object

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/71543141-d982c480-2980-11ea-9835-4ef28b282600.png)

**Comment by johnkslg** [comment]
Fixed again!
![image](https://user-images.githubusercontent.com/3536496/71635071-13003d80-2bd6-11ea-9ad8-7afb87dff8be.png)

**Comment by WeaselDog** [comment]
Can confirm, both cases are fixed now:
![DropObject](https://user-images.githubusercontent.com/47330823/71784752-d2287000-2fab-11ea-8dc4-456992398b09.png)
