### ISSUE TITLE
[0.9.0 staging-1309] Can't use bank accounts in Civic objects.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14225]
I have 3 bank account:
![image](https://user-images.githubusercontent.com/45708377/71437739-f5c5fd80-2703-11ea-96a5-4c38f4fec9d2.png)
Can't use my bank accounts in laws:
![image](https://user-images.githubusercontent.com/45708377/71437754-04141980-2704-11ea-966a-94c773be2132.png)

Can't use Treasury in Wages:
![image](https://user-images.githubusercontent.com/45708377/71437490-1477c480-2703-11ea-8a9e-65b50f774645.png)
I think it shoulb like in laws:
![image](https://user-images.githubusercontent.com/45708377/71437510-28bbc180-2703-11ea-9dd5-7fd4f7bb72e2.png)

**Comment by johnkslg** [comment]
Fixed to work as you described.

**Comment by SlayksWood** [comment]
Still can't use Treasury and my bank accounts in Wages (Government office)
![image](https://user-images.githubusercontent.com/45708377/71541005-8cdcc080-2963-11ea-847d-e310b7a28f8f.png)

**Comment by johnkslg** [comment]
Working on mine, recheck in latest staging? 
![image](https://user-images.githubusercontent.com/3536496/71698415-4c6cb080-2d70-11ea-816e-7a2bd83c0ac3.png)

**Comment by beastyn** [comment]
fine for me
