### ISSUE TITLE
[8.3.0] /addimpacthours doesnt work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#14278]
The meteor still hits in due time.

**Comment by WeaselDog** [comment]
I see the issue. There is a problem with the conversion from hours to days and the config doesn't save. The issue with the config not saving also applies to a few other commands like /setspawn.

**Comment by WeaselDog** [comment]
I did a lot of testing and the issue with /addimpacthours. The updated impact time was not saving after restarting the server. It would show up in-game, but after a server restart the changes would be undone. It is fixed now.

**Comment by beastyn** [comment]
still won't save hours after server restart.
![bandicam 2020-01-03 10-20-12-496](https://user-images.githubusercontent.com/27898520/71708463-601d2300-2e13-11ea-9322-87ce76231929.jpg)
![bandicam 2020-01-03 10-24-57-176](https://user-images.githubusercontent.com/27898520/71708465-614e5000-2e13-11ea-9393-7b99e545c7f0.jpg)

**Comment by WeaselDog** [comment]
It is fixed on my end. The numbers don't matter, but here is how I replicate.
Server has less than one day to impact:
![Meteor1Day](https://user-images.githubusercontent.com/47330823/71737698-4ecf1900-2e09-11ea-881f-eca84d23633a.png)

Type /meteor addhours 168 to add one week. Close server and restart. Now see this:
![MeteorOneWeek](https://user-images.githubusercontent.com/47330823/71737756-7aea9a00-2e09-11ea-81b1-c1e178df1beb.png)

**Comment by WeaselDog** [comment]
@beastyn Do you mind rechecking when you have time? It is hard to tell what went wrong in your test because the meteor times do not match. If it fails to save after restart it should just have the original meteor impact time.

**Comment by beastyn** [comment]
seems fine now

**Comment by beastyn** [comment]
Actually. Seems there is a problem with hours hours if adding with minus (if it will be less than 30 days).
Like /meteor addhours -400

Can you check this situation?

**Comment by WeaselDog** [comment]
I think I see see the issue. I have it setup now so it will return an error message if trying to cause a meteor impact with this command. Will that fix the issue?
There is another option to add a new RemoveHours command and disallow negative numbers with AddHours.

**Comment by beastyn** [comment]
fine for now. Will make remove command if requested
