### ISSUE TITLE
[0.9-1512] Bank authorization for other users

### ISSUE THREAD

**Issue by Chris-85** [StrangeLoopGames/EcoIssues#15811]
If a Bank is placed and everyone or a demografic is authorized the user can`t use the bank to manage accounts (can´t add managers or users). But the creation of accounts works.

If you auth that user on the deed of the property, its working! If you de auth, its not working anymore. Can be reproduced easily!

**Comment by NN-Mike** [comment]
![](https://cdn.discordapp.com/attachments/680068515658596364/700078542955872407/unknown.png)

The same applies to the registrar and titles

**Comment by johnkslg** [comment]
Fixed, thanks @Chris-85 !

**Comment by Chris-85** [comment]
Retested with build 1515, still reproducable! So it seems not to be fixed properly

**Comment by SlayksWood** [comment]
fixed in Staging-1519
