### ISSUE TITLE
[0.9.0 Staging-1538] - Crafting Recipes show more than maximum ingredients

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16144]
Steps to reproduce: Craft a recipe with more items than needed in linked storage
Expected behaviour: Supplied item number would show numbers up to the total required, but not in excess.
Actual behaviour: The number of items supplied exceeds the number required.
Screenshot - "86 out of 40 Plant Fibers added":
![image](https://user-images.githubusercontent.com/48172405/81015081-f4e16d00-8e55-11ea-960f-544cddd8d142.png)

**Comment by johnkslg** [comment]
Fixed this up and took another pass to show whats in storage more clearly
![image](https://user-images.githubusercontent.com/3536496/81355286-df04bf80-9082-11ea-9e75-3da92878d5e0.png)

**Comment by trickenso** [comment]
@johnkslg I might be missing something, but your screenshot still shows "2 out 0 woods required". Maybe a minor thing, but it's a bit confusing what this is actually trying to say - Is it saying it has 2 wood available in storage, but doesn't require any more for the current repetition?

If it requires 0 wood it might be clearer if it indicated "2 of 2 Woods added" or "O wood required" or something - to indicate that the current repetition already has enough wood.
