### ISSUE TITLE
2D Map view should be able to see the whole world at once

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#16205]
I have always wanted this feature for the 2D map: to be able to zoom out and see the whole world. I think it is a significant issue that you can't do this in-game, for our game that is about finite resources and space.

In 2D mode the view should be able to zoom out, until you can see the whole world as a square with edges. It should not repeat/loop. 

The edges should have a very simple border and there should be a very simple background-- the background can be the same as the 3D map, and the border could be just black cubes or a thick line.

In the meantime, if it is easier to get it to zoom out to a point where you can see the whole world, and the edges do loop, this would be acceptable for now as well-- the big deal in this issue is being able to see everything at once.

**Comment by SlayksWood** [comment]
The biggest problem with cut off border will be moving the map. Your borders will be"twitch"
https://drive.google.com/file/d/1JR50eSMa8OqAGwA2oCb0lmSE7rFxlXDZ/view?usp=sharing

**Comment by mirasrael** [comment]
I fixed this to scale to max width or height (depending on aspect ratio). So if you make square map view then you will be able to see whole map at once.

**Comment by SlayksWood** [comment]
@keegan-o is it enough?
![image](https://user-images.githubusercontent.com/45708377/82531073-4fade080-9b47-11ea-8167-57d28fac5e9e.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/82698270-527c0480-9c1f-11ea-9a06-91bdfb9f181f.png)
It's better but it's still not the whole map at once-- with lots of effort I can get pretty _close_ to the whole map at once but never all the way there, and for me the point is that it should be *easy* to see the whole map at once by zooming all the way out. 

We could push the issue off 9.0 I think now because it does feel better. But for me the point is still to see everything at once, with a clear edge so that you don't have to wonder if you're missing something. The edge will have to be within the UI with an empty background beyond it in order to feel like you are seeing everything clearly and not obscured by the fading in frame of the UI or other things. 

Since that's a lot more work, what if we transformed this into a 9.1 task? Alternately, we can close this and I can open a new 9.1 task for a 'Map with Edges View'

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/82699558-c0c1c680-9c21-11ea-857a-aec69363844b.png)
Here's the difference between 'almost' and the whole map with a border--
This difference is not huge but it means that you aren't scrolling around to make sure you're not missing anything, and the bigger feature would be the ability to toggle this mode, and zoom in on a corner. If you could zoom in and out on just one single non-repeated map you'd have a much better sense of a particular area's relationship to the size of the whole world.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/82700566-45611480-9c23-11ea-91dc-2d638f7055b6.png)
mock-up of zooming into an edge

**Comment by keegan-o** [comment]
Another reason I want this feature is that I think the full screen map mode should allow you to view world layers with the whole world in view.

With the map currently, this is the furthest you can zoom out:
![image](https://user-images.githubusercontent.com/14983165/82700905-fb2c6300-9c23-11ea-9a78-6533d4509997.png)

Here's a mock-up of 'edge mode', full screen:
![image](https://user-images.githubusercontent.com/14983165/82701118-65dd9e80-9c24-11ea-8078-6ce8cb5d4fbd.png)

It would allow you to browse through world layers in a comfortable full screen UI and see their extent on the whole world, from inside the game. Would be particularly nice for things like trample, ground pollution, etc etc.

**Comment by keegan-o** [comment]
If we did that for **9.1** we can work with Milenko to make sure we have a cool tiling background and frame for the map. Does that sound doable @mirasrael ?

**Comment by keegan-o** [comment]
Definitely this should be a toggle within settings, too, I'm not suggesting we replace the current functionality which does look nice.
