### ISSUE TITLE
Can't select DevToolItem while carrying logs, but apparently you can select anything else

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#1631]
I had logs and a hammer.  I could scroll and select anything on my hotbar (random items, empty slots), but not the dev tool.

**Comment by metachronism** [comment]
as far as I can tell, this is working as intended.  might have been fixed before

**Comment by MarjieAVolk** [comment]
Test is still failing.  Behavior looks the same as when I opened the bug.  When carrying dirt, I can't switch to any other tools, but I can switch to non tool items and empty toolbar slots.  That doesn't seem correct to me
