### ISSUE TITLE
Chat window displays vertical artifact when you first open it

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16904]
![animx22](https://user-images.githubusercontent.com/3536496/85960422-265b4e00-b958-11ea-9811-c6968bbac79f.gif)
It appears to be the icons in the text not getting masked for a frame. 
Probably needs to delay a frame or update text layout immediately.

**Comment by johnkslg** [comment]
@serpopov plz advise if you have any info

**Comment by gzatravkin** [comment]
Can't repro at lastest staging. Maybe was fixed by changes of TMPro version.

**Comment by SlayksWood** [comment]
Still an issue:
![2020 07 14 Chat window displays vertical artifact ](https://user-images.githubusercontent.com/45708377/87420228-949d4300-c5dd-11ea-8e99-58a20097256b.gif)
Try to change chat size and find needed icons.

**Comment by SlayksWood** [comment]
Still an issue:
![2020 07 17 Chat window displays vertical artifact ](https://user-images.githubusercontent.com/45708377/87766131-5d1ed880-c821-11ea-9aca-141431c376e6.gif)

**Comment by SlayksWood** [comment]
Seems fixed
