### ISSUE TITLE
[0.9.0 staging-1633] Blackout in Main menu

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16926]
Press New game or Host a World:
- you can see some blackout:
![image](https://user-images.githubusercontent.com/45708377/85997795-a6de8500-ba12-11ea-9c92-537d60b7a4d7.png)
![image](https://user-images.githubusercontent.com/45708377/85997837-b78efb00-ba12-11ea-97c8-cbaf92d38d0b.png)

**Comment by gzatravkin** [comment]
Proabably was fixed in 6332 (can't reproduce after null reference fix), but if not, please attach log file too

**Comment by beastyn** [comment]
Still the same.
Actually it looks pretty strange. Borders are fine, bright white, but letters are dim.
![bandicam 2020-07-03 10-36-24-021](https://user-images.githubusercontent.com/27898520/86435296-186f4980-bd19-11ea-80e5-414bb1b05557.jpg)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4867912/Player.log)

**Comment by gzatravkin** [comment]
Still wasn't able to reproruce in editor (maybe it's just on builded version).
But added override of sorting layers, so background is on other layer than text.
Let's see if it fixed it.

**Comment by SlayksWood** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/45708377/86900385-f3614900-c113-11ea-8b00-87d4c8687eca.png)
![image](https://user-images.githubusercontent.com/45708377/86900513-1c81d980-c114-11ea-8920-2fdde73486b3.png)
