### ISSUE TITLE
[0.9.0.0 beta staging 3] New player can become stuck after placing tent

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17161]
If you place the tent in a way you are between the table on the side of the tent, you will become stuck beetween the table and the tent (you will be able to move a little but you will not be able to go out). This can be an issue if this happen during the tutorial to a player who don't know the /unstuck command.

Maybe there is a way to detect the user is stuck and show him a tutorial ?

**Comment by StanKryvenko** [comment]
Fixed in SVN

**Comment by SlayksWood** [comment]
Still an issue. have workbench, and want to place starter camp like this:
![unknown](https://user-images.githubusercontent.com/45708377/90004043-a8e86480-dc9d-11ea-9e80-e0d1753e91fc.png)
i stuck in tent:
![unknown (1)](https://user-images.githubusercontent.com/45708377/90004116-c74e6000-dc9d-11ea-903d-8eebae1908b5.png)

**Comment by mirasrael** [comment]
@MazonDel probably we can use Depentrate code right after placement.

**Comment by WeaselDog** [comment]
Here is how to reproduce it without the workbench. Place campsite so you are standing near where the bed will be.
![StuckCampsite](https://user-images.githubusercontent.com/47330823/90094548-14a0f080-dce3-11ea-9ab3-834abde6a78f.png)
