### ISSUE TITLE
Vehicles/Tools noises on map

### ISSUE THREAD

**Issue by dezorro** [StrangeLoopGames/EcoIssues#17772]
was walking along one the map and started hearing a steam truck go another guy to come over he could hear same noise but in totally different spot about 100m away but no steam truck is near us only one person with a steam truck on our server and he was looking at his steam truck and it was off done a re log noise was in same location still did get a recording of noise.

**Comment by matta22** [comment]
is this 9.0? because we are getting similar issues with powered carts and just normal wooden carts on our 9.0 server aswell.

**Comment by dezorro** [comment]
yes this is 9.0 not sure what caused it but going to see if a server restart fixes it today

**Comment by SlayksWood** [comment]
I had such a problem when I left the game while sitting in the vehicle, and after that the sound would freeze and play separately.
But it really hard to reproduce. 
@Quadbro Can you take a look?

**Comment by SlayksWood** [comment]
And I also have some problem with chainsaw and seems some people have problem with modern rock drill here #17404

**Comment by SlayksWood** [comment]
Step to reproduce for tools:
- first player take chainsaw in active cell on toolbar. 
- second player stay near him
- first player place chainsaw to any storage when it's active on toolbar
- second player still hears chainsaw sound.

**Comment by Quadbro** [comment]
Fixed vehicles and tools with extra stop cases

**Comment by SlayksWood** [comment]
Still an issue for tools. Can't to check good for vehicles:
- first player take chainsaw and select it on toolbar:
![image](https://user-images.githubusercontent.com/45708377/91693332-88f8e200-eb73-11ea-9337-49c05f6e5f93.png)
- first player select another tool or empty cell.
- second player still hears chainsaw.
- first player use another tool
- second player don't hear chainsaw.

**Comment by SlayksWood** [comment]
Tools exactly fixed. Can't reproduce after changes with vehicles. So closed for now.
