### ISSUE TITLE
[civics-rebase-2] Civics Issues

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18557]
- [x] Capitol UI does not recognize ownership.
![Screenshot_1](https://user-images.githubusercontent.com/24981362/94905030-7f2d0c00-049c-11eb-86c2-547df601f17f.jpg)

- [x] Capitol UI allows manipulation AFTER ratifying a constitution and takes effect.
This also happens when you make a constitution invalid, then fixing conditions it takes effect again immediately.
![Screenshot_11](https://user-images.githubusercontent.com/24981362/94910902-a6d4a200-04a5-11eb-948e-eded2e8bd9df.jpg)

- [x] Invalid Amendments are not displaying invalid state in Amendments table ui
As well as allowing one to enact them while in invalid state.

![Screenshot_12](https://user-images.githubusercontent.com/24981362/94911603-aee11180-04a6-11eb-996c-34ba69d854cc.jpg)
![Screenshot_13](https://user-images.githubusercontent.com/24981362/94911704-d3d58480-04a6-11eb-8ec8-bdd8d7505d32.jpg)

- [x] When adding an item to an election draft it auto pushes it as a "active election" on the website listing; you cant vote on it as it states "draft is invalid" BUT it should not be there at all until its sent to election. 

![Screenshot_15](https://user-images.githubusercontent.com/24981362/94912892-9d990480-04a8-11eb-9a7b-8787ff4c74c7.jpg)
![Screenshot_14](https://user-images.githubusercontent.com/24981362/94912898-9f62c800-04a8-11eb-9d25-fe526973b1ee.jpg)

- [x] Copying the properties from an existing and or revising an existing law will not save its properties and only add a blank draft
but it will add a "Law X Revision object every time you try to copy one.
Each added revision on top of this, when finalizing voting and enact it; it will add each revision cloned onto separate slots on the court as drafts giving me a way to have infinite slots on a court.
 ##
![Screenshot_22](https://user-images.githubusercontent.com/24981362/94924261-7b5db180-04bd-11eb-8915-fed394bd55b9.jpg)
![Screenshot_23](https://user-images.githubusercontent.com/24981362/94924755-66355280-04be-11eb-945d-985920ba6e30.jpg)

- [x]  Start Election button should be in line with other "enable" type buttons, both in color and style it is also offset a bit as well as the image / text interaction shouldn't be this close.
(not sure if this should be a separate UI issue ) 

![Screenshot_25](https://user-images.githubusercontent.com/24981362/94924932-b6acb000-04be-11eb-8070-c1b1107cb94b.jpg)
![Screenshot_24](https://user-images.githubusercontent.com/24981362/94924933-b7dddd00-04be-11eb-861b-127fc12bc7ed.jpg)

https://github.com/StrangeLoopGames/Eco/pull/6875

**Comment by johnkslg** [comment]
Can you add repro steps for getting an invalid amendment to be active?

**Comment by johnkslg** [comment]
Found quite a few bugs unrelated to my changes, but I have fixed all that I found! Great job.

**Comment by IcedForge** [comment]
https://i.gyazo.com/1d00832d0ec0b44d0655504b9d5d4501.mp4
Revision laws are still an issue but i believe this is another type of issue but with simular outcome; any time you copy a law and it makes a revision you can then add another one and another one etc you see the video but for the other ones they seem solid, found a few new ones ill post in another issue to avoid a bigger wall of text.

**Comment by johnkslg** [comment]
I'm not seeing that issue. Going to merge it, try in the next build again?

**Comment by johnkslg** [comment]
Reproed it, fixing

**Comment by IcedForge** [comment]
Closing this and splitting new / repeat issues into separate ones for easier tracking now that its merged into dev build.
