### ISSUE TITLE
[0.9.0.5 br-100] Icons on signs are floating and moving with distance

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#18928]
I noticed this on White Tiger and Coast Redwood - there is something off about icons on signs. First of all, their position shifts based on distance AND they can get out of the frame when you are far away:

![image](https://user-images.githubusercontent.com/964559/97236709-eb044b00-17a2-11eb-8ed0-6b3b77076612.png)

![image](https://user-images.githubusercontent.com/964559/97236718-efc8ff00-17a2-11eb-8c6a-633e326d8854.png)

Secondly, even up-close, they aren't very centred:

![image](https://user-images.githubusercontent.com/964559/97236805-269f1500-17a3-11eb-85e5-bbaa87cffef8.png)

So I'm guessing there is some weird logic there when it comes to displaying those icons.

Also also, since some people are using those icons for their stores, it might be nice to have some high-rez icons available, perhaps as a default :) .

**Comment by SlayksWood** [comment]
need CurveShader

**Comment by SlayksWood** [comment]
@ThePiachu 
![image](https://user-images.githubusercontent.com/45708377/97270119-ac709e00-183f-11eb-95a4-adbc517a9c0c.png)
Don't have problem with center. Can you provide your text from table?

**Comment by ThePiachu** [comment]
Those aren't my signs. The floating ones are from White Tiger, somewhere around town centre, and the other one is from Coast Redwood, from thomasfn's store.

**Comment by ThePiachu** [comment]
Hmm, might be fixed in 0.9.1.1, haven't seen the error appear recently...

**Comment by serpopov** [comment]
Fixed in develop

**Comment by SlayksWood** [comment]
Still have issue, but I checked it in another issue #17527. So merged it to this one.
