### ISSUE TITLE
Steam linking resets all user icons

### ISSUE THREAD

**Issue by denysaw** [StrangeLoopGames/EcoIssues#19436]
User "184667" bought Dev-Tier and had Dev-Tier icon.
After linking with steam, Dev-Tier icon is gone and all he has is betaicon
He should have betaicon, betafourpackicon and devtier

**Comment by denysaw** [comment]
Done. Staging + Prod updated.

**Comment by D3nnis3n** [comment]
Unfortunately not fixed. Zoneman just registered and linked Steam, didnt get icon.
