### ISSUE TITLE
No mails being sent to adresses that contain "+"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#19543]
The welcome mails are not sent to users that have a + in their e-mail like "test+test@gmail.com", "test@gmail.com" is working.

**Comment by denysaw** [comment]
Done. Could be tested on Stagingland

**Comment by SlayksWood** [comment]
I can't find any resource which lets create mail with '+' in name, but I tried to test it with malinator and I didn't have any message

**Comment by SlayksWood** [comment]
So I read about mail that contain "+" more. And There is still a problem that I don't have all mails - for example 'Eco Wolf Whisperer' and 'Welcome to Eco - How To Start Playing'

**Comment by denysaw** [comment]
@SlayksWood Again... Could we, please, close this issue as it was about emails with + and probably has higher priority and open another one with the exact cases when emails are not sent or `'Eco Wolf Whisperer' and 'Welcome to Eco - How To Start Playing'` are the only 2 ones? Thank you.

**Comment by SlayksWood** [comment]
I don't have any messages now.
