### ISSUE TITLE
[0.9.2.0 beta staging-1891] All plot auth has reset to owner only - Migration

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19903]
All authorised "who can access" has been reset it seems, attached migration.log just incase (i did NOT migrate the DB as it is almost 6GB so just game.eco if that is the cause?)

[migrations.log](https://github.com/StrangeLoopGames/EcoIssues/files/5765674/migrations.log)

![image](https://user-images.githubusercontent.com/61889138/103555576-658ace80-4ea8-11eb-9c01-a8f97dcc2d2e.png)

![image](https://user-images.githubusercontent.com/61889138/103555985-ff527b80-4ea8-11eb-8cd2-f00b9b52c877.png)

**Comment by gzatravkin** [comment]
fixed by https://github.com/StrangeLoopGames/Eco/pull/7532

**Comment by IcedForge** [comment]
This is still an issue in staging 1897, 
Created a new world in 9.1.9
Added a 4 large areas in the same plot tried adding both users, elected titles, registrar title and demographics as authorized and as plot owners
Migrated save into 0.9.2.0/1897
Red square is player owned and were assigned plot markers
none of these different sections contained any authorized items
![Screenshot_23.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/c3882976-29e4-4d3e-847a-148c688f619c)

**Comment by gzatravkin** [comment]
Can you attach a save of your migrating world?

**Comment by gzatravkin** [comment]
Actually this is not continious deeds problem, all deeds had broken migrations for auth.

Fixed it here https://github.com/StrangeLoopGames/Eco/pull/7552

**Comment by johnkslg** [comment]
stellar bug 💎
