### ISSUE TITLE
[CLIENT] 9.1.9 b-release 136 - Random Unity crashes

### ISSUE THREAD

**Issue by Palamicoto** [StrangeLoopGames/EcoIssues#19967]
Hi,

I got random crashes with my game, it seems that a little window appears with a loading bar when it crash and it also seems that it is a write memory error.
I know I'm not giving any useful information, but I don't know where to search for a crash report or anything that could help you investigate this bug.
Can you tell me what do you need to investigate ?

OS : Windows 10 64 bits
Proc : AMD Ryzen 5 2600x Six-Core 3.60 GHz
Graphic Card : NVIDIA GeForce RTX 2070 (Drivers up to date from yesterday)
RAM : 16 Go

Thank you.

**Comment by maphrea** [comment]
OS : Windows 10 64 Bit
Processor : Intel(R) Core (TM) i9-9900K CPU @ 3.60GHz
Graphics Card : (EVGA) NVIDIA GeForce RTX 2080 Ti
              -Note: Graphics Card drivers updated before CTD's occured, and I updated and clean installed                      them again after, issue still persists.
Ram : 32.0 GB
Eco Update Version:9.1.9
                      -Note: Originated in 9.1.9, but I could get 8.3.3 to work, anything after 9.0.0 the issue returns.
Player.Log : [https://pastebin.com/iFxQJrhB](url)
        -Note: Player.log not saving in "/StrangeLoopGames/Eco/Crashes" file like states in the log, instead it saves to "/StrangeLoopGames/Eco", Crashes folder does exist, It's just empty.
Server.Log : Not Included as EcoServer.exe appears to run normally on its own

I first experienced the same issue on 1/10/2021 at around 1230am (EST). Whenever I go to launch the game, the black loading screen with a tree on it pops up, as well as a blank smaller window, with a loading bar that has the Eco Icon on it. When the loading bar reaches 1/4'th to half way, the game immediately CTD's. 

I've verified the games files; Uninstalled the game, and reinstalled it; Uninstalled, shutdown the computer, reinstalled; and updated the majority of my drivers. From what I can tell it's only a client issue, as when I run the Ecoserver.exe I can get a server up and running, no errors pop up or anything. I also haven't messed around with any mods or additional content with this game.

Personal Note; You guy's have done a great job with this game, it usually runs smoothly, and usually a nice relaxing way to end a evening after work. Thank you.

**Comment by IcedForge** [comment]
Thank you both for reporting.
Could you provide full hardware spec and dxdiagnostics?
You can get this via windows key+R, then type in Dxdiag and hit enter
and what power supply as well.

@maphrea Not sure i understood you correctly
But did you run any previous 9.x version correctly? or is this issue consistent in all of the 9.x versions? Or just latest 9.1.9?

**Comment by Palamicoto** [comment]
I tried a lot of fix, one seemed to work.

I explain, I've looked for EVERY drivers not up to date, not only the graphic card driver.
I had some of them very outdated (from 2005), I updated them (got one on my hard drive) and since I've experienced no crash.

Don't know if it is the same problem than maphrea, but updating every drivers worked for me.

**Comment by maphrea** [comment]
@IcedForge I ran versions 8.3.3 (the only version working for me.), 9.0.0, 9.1.7, 9.1.8, and 9.1.9 .
I only completely uninstalled the game and reinstalled it for versions 9.1.8, and 9.1.9 .  With 8.3.3, 9.0.0, and 9.1.7, I just used the steam beta's options, and verified the game files. 

Dxdiag - https://pastebin.com/y9kA8bj7
Power Supply - (Thermaltake) Toughpower Grand RBG 1200W; Toughpower Grand Series
 Part Number - PG1200F1FAP
--Note; I'm not 100% certain if that's all the information you need on the power supply, but that's whats written on the sides of the power supply.

**Comment by IcedForge** [comment]
@maphrea 
You can try disabling any nvidia audio devices ( or any that you are aware that you are not using )
by using win key, "manage sound devices", click on nvidia ones and disable

**Comment by maphrea** [comment]
Not noticing too much of a difference, the game still crashes, but the loading screen with the tree stays about 1 or 2 seconds longer before the crash.
The player.log seems to have remained the same as before from a quick skim through, but here it is anyway.
https://pastebin.com/Puz0WNyD

**Comment by IcedForge** [comment]
Sorry for the long delay, had some luck with another Nvidea user where the issue was resolved after updating their Gcard drivers to the latest game ready drivers released at 1/07/2021, can you check for any updates and test again after that is done?

**Comment by maphrea** [comment]
All good as far as the delay, I attempted to update my BIOS a couple days back and something happened to interrupt the process. Long story short, I've not had my computer the last couple days anyway. It's back and working fine now, but the Nvidea update you mentioned  (1/07/2021) is the current version of Nvidea that I'm running. The game still doesn't make it past the loading screen. I would like to mention that Eco doesn't show up in the Nvidea Geforce Experience Games panel, I may be mixing it up with steam, but I believe that Eco used to be included in the list as well.

**Comment by IcedForge** [comment]
Reason why i was mentioning the graphic update is because last dxdiag log you posted your graphics drivers were these
  Driver Date/Size: 12/30/2020 7:00:00 PM, 1049800 bytes
  
Could you post a new dxdiag if you have updated drivers in general since then?
As this issue seemed to have resolved for other nvidea cards users i am trying to figure out if there is something explicit from nvideas side that is causing confligt with the Wwise sound system on specific card ranges

**Comment by IcedForge** [comment]
@Palamicoto Could you be a super help and post your dxdiag file here as well 
windows key + R, type in Dxdiag ( at the bottom you have an option to save all to file or something like this ) and upload this here or send to to my mail if you dont want it public at Jens@strangeloopgames.com

**Comment by maphrea** [comment]
@IceForge; Strange, I just ran another Dxdiag, and it does say that that's the date the driver's were last updated, however NVIDIA is reporting the 01/07/2021 versions is installed (461.09)... I'll attempt to re-install the driver and see if that works. I should also note I experienced a different issue in a game called ARK, not certain if it could be related, but I previously messed with NVIDIA's PhysX settings. Regardless, i fixed the issue with ark by resetting the settings to the default, but the issue with Eco still stands.

**Comment by Palamicoto** [comment]
Solved with up to date Hard Drive driver.

**Comment by maphrea** [comment]
I managed to update my Samsung SSD 970 EVO plus 500GB driver, however the second driver on my computer doesn't seem to have an update; its a WD Black (WDC WD2003FZEX-00SRLA0). The game still crashes during startup. If at possible, could you provide some information on how to update the driver.
