### ISSUE TITLE
[0.9.2 staging-1906] World index in Ecopedia lost icons in localizations.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20092]
Steps to reproduce:
- set non-English language (I used Gibberish)
- open Ecopedia -> World index:
![image](https://user-images.githubusercontent.com/45708377/105142300-7e7fba80-5b0b-11eb-959a-b9f40c1b9218.png)

**Comment by gabrielgindridev** [comment]
![image](https://user-images.githubusercontent.com/65634950/108226536-c2baa680-711b-11eb-9033-cc59a173f32a.png)
seem like it was fixed

**Comment by SlayksWood** [comment]
Hm still an issue in staging-1937:
![image](https://user-images.githubusercontent.com/45708377/108811355-2f232300-75be-11eb-8cda-4dda7bdf6bbf.png)
```
[09:03:47.817] Ecopedia: Missing following icons: [Citizens] , [Civic Articles] , [Election Processes] , [Laws] , [Titles] , [Districts] , [Demographics] , [Tags] , [Statistics] , [Bank Accounts] , [Currencies] , [Work Orders] , [Work Parties] , [Settlements]
EcoEngine.Logging.LogManager:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
EcopediaManager:CheckForMissingItems()
Player:ReceiveInitialState(BSONObject)
TooltipHandler:Invoke(TooltipUI)
NetObjComponent:OnReceiveInitialState(BSONObject)
NetObjComponent:Eco.Shared.Networking.INetObject.ReceiveInitialState(BSONObject)
Eco.Shared.Networking.NetObjectManager:HandleNewObject(BSONObject)
ClientPacketQueueHandler:ProcessPhases(TimeLimit)
ClientPacketHandler:HandleNetworkEvents(TimeLimit)
System.Action`1:Invoke(T)
FramePlanner.PlannerGroup:OnUpdate()
FramePlanner.FramePlannerSystem:OnUpdate()
Unity.Entities.ComponentSystem:Update()
Unity.Entities.ComponentSystemGroup:UpdateAllSystems()
Unity.Entities.ComponentSystem:Update()
HighlightingSystem.OnEndOfFrame:Invoke()
```

**Comment by gabrielgindridev** [comment]
The latest `develop` is working. I'm not sure why this is happening, maybe it is only breaking in the build?

Gibberish:
![image](https://user-images.githubusercontent.com/65634950/111514799-d6642780-8730-11eb-8be8-da73cef17054.png)

Русский:
![image](https://user-images.githubusercontent.com/65634950/111514985-09a6b680-8731-11eb-9947-2b65bb863315.png)

**Comment by TwixterZ** [comment]
tested on 9.4 develop 250 and working as intended

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/6dabd95c-aa39-4c0d-9fd6-115b614b5103)
