### ISSUE TITLE
House bonus stacks wrong when multiple (+4) residents living in the same house

### ISSUE THREAD

**Issue by Seekersdk** [StrangeLoopGames/EcoIssues#20296]
Something goes very wrong when 4+ ppl live and share the same house.
Eg, the frist bedroom gets the 100%
2nd gets 200%
3rd gets 400%
4th get 800%
etc

How to produce the bug:
1. Build house
2. Make 4 bedrooms with beds
3. Get 4 ppl to move in
4. Then you have the issue
5. Then make 4 toilets, WCs, kitchens
6. If you are more ppl, you just make more rooms ofc. and the bug goes crazy

Its stack like crazy the more ppl who move in. You have to be 4 persons or more for the bug to kick in

Confirmed the bug on Whitetiger as well, to rule out my own server. Feel free to check my house out on Whitetiger (1073,373).

Some players on my server managed to get minus 1 million XP, draining their XP bar right away. 
![bug1](https://user-images.githubusercontent.com/78330843/106407581-b4db0500-643c-11eb-8720-291a85159a32.png)
![bug2](https://user-images.githubusercontent.com/78330843/106407583-b5739b80-643c-11eb-9a3a-b720dbdf9f0b.png)

**Comment by SevenAngels** [comment]
Can confirm, this is also happening with a group of 5 people on my server. Hitting the soft cap on a room causes extreme negative xp gain. 

Going from 5 residents to 6 residents causes house value to jump from 83.26 to 242.2.

5 residents:
![image](https://user-images.githubusercontent.com/15224019/106413681-5435d300-6410-11eb-8e4d-3f13cf97a485.png)

6 residents (no change in furniture):
![image](https://user-images.githubusercontent.com/15224019/106413773-90693380-6410-11eb-85af-d10ec028b517.png)

**Comment by danisani1** [comment]
I think this guy in discord got it pretty right: 
![image](https://user-images.githubusercontent.com/58810286/106452093-b67dea80-6487-11eb-9865-cabba1908221.png)

**Comment by talonos2** [comment]
We did some experimentation and realize that the value of each piece of furniture is ((1-D)/(1-T))N, where D is the listed diminishing return value, T is the "penalty" for having multiple occupants, and N is the number of previous pieces of furniture in that category. So for the third hewn chair in a given room in a three person house, we're getting ((1-0.3)/.5)2, or 1.42. I've tested this: 10 hewn chairs gives a ridiculously high value, as per the formula.

But it gets worse: Rooms follow the same pattern, just with a D locked to 0.5. This means with three people (a 50% reduction) there is no diminishing returns on rooms, and if you can get a housing penalty "worse" than a 50% reduction, each room is worth more than the one before it, scaling exponentially off into infinity.

It seems something's going wonky with the material soft cap, too. Not sure what. Normally, the second full multiple of the soft cap is worth half the first, the third is worth half the second, etc. So, for instance, 10 worth of furniture in a tier 1 room is normally worth 7.5, 15 worth of furniture is worth 8.75, etc.

It no longer works like that if you have multiple people on the same deed. With three people (a 50% reduction) 5 worth of furniture gives the full 5, 10 worth of furniture gives zero, and then the value of the room starts going negative: 15 worth of furniture gives you -10, and it starts exploding exponentially into negative infinity after that.

**Comment by WeaselDog** [comment]
This is fixed in 0.9.2.4

**Comment by SlayksWood** [comment]
release-156 still an issue for me. A little different, but the problem is there and now starts with the addition of 2 residents. It gives correct penalties tight now, but will broke Room calculation.
Step to reproduce:
I build a Hosue with 4 Bedrooms, 1 Kitchen, 1 Bathroom and 2 General Rooms.
- 1 resident in House. Room calculation is properly, penalties for repeating room is right.
![image](https://user-images.githubusercontent.com/45708377/106852796-b3723c80-66c9-11eb-80d6-dcbfefbf0fa9.png)
- 2 residents in house. Room calculation is broken now. Second bedroom and second general give me 100% expirience instead of 50%, 3 Bedroom give 50% instead of 25% and 4 bedroom give 25% instead of 12,5%
![image](https://user-images.githubusercontent.com/45708377/106852741-9ccbe580-66c9-11eb-976a-0b850b9c3cbe.png)
![image](https://user-images.githubusercontent.com/45708377/106853115-3d220a00-66ca-11eb-952e-d1236bd47325.png)
Calculate it: 15,94 (Kitchen) + 15,01 (1st Bedroom) + 14,35 (2nd Bedroom) + 7,11 (3rd Bedroom) + 3,42 (4th Bedroom) + 13,63 (1st General) + 11,33 (2nd General) + 12,71 (Bathroom) = 93,5. So room calculation broken, but currently I have penalties for 2 redident because I get 93,5*0,9 = 84,15 Exp:
![image](https://user-images.githubusercontent.com/45708377/106853568-fb459380-66ca-11eb-9d8c-1cae08a59542.png)

- 3 redidents and I have less Exp (because I have 50% penalty by residents) but House will give me more EXP. Now 3rd Bedroom wiil give 100% value, 4th Bedroom - 50%:
![image](https://user-images.githubusercontent.com/45708377/106853803-55465900-66cb-11eb-873d-4e4c8fe17f30.png)

and etc.

**Comment by SlayksWood** [comment]
And I guess it was broken here too (haven't tested it yet) #20353

**Comment by talonos2** [comment]
Seems intentional.

Look at it this way: With one resident, you get one "free" room and the rest decreasing exponentially after that, you asymptotically approach 2x the points of your best room.

With three residents, you get three "free" rooms and then the rest decrease exponentially. In this case, you asymptotically approach 4x the points of your best room. But this is divided in half because of the residency penalty, leaving you at 2x the points of your best room, same as with a single person.

I think this feature is working as intended. One is the same, two has a better asymptotic cap than one, three has the same asymptotic cap, and beyond that overcrowding takes place and the cap gets worse. Also it's now impossible to get exponential "runaway" XP like that 200,000 point house I had a few hours ago before the patch. I am satisfied with these new formulas, so far as I understand them.

**Comment by gzatravkin** [comment]
Yes, the change to give for each new resident one free of penalty room is intentional. The issue was critical because of allowing near infinity skill points. So if it don't happens anymore I would close the issue and maybe create new one for balancing (the final formula is still in discussion) @SlayksWood

**Comment by talonos2** [comment]
`the final formula is still in discussion`

Thanks for the heads up; I'll avoid updating the wiki page for a while. ;)

**Comment by talonos2** [comment]
Spreadsheet stuff: I'm sure the devs are aware of this, but this is so the others watching this thread are aware:

If you want to maximize how much XP you, personally, receive, form a two-person house. (Or, not pictured, a 270+ person house with 270+ rooms) Either of these will let you break past the "asymptotic cap" of 200% that was present in previous versions.

![image](https://user-images.githubusercontent.com/3359830/106934756-bd9b3780-66d7-11eb-9a5c-dcd8034ccc74.png)

If you want to maximize how much XP the entire group receives, be in a three person house or a 150+ person house:

![image](https://user-images.githubusercontent.com/3359830/106936792-3dc29c80-66da-11eb-93b5-9ab4cd5439f6.png)

**Comment by TwixterZ** [comment]
Issue re-emerged as of 9.4 Staging 2022 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/82028efe-68fe-4580-a8e4-2d412e60d711)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2040.

Tested via commands.
Closing as fixed.

![image](https://user-images.githubusercontent.com/77248866/123971001-3c2ca480-d9ec-11eb-90a0-f6cb4afb681c.png)
