### ISSUE TITLE
Plow Field Contract don't give right to Contractor

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20374]
Step to reproduce:
- first player create a plow contract:
![image](https://user-images.githubusercontent.com/45708377/107032026-2eb81900-67c4-11eb-99c6-10878b057235.png)
- second player take it. Contractor doesn't have authorization rights to hoe:
![image](https://user-images.githubusercontent.com/45708377/107031333-10055280-67c3-11eb-83e0-f29d540085ef.png)

_Originally posted by @SlayksWood in https://github.com/StrangeLoopGames/EcoIssues/issues/19803#issuecomment-773991664_

**Comment by serpopov** [comment]
I think it is fixed in develop

**Comment by SlayksWood** [comment]
Still an issue in 0.9.3 staging (develop-180)

**Comment by SlayksWood** [comment]
Still an issue in staging-1930:
![image](https://user-images.githubusercontent.com/45708377/107918098-1ab9a780-6f7a-11eb-9dbe-1bbeea3e71fc.png)
