### ISSUE TITLE
"Target inventory only accepts fuel" When trying to sell to a store

### ISSUE THREAD

**Issue by otting** [StrangeLoopGames/EcoIssues#20375]
As the title says the message "Target inventory only accepts fuel" appears when their stock is otherwise full, I suspect that it tries to putt the things into a brasier or something.

I was trying to sell Sandstone only

![image](https://user-images.githubusercontent.com/5678451/107038468-dc272e80-67bc-11eb-966f-6d2fc7144bef.png)

**Comment by SlayksWood** [comment]
The problem here is pretty simple. A store owner just has no room in storages. But usually the buyer sees this notification:
![image](https://user-images.githubusercontent.com/45708377/107183227-72429b00-69ef-11eb-9883-9fecea68e46d.png)
But we don't have this feature #8977 in game. So a lot of players links their Fuel Inventory to Store (seems we have now bug or not a bug with autolinking Fuel inventory to Store) to make fuel auto-refillable:
![image](https://user-images.githubusercontent.com/45708377/107183801-791ddd80-69f0-11eb-9dd0-6d03aa144d87.png)
So when another player will try to sold basalt now, he will see this notification:
![image](https://user-images.githubusercontent.com/45708377/107183844-905ccb00-69f0-11eb-894c-04c74ceb3647.png)
But he must see something like that:
"The store owner has no room for this type of resource."
This problem is becoming more and more urgent, because we have more and more unique Storages, like Silo.

**Comment by TwixterZ** [comment]
Issue tested on 9.4 Develop 259, currently instead of showing any error message, items sold to store is put into fuel supply storage instead allowing such storage to accept items that is not fuel.

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/b4f25da0-a1cd-4cb3-8000-7c04e6672271)

**Comment by tomsseisums** [comment]
Could not reproduce the problem with items being put into wrong storage. Possibly got fixed with the latest staging to develop merge on 21st of April.

What I found instead is that other changes have broken the updated messages.

**Comment by serpopov** [comment]
Arrow is fuel so it is possible to place them in fuel slot

**Comment by TwixterZ** [comment]
Re-test done on this issue on 9.4 Develop 287, error message still showing "Inventory only accepts fuel" instead of expected behavior.

Expected behavior : Error message stating "**Storage is Full**" or "**Store owner has no room for this type of resource.**"

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/bd78f351-b02b-4458-b7fe-56e10d547316)

**Comment by SlayksWood** [comment]
Still have the issue. I have message that:
![image](https://user-images.githubusercontent.com/45708377/118478833-00c66700-b719-11eb-8b45-6524d3df7705.png)
Step to reproduce:
- first player create a stores with linked campfire full suply:
![image](https://user-images.githubusercontent.com/45708377/118486993-ee512b00-b722-11eb-8c90-d0c65f812838.png)
- add acorn to purchace list.
- second player try to sell acron to this shop.

**Comment by serpopov** [comment]
This will be fixed in https://github.com/StrangeLoopGames/EcoIssues/issues/17631 with different solution: campfires, torch stands etc won't be linked to store

**Comment by tomsseisums** [comment]
And autolinking should have been fixed here: https://github.com/StrangeLoopGames/Eco/pull/8262

**Comment by WeaselDog** [comment]
Thank you for reporting this. We will keep this issue open as we may want to clarify the error message in the future.

There was an incorrect behavior happening where stores were linking to fuel slots, causing people to see this error message very often. This error message should only be displayed when someone has manually linked a fuel slot to their store, and usually when someone does this they will be buying fuel.
