### ISSUE TITLE
[0.9.2.4 beta release-156] Strange title error in law

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#20865]
This is a really odd one that I think may have inevitably caused when making updates to titles, districts and a law that was referencing them but I'm honestly not sure. In short, the game is complaining about an error in a law that a removed title has been selected, even though the actuality selected title is in fact not one that has been removed, as seen in the below screenshot.
Even if I go to revise the law, clear the title and select the same one again the same error will still appear.
It also only errors on the first time the title is referenced and not on any of the other times in other sections.
![Eco_2021-03-09_14-13-12](https://user-images.githubusercontent.com/10183015/110415664-5b728f80-80e6-11eb-8d3e-a0895dd1a1f0.jpg)

A possible link to this is how when I made a revision to the Minister for Public Works title, I forgot to also revise the Road Workers title which makes a reference to it thus leading to its own error as seen below.
![Eco_2021-03-09_14-50-03](https://user-images.githubusercontent.com/10183015/110415834-befcbd00-80e6-11eb-846d-686bda4cb4c1.jpg)

However as can be seen it also lists a number of other errors that seem to make no sense as they are all pointing to a law where the title is used. The above image is when simply viewing the title without editing, though when I click to revise the title and check the errors I get a much more reasonable set of errors that makes sense.

![Eco_2021-03-09_14-52-27](https://user-images.githubusercontent.com/10183015/110416205-611ca500-80e7-11eb-9b83-342f304f4f37.jpg)

If the initial error in the does carry through to any laws it is referenced in and invalidates them, then why when looking at the law does it only error on the first mention of the title and not any of the others, and the error message also doesn't make sense? I feel like there is a bug somewhere here but I'm very confused trying to work out what the game is thinking/trying to do that I'm honestly not sure.

Also my other issue #20864 may be related as it occured at the same time.

**Comment by Dave247** [comment]
It doesn't seem I'm even able to start an election to update the Road Workers title in order to fix the error, as when I try to I get a warning about the error that I am trying to fix.
![image](https://user-images.githubusercontent.com/10183015/110418154-1bfa7200-80eb-11eb-9bfa-598803cad24d.png)

**Comment by IcedForge** [comment]
Thank you for reporting. If you edit out the entry as shown below it should fix this, is it not allowing you to change this?

![Screenshot_1](https://user-images.githubusercontent.com/24981362/110763113-d2786700-8251-11eb-837c-20afe0d10574.jpg)

**Comment by Dave247** [comment]
The thing is I did edit that to be the current (not removed) title, and if I add that by itself to an election to update it I still get a error which had me confused, as either something is very mixed up or completely broken.

**Comment by Dave247** [comment]
I have uploaded the server's save file in another ticket, which can also be used here as both issues occured at the same time.
https://github.com/StrangeLoopGames/EcoIssues/issues/20864#issuecomment-798869641

**Comment by Dave247** [comment]
Coming back to this again having experienced it a second time after a new wipe/cycle, I think what the actual problem is that the title's references were not properly updated when they should of been which has caused all manner of issues and things to break as a result. After playing around a bit in a offline world and not being able to reproduce it, I suspect that it might be getting caused by another issue that is mentioned in #20311 , which itself is also part of an even larger issue that is already being looked into.

**Comment by IcedForge** [comment]
Are you still running into this after 9.3 ?

**Comment by Dave247** [comment]
> Are you still running into this after 9.3 ?

It hasn't happened yet, though we are only a week into a new server that is currently running 9.3.3 and as I think it was a specific set of circumstances that triggered it in the first place, it all depends if I can manage to make it happen again.

I have encountered another bug though in our current world, where after a large government restructuring bill the existing titles are marked as being invalid, despite when checking the details in the government office it doesn't show any errors. I have no idea what to make of it though as everything still sees to work as intended, and I'm not sure I want to risk putting it through another election unnecessarily just to see if it will fix anything when it could break it even further.

Both issues first occurred at the end of an election when the game was updating all of the refences, so I figure whatever bad thing happened was during that process.

**Comment by TwixterZ** [comment]
Apologies for late respond, @Dave247 Have you raised a new ticket detailing that issue?

**Comment by Dave247** [comment]
> Apologies for late respond, @Dave247 Have you raised a new ticket detailing that issue?

Ah no sorry, from memory we managed to avoid it happening in the previously mention iteration, and as we decided not to start up a new cycle until 9.4 comes out due to the changes it will bring and didn't want to get stuck on the old version.

Hopefully the changes in 9.3 fixed it, though as I don't have anything else to add I think it's safe to close this ticket, though if I do notice it happen again in 9.4 then I'll make sure to capture the server save file and open a new ticket for it.
