### ISSUE TITLE
[0.9.3 staging-1961] Using camera zoom (alt+mouse wheel) should prevent mouse wheel controls in vehicles

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21049]
Step to reproduce:
- spawn Skid Steer.
- drive it
- use Alt+Mouse Wheel to zoom in/out camera, the Arm is also moving. Should only camera zoom in/out.

**Comment by StanKryvenko** [comment]
Fixed in SVN

**Comment by SlayksWood** [comment]
Tested on 0.9.3 staging-1969, Still an issue for both Excavator and Skid Steer.
https://drive.google.com/file/d/1eTHQDnoW6OlcI8pwUEkpx6-IYZs7mihc/view?usp=sharing

**Comment by SlayksWood** [comment]
need to check in staging-1970 or later

**Comment by Daniel-Magulado** [comment]
Reopening.

Tested on 0.9.3 Release-190.
The issue is still reproducible with the Crane vehicle.

https://user-images.githubusercontent.com/77248866/114699730-3f03eb80-9d53-11eb-8d84-a16d3f886c6c.mp4

Various mouse-related issues can also be observed with the Crane vehicle.
#12024
https://github.com/StrangeLoopGames/Eco/issues/7974

**Comment by SlayksWood** [comment]
0.9.4 develop-277 Fixed for crane, but still an issue with Excavator and Skid Steer.

**Comment by StanKryvenko** [comment]
I think there's an issue with SVN, because all mentioned changes was there about 2 weeks ago

**Comment by StanKryvenko** [comment]
Fully investigated this issue, no problems found. @SlayksWood plz recheck dev

**Comment by SlayksWood** [comment]
Fixed in 0.9.4 develop-287.
