### ISSUE TITLE
Alpha.6 [2ed68eec] Migration issue: Chests disappear

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2109]
What i did:
- Download new server
- Copyed `Storage` folder from old server folder in new one
- Started new server
- See `Converting world` in logs (takes about 30sec)
- Online

What happend (what we noticed):
- All storage chest disappeared
- "Crafting" tab is empty

**Comment by Conchipedia** [comment]
on vanilla version, nothing changed , added, or copied over, placed workbench and nothing showing to craft
![unknown](https://user-images.githubusercontent.com/29383891/30425470-431f6196-9941-11e7-9b31-d84423b76475.png)
also stone axe (given by learning laboring) doesn;t show as proper icon in toolbar, also couldn't even see it being held in the hand

**Comment by MarjieAVolk** [comment]
Lots of different bugs in here - I just fixed the invisible crafting tab issue.  I'm creating a new issue for the stone axe problem (https://github.com/StrangeLoopGames/EcoIssues/issues/2111)

So this issue is now for the chests disappearing

**Comment by Fank** [comment]
Issue still exists from cc778b68 -> 9e7f9060    
Savegame: ftp://eco.fankserver.com/Game.eco

**Comment by Fank** [comment]
@MarjieAVolk it would nice if you could prioritize this issue because, we and maybe other don't want to update the server because all player will loose stuff.
And i tested the newest version, they are lot of fixed which we want to use :D

**Comment by metachronism** [comment]
@Fank can you please attach a 5.6.1 gamesave (before migration) that reproduces this issue?

**Comment by MarjieAVolk** [comment]
He did, it's at that link: ftp://eco.fankserver.com/Game.eco

**Comment by Fank** [comment]
@metachronism see above its from alpha.6 -> alpha.6
https://github.com/StrangeLoopGames/EcoIssues/issues/2109#issuecomment-329963320
