### ISSUE TITLE
Upgrade to Dev Tier doesn't update amount paid + wrong price

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21181]
User 198585 linked steam to slg, then upgraded to dev tier.
User did not get upgraded amount paid from 30 to 185 dollars, stayed at 30.
Also user had to pay 160 dollars despite 185 dollars - 30 dollars = 155 dollars.

**Comment by Veredior** [comment]
Hello,

one of my friend (slg account 188608) has the same problem. He bought his eco licence on steam and then linked his account to his slg account a month ago.

**Comment by D3nnis3n** [comment]
Hello,
that is a different issue, as your friend didn't get the correct 'amount paid' after linking. The person mentioned here did, it just didnt update on upgrade to dev tier. I will fix your friend manually.

https://github.com/StrangeLoopGames/EcoIssues/issues/21206

**Comment by denysaw** [comment]
Fixed on sandbox and prod.

**Comment by Ry4ndrew** [comment]
@denysaw Retested and can confirm the amount paid is properly set at $155 but it does not automatically update to $185 in the database.

**Comment by D3nnis3n** [comment]
@denysaw Amount paid calculation issue still persisting, confirmed by me as well.

**Comment by denysaw** [comment]
Done. Also hotfixed on Prod.

**Comment by Ry4ndrew** [comment]
Retested and can confirm fix. Thanks.
