### ISSUE TITLE
[9.4 Develop 256] Placed down item did not show up

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21449]
Items did not appear when put down on freshly generated server, including trees. 
Server restart fix this issue. 

Tested with:
- contract board
https://images.zenhubusercontent.com/47210472/d0c96219-e89e-42ca-92e0-e6b902afa820/884be588792c5026ac5410a1e497d55b.mp4
- storage box
- starting campfire
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/74ff885c-1fc7-49cf-b240-fd94dfe4b93e)
- large lumber stockpile
- Using /spawn kitchen 
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/ded64b50-f0ab-4ba3-b4e6-fecc887459d7)
- Using /spawn sawmill
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/29394778-faab-4169-8496-2a361f067453)

**Comment by WeaselDog** [comment]
From @SlayksWood 
> There are places where whatever you place, it is not displayed. This is register on the server, but not visually visible. If you try to place something else there, it will be an error that another object cannot be placed here.
Client restart is not fix this issue, we can't check server restart.

**Comment by tuha263** [comment]
I can't reproduce it after some RconPlugin merge today. Seem it was fixed.

**Comment by SlayksWood** [comment]
@tuha263 Still an issue in 0.9.4 develop-279.
- generate a new world place any world objects in different places. Somewhere they appear, somewhere not.
Issue can be fixed with server restart.

**Comment by tomsseisums** [comment]
This PR seems to also address it: https://github.com/StrangeLoopGames/Eco/pull/8419

**Comment by tomsseisums** [comment]
There was a misunderstanding and our squad took over due to it being critical and no progress being reported, although @mirasrael's PR (https://github.com/StrangeLoopGames/Eco/pull/8419) has been opened for some time already that's addressing the issue, but wasn't linked to the issue.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-286.

Still happening on the said build. On the video below, I've already placed 2 hewn bench that prevents that one I am placing down.

https://user-images.githubusercontent.com/77248866/118423338-61dd4300-b6f7-11eb-9f15-f56b3d1992a0.mp4

Adding video and logs.

My game log is bombarded with
`ArgumentNullException: Value cannot be null.
Parameter name: uriString
  at System.Uri..ctor (System.String uriString) [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.LoginUser (System.String serverUri, System.String accountIdUri, System.String vivoxAccessToken) [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

[Full Game Log](https://drive.google.com/file/d/1nnRNer6Za6PPiFKEr_jBjkQ-7v0Jwkdv/view?usp=sharing)

**Comment by mirasrael** [comment]
This issue fixed long time ago in https://github.com/StrangeLoopGames/Eco/pull/8419

**Comment by TwixterZ** [comment]
Issue tested and confirm still happening as of 9.4 Staging 1986 on some part of the map. 

https://i.gyazo.com/9f91c4ec6e649553f7c00bdbc684da2c.gif

**Comment by TwixterZ** [comment]
Re-tested issue on 9.4 Staging 1987, issue is now fixed

**Comment by mirasrael** [comment]
This issue from comment actually not related to original issue, but fixed it.
