### ISSUE TITLE
Alpha.6 [4c637828] Server gui wrong formating in Reputation -> Display

### ISSUE THREAD

**Issue by Fank** [StrangeLoopGames/EcoIssues#2242]
Everything is in oneline:   
![image](https://user-images.githubusercontent.com/1900106/30807612-f169ea16-a1fa-11e7-94ce-987ee0b7bc89.png)

**Comment by johnkslg** [comment]
Fixed

**Comment by Fank** [comment]
50%:    
D9d6f47c

![image](https://user-images.githubusercontent.com/1900106/30903332-ae9e9c48-a36e-11e7-8356-2e01818ae93c.png)

**Comment by MishkaFur** [comment]
Still exists in 9.1.9 server GUI

![image](https://user-images.githubusercontent.com/61889138/104933972-7b68bb00-59a1-11eb-9d8e-9620b9ea0308.png)
