### ISSUE TITLE
Game has crushed recently few time in few minutes

### ISSUE THREAD

**Issue by VolodymyrB** [StrangeLoopGames/EcoIssues#22539]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7009960/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7009969/Player.log)

**Comment by VolodymyrB** [comment]
And again
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7009980/Player.log)

**Comment by TwixterZ** [comment]
Hi @VolodymyrB thank you for reaching out to us and apologies this happens to you.

can you help to provide a bit more information?
- Were you playing in white tiger server when this happens, or is this happening on private game?
- if on private game, is there any mod used?

**Comment by VolodymyrB** [comment]
Hey, it’s WT

чт, 19 серп. 2021 о 11:31 Khairi ***@***.***> пише:

**Comment by SlayksWood** [comment]
> [Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7027937/Player.log)
> [Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7027938/Player-prev.log)
> 
> Since the update crashing before and after accessing my dedicated server.

**Comment by SlayksWood** [comment]
@VolodymyrB @SybilGlendevon Thank you for the report. I had a similar problem, but it was solved by updating the video drivers. Can you update your ones and then report the results?

**Comment by VolodymyrB** [comment]
The game is still crashing after the video drivers update.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7038725/Player.log)

**Comment by VolodymyrB** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7038750/Player.log)

**Comment by VolodymyrB** [comment]
The game is only crushing when I'm riding the Steam truck

**Comment by Kodvik** [comment]
> @Kodvik thank you for that information, just checking here, does playing on windows mode works for you?

I was able to drive around for a bit with it (a lot longer than in borderless window)... but it just crashed right now (it took something around 10 minutes to crash and in dedicated fullscreen I've played for hours and didn't get one single crash [while driving a lot... which seems to be the main issue])

here are some info about my hardware if it would help: I5 7400 at 3000GHz... GTX 1060 6Gb... 16 GB DDR4 and using a SU800 as SSD with the game and OS in it

the game graphical options I'm using are:

![20210827200042_1](https://user-images.githubusercontent.com/89546553/131196547-cd804720-df4b-485f-a71a-1b04883a8b1a.jpg)

let me know if you want me to keep testing it with window or borderless window mode to help with more info

**Comment by TheRisenPhoenix** [comment]
A friend of mine experiences the same problem, the game crashes at irregular intervals. I looked into the logs and the error is always the same, the function CreateDirect3D11SurfaceFromDXGISurface from d3d11 reports trying to access an invalid address. System running on latest Win10 and Nvidia (GTX 1070) drivers. 
I read in reports of other games that this might be related to a bug in Unity?

**Comment by TwixterZ** [comment]
@TheRisenPhoenix thank you for this information, I have notified our developer with this information, and they are looking whether this is possibility Unity bug

**Comment by TheRisenPhoenix** [comment]
We did some further testing and found that disabling the Steam overlay (and others, such as Geforce overlay or Discord overlay) could help avoid the crash in single player mode. However, when joining multiplayer worlds directly through Steam (so joining a friend), the system now crashes every time you enter the game (when _loading world_ is active). However, when joining a game from within the game (using eco's own server list features), loading does not crash and the game runs without crashing (we only tested it once, but it worked for two hours straight).
This could all be a coincidence (the cause of the crash was still the same, indicating an engine/graphics issue, which confuses me in this context), and we didn't test it often enough to be sure of a correlation, but maybe it has something to do with Unity in combination with Steam. 

I hope this will help you guys narrow down the cause a bit.

**Comment by TheRisenPhoenix** [comment]
Okay nevermind. Overlays do not seem to be the problem. We did some more tries and the game still crashes (and often can only be joined after several attempts), but overall the crashes seem to happen a little less frequent. 
That the game ran without a problem in our try mentioned above seems to have been a coincidence.

**Comment by Darkmift** [comment]
Hi,

I hope this helps,
This is the data from the past 2 days.

Error:game crashing when walking around.
Upon attempt to reconnect...game crashes.

https://drive.google.com/drive/folders/1jBz4JpO2NzP7_mxMWwIL8Z9R8vx2QeyH?usp=sharing

**Comment by D3nnis3n** [comment]
Looks this issue is resolved, hence closing it. Please feel free to open a new issue if the problem reappears.
