### ISSUE TITLE
Consistent Server Crash w/ user login, Unknown reason

### ISSUE THREAD

**Issue by RowanJones** [StrangeLoopGames/EcoIssues#2453]
[327_Server_DumpFolder.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1354039/327_Server_DumpFolder.zip)

Hi There,

Each time we have a user log in, it crashes. Or it seems to crash just because it wants to, lol.

In either case, we cannot have the server open for more than a minute now without it crashing entirely.

We are on the VULTR host with 8GB service of RAM, so it is not the server host issue.

Please also note, we are STILL having the issue with use ImpersatorDecens not being able to join us, this was working for a bit, and has gone to the monkeys again, even with new world wipe. https://github.com/StrangeLoopGames/EcoIssues/issues/2404

Can someone please assist us? 

Thank you,

Rowan

327 Server Discord (where we all live): https://discord.gg/MXdJ87r

**Comment by RowanJones** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2270

**Comment by RowanJones** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2425

**Comment by RowanJones** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2427

**Comment by RowanJones** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2449

**Comment by RowanJones** [comment]
https://github.com/StrangeLoopGames/EcoIssues/issues/2434

**Comment by MarjieAVolk** [comment]
Here's a couple exceptions I saw in the dumps:

This is the most common one, all the latest dumps are this one:
`Exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Error in WoodPulp at 27: The type 'Eco.Mods.TechTree.WoodPulpItem' already contains a definition for 'FriendlyName' (CS0102)
Error in WoodPulp at 28: The type 'Eco.Mods.TechTree.WoodPulpItem' already contains a definition for 'FriendlyNamePlural' (CS0102)
Error in WoodPulp at 29: The type 'Eco.Mods.TechTree.WoodPulpItem' already contains a definition for 'Description' (CS0102)
Error in BakeryOven at 44: The type 'Eco.Mods.TechTree.BakeryOvenObject' already contains a definition for 'FriendlyName' (CS0102)
Error in BakeryOven at 46: The type 'Eco.Mods.TechTree.BakeryOvenObject' already contains a definition for 'fuelTypeList' (CS0102)
Error in BakeryOven at 58: Type 'Eco.Mods.TechTree.BakeryOvenObject' already defines a member called 'Initialize' with the same parameter types (CS0111)
Error in BakeryOven at 66: Type 'Eco.Mods.TechTree.BakeryOvenObject' already defines a member called 'Destroy' with the same parameter types (CS0111)
Error in BakeryOven at 76: The type 'Eco.Mods.TechTree.BakeryOvenItem' already contains a definition for 'FriendlyName' (CS0102)
Error in BakeryOven at 77: The type 'Eco.Mods.TechTree.BakeryOvenItem' already contains a definition for 'Description' (CS0102)
Error in BakeryOven at 79: Type 'Eco.Mods.TechTree.BakeryOvenItem' already defines a member called 'BakeryOvenItem' with the same parameter types (CS0111)
Error in BakeryOven at 89: Type 'Eco.Mods.TechTree.BakeryOvenRecipe' already defines a member called 'BakeryOvenRecipe' with the same parameter types (CS0111)
Error in Bloomery at 40: The type 'Eco.Mods.TechTree.BloomeryObject' already contains a definition for 'FriendlyName' (CS0102)
Error in Bloomery at 42: The type 'Eco.Mods.TechTree.BloomeryObject' already contains a definition for 'fuelTypeList' (CS0102)
Error in Bloomery at 54: Type 'Eco.Mods.TechTree.BloomeryObject' already defines a member called 'Initialize' with the same parameter types (CS0111)
Error in Bloomery at 62: Type 'Eco.Mods.TechTree.BloomeryObject' already defines a member called 'Destroy' with the same parameter types (CS0111)
Error in Bloomery at 72: The type 'Eco.Mods.TechTree.BloomeryItem' already contains a definition for 'FriendlyName' (CS0102)
Error in Bloomery at 73: The type 'Eco.Mods.TechTree.BloomeryItem' already contains a definition for 'Description' (CS0102)
Error in Bloomery at 75: Type 'Eco.Mods.TechTree.BloomeryItem' already defines a member called 'BloomeryItem' with the same parameter types (CS0111)
Error in Bloomery at 85: Type 'Eco.Mods.TechTree.BloomeryRecipe' already defines a member called 'BloomeryRecipe' with the same parameter types (CS0111)
Error in Brazier at 39: The type 'Eco.Mods.TechTree.BrazierObject' already contains a definition for 'FriendlyName' (CS0102)
Error in Brazier at 41: The type 'Eco.Mods.TechTree.BrazierObject' already contains a definition for 'fuelTypeList' (CS0102)
Error in Brazier at 53: Type 'Eco.Mods.TechTree.BrazierObject' already defines a member called 'Initialize' with the same parameter types (CS0111)
Error in Brazier at 61: Type 'Eco.Mods.TechTree.BrazierObject' already defines a member called 'Destroy' with the same parameter types (CS0111)
Error in Brazier at 71: The type 'Eco.Mods.TechTree.BrazierItem' already contains a definition for 'FriendlyName' (CS0102)
Error in Brazier at 72: The type 'Eco.Mods.TechTree.BrazierItem' already contains a definition for 'Description' (CS0102)
Error in Brazier at 74: Type 'Eco.Mods.TechTree.BrazierItem' already defines a member called 'BrazierItem' with the same parameter types (CS0111)
Error in Brazier at 84: Type 'Eco.Mods.TechTree.BrazierRecipe' already defines a member called 'BrazierRecipe' with the same parameter types (CS0111)
Error in Campfire at 40: The type 'Eco.Mods.TechTree.CampfireObject' already contains a definition for 'FriendlyName' (CS0102)
Error in Campfire at 42: The type 'Eco.Mods.TechTree.CampfireObject' already contains a definition for 'fuelTypeList' (CS0102)
Error in Campfire at 54: Type 'Eco.Mods.TechTree.CampfireObject' already defines a member called 'Initialize' with the same parameter types (CS0111)
Error in Campfire at 62: Type 'Eco.Mods.TechTree.CampfireObject' already defines a member called 'Destroy' with the same parameter types (CS0111)
Error in Campfire at 72: The type 'Eco.Mods.TechTree.CampfireItem' already contains a definition for 'FriendlyName' (CS0102)
Error in Campfire at 73: The type 'Eco.Mods.TechTree.CampfireItem' already contains a definition for 'Description' (CS0102)
Error in Campfire at 75: Type 'Eco.Mods.TechTree.CampfireItem' already defines a member called 'CampfireItem' with the same parameter types (CS0111)
Error in Campfire at 85: Type 'Eco.Mods.TechTree.CampfireRecipe' already defines a member called 'CampfireRecipe' with the same parameter types (CS0111)
Error in Kiln at 44: The type 'Eco.Mods.TechTree.KilnObject' already contains a definition for 'FriendlyName' (CS0102)
Error in Kiln at 46: The type 'Eco.Mods.TechTree.KilnObject' already contains a definition for 'fuelTypeList' (CS0102)
Error in Kiln at 58: Type 'Eco.Mods.TechTree.KilnObject' already defines a member called 'Initialize' with the same parameter types (CS0111)
Error in Kiln at 66: Type 'Eco.Mods.TechTree.KilnObject' already defines a member called 'Destroy' with the same parameter types (CS0111)
Error in Kiln at 76: The type 'Eco.Mods.TechTree.KilnItem' already contains a definition for 'FriendlyName' (CS0102)
Error in Kiln at 77: The type 'Eco.Mods.TechTree.KilnItem' already contains a definition for 'Description' (CS0102)
Error in Kiln at 79: Type 'Eco.Mods.TechTree.KilnItem' already defines a member called 'KilnItem' with the same parameter types (CS0111)
Error in Kiln at 89: Type 'Eco.Mods.TechTree.KilnRecipe' already defines a member called 'KilnRecipe' with the same parameter types (CS0111)
Error in StoneBrazier at 38: The type 'Eco.Mods.TechTree.StoneBrazierObject' already contains a definition for 'FriendlyName' (CS0102)
Error in StoneBrazier at 40: The type 'Eco.Mods.TechTree.StoneBrazierObject' already contains a definition for 'fuelTypeList' (CS0102)
Error in StoneBrazier at 52: Type 'Eco.Mods.TechTree.StoneBrazierObject' already defines a member called 'Initialize' with the same parameter types (CS0111)
Error in StoneBrazier at 60: Type 'Eco.Mods.TechTree.StoneBrazierObject' already defines a member called 'Destroy' with the same parameter types (CS0111)
Error in StoneBrazier at 70: The type 'Eco.Mods.TechTree.StoneBrazierItem' already contains a definition for 'FriendlyName' (CS0102)
Error in StoneBrazier at 71: The type 'Eco.Mods.TechTree.StoneBrazierItem' already contains a definition for 'Description' (CS0102)
Error in StoneBrazier at 73: Type 'Eco.Mods.TechTree.StoneBrazierItem' already defines a member called 'StoneBrazierItem' with the same parameter types (CS0111)
Error in StoneBrazier at 83: Type 'Eco.Mods.TechTree.StoneBrazierRecipe' already defines a member called 'StoneBrazierRecipe' with the same parameter types (CS0111)`

`Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StockpileComponent.<>c.<UpdateStockpile>b__9_0(ItemStack stack)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.StockpileComponent.UpdateStockpile()
   at Eco.Gameplay.Components.StockpileComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )`

`Exception
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Eco.Plugins.Networking.ListenServer.Setup(String ip, Int32 port)
   at Eco.Plugins.Networking.NetworkManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)`

`Exception
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Eco.Stats.SimStats.AddStatValue(String[] key, Single val)
   at Eco.Gameplay.Players.User.Tick()
   at Eco.Simulation.Simulation.TickAll()
   at Eco.Gameplay.Players.UserManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)`

`Exception
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Eco.Core.Serialization.DataStore.ProcessQueue()
   at Eco.Core.Serialization.DataStore.<Run>b__26_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by RowanJones** [comment]
Blerp. Well, that's over my head. I'm a padawan, so I just see textwall with one or two things popping out that i can understand. Now i know how captain america feels.

**Comment by MarjieAVolk** [comment]
Just taking dev notes

**Comment by RowanJones** [comment]
AH! ok! do your thing, Master Jedi!

**Comment by MarjieAVolk** [comment]
@craig-jong / @metachronism know what's up with the duplicate definitions of FriendlyName et al?  Are there two copies of autogen in there or something?

**Comment by MarjieAVolk** [comment]
Actually, I think I fixed that add stat value one already, that was the world gen order thing.  So I'll delete that one

**Comment by RowanJones** [comment]
Please also note, we are STILL having the issue with use ImpersatorDecens not being able to join us, this was working for a bit, and has gone to the monkeys again, even with new world wipe. #2404

**Comment by RowanJones** [comment]
![untitled-1](https://user-images.githubusercontent.com/30301814/31160754-09532264-a890-11e7-8203-8183357bd7b7.jpg)

We have not changed a thing, loaded a vanilla world (even though all we did was re-install a vanilla server onto a  vanilla server), and it was working again. But we lost all our progress.

**Comment by RowanJones** [comment]
First crash of the Vanilla re-load:

This happened immediately after i used the /give and the /fly command.

--BEGIN DUMP--
Dump Time
10/03/2017 23:29:36

Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StockpileComponent.<>c.<UpdateStockpile>b__9_0(ItemStack stack)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.StockpileComponent.UpdateStockpile()
   at Eco.Gameplay.Components.StockpileComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StockpileComponent.<>c.<UpdateStockpile>b__9_0(ItemStack stack)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.StockpileComponent.UpdateStockpile()
   at Eco.Gameplay.Components.StockpileComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---


Inner Exception
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StockpileComponent.<>c.<UpdateStockpile>b__9_0(ItemStack stack)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.StockpileComponent.UpdateStockpile()
   at Eco.Gameplay.Components.StockpileComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Eco.Gameplay.Objects.WorldObjectManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Components.StockpileComponent.<>c.<UpdateStockpile>b__9_0(ItemStack stack)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Eco.Gameplay.Components.StockpileComponent.UpdateStockpile()
   at Eco.Gameplay.Components.StockpileComponent.Tick(Single dtime)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Gameplay.Objects.WorldObject.Tick(Single dtime)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---


--END DUMP--

**Comment by metachronism** [comment]
Do you have the gamesave available?

**Comment by RowanJones** [comment]
I do, how does one get large files to you? I zipped it and it told me it was too much. Please advise <3 <3 <3 thanks fam <3

**Comment by MarjieAVolk** [comment]
You can use a file hosting service like Dropbox or Google Drive

**Comment by RowanJones** [comment]
Old world:
https://drive.google.com/open?id=0B3pXs2mr7zR0MmhQeFZNenRkTms

New world crashed for an unknown reason:

![image](https://user-images.githubusercontent.com/30301814/31245834-ce22879a-a9c8-11e7-8fbf-de1635510d31.png)

new world since ticket opened game files and crashes here:

https://drive.google.com/file/d/0B3pXs2mr7zR0YkNUR2NVRWJFWlk/view?usp=sharing

**Comment by RowanJones** [comment]
FYI Our world flooded this morning (thursday) , should be in those files i uploaded, we had to wipe.

**Comment by RowanJones** [comment]
FYI, we canceled our hosting services with Vultr until this gets sorted out, so you won't see the 327th pop up. We just couldn't justify spending the 70$/CAD a month for something that wasn't working.  We're all kind of waiting for news on this ticket before we go forward with hosting a server. :( <3 plz halp devs <3

**Comment by KyeEco** [comment]
Id like to add, i made a 4th server (as we run 3) our first 3 servers have been absolutely fine, no new worlds needed, very minimal crashing, but on the 4th server i left it sit for an hour after being generated, completely new vanilla files and it had flooded the world, the only things in this world where a few stockpiles and a few chests, i had started a new world because of it and joined during the generation (by accident) and had noticed that the CO2 PPM was rising even though i had started a fresh world, so i created a new world again and have left it sit for a few days but the sea level hasn't risen, so i'm not sure how this occurs, Thanks Guys.

**Comment by MarjieAVolk** [comment]
Flooding is a separate issue, so in the interest of sanity I'm going to delete your comments on flooding and paste them in https://github.com/StrangeLoopGames/EcoIssues/issues/2486

**Comment by MarjieAVolk** [comment]
Okay so I loaded both your new save and your old save, and neither one crashed for me, neither on startup nor on login.  At this point I am confused as to what all your issues are, and which save file has which issue(s).  It would be really helpful if you could file separate issues for each problem you have, along with the save file and whatever you know about how to reproduce the problem.

The main ones I'm seeing in the dumps are the thing about the stockpiles, and the WorldObjectManager constructor one (the one in your screenshot).

The stockpile stack trace doesn't seem to match up with the code, so that may have been fixed already, likely in Commit ff65c6bb - "rework inventory <-> stockpile sync, proper locking (#1852)"

The WorldObjectManager one would be happening on startup.  @metachronism I don't think it's the object in WorldObject folder problem, I checked.  So I don't know what the state is on that one, but I didn't see it when I opened the save files.

**Comment by metachronism** [comment]
closing with no repro as this is likely fixed by the stockpile changes, so should be in 6.0.1
