### ISSUE TITLE
Right-Click "Put" not being recognized as a valid option on Dadspeed Server unless you relog several times.

### ISSUE THREAD

**Issue by ECO-ExPLiCiT** [StrangeLoopGames/EcoIssues#24840]
Here are a couple of screenshots with the debug overlay active. The one with the big red X is when the right-click unload isn't working and the one with the big red OK is when the right-click unload is working. Notice the differences I circled and highlighted:

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/33853005/d7f1005d-3ee1-4cf6-b97a-63292ee74c74)

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/33853005/a1e70bfa-aa70-41ac-82af-5615a9c69b46)

**Comment by D3nnis3n** [comment]
This should already be fixed in Update 10.2, please reopen the issue if that is not the case. (You can try the playtest version soon)

**Comment by ECO-ExPLiCiT** [comment]
I request that this be reopened as it is still an issue even after update.

**Comment by D3nnis3n** [comment]
Alright, please provide reproduction steps so we can investigate - we're not able to get this issue.

**Comment by ECO-ExPLiCiT** [comment]
Just log into Dadspeed. While it doesn't happen 100% of the time it still around 90%

**Comment by D3nnis3n** [comment]
Thanks, but to investigate we need to be able to recreate the issue in a local testing environment on Unity - a different server won't do unfortunately.

**Comment by ECO-ExPLiCiT** [comment]
Dad speed is not the only place people have experienced the problem. Manly Mutt found it happened even on White Tiger before but I have no idea how you would "re-create" it without being on a server its already happening on. I think if we could figure out what is causing it on the server we are on we could fix it ourselves.

**Comment by Arend9999999** [comment]
You might wonder why the bigger servers are not willing to post GitHubs anymore....

you can not say things like: (the issue hasn't been reported anywhere else yet and isn't reproducible on official servers either)

this is clearly happening on all servers online
and it is not reported because you ignore people on discord or you just give these kind of answers.
if you got nothing to say Dennis let the actual Development team look at it and just keep your mouth shut

You said this MULTIPLE TIMES... that it doesn't happen on official servers or that there are not bug report... While there are clearly reports and when it clearly happens on your official servers too.

**Comment by D3nnis3n** [comment]
There is no doubt the issue is being **experienced,** it has been brought up to developers and reproduction steps were then requested as **reproduction** was neither possible on official servers nor in a local test environment. Hence any information that can help **reproducing** the issue in a standard environment by developers will be very appreciated as a reliable way to do so is necessary for investigation.

**Comment by WhistleTips2** [comment]
As this is quite annoying, I'd like to help out as best as I can. Unfortunately, the best way that we (as players) can communicate the reproduction steps is to advise you to log in to the dadspeed server to observe it. I too have experienced this on other servers as well but it's much more intermittent. It's much more consistent on dadspeed.

Should we reach out to the server owners to see if we can share the save files with you to run locally? How can we assist on reproducing this in your environment? We know how to reproduce it on our end, but not sure how to help you do the same on your end.

**Comment by Mr-Cakes** [comment]
Good afternoon.

This remains an issue on all 4 of Greenleaf's servers. There are no reliable steps to reproduce the bug - just attempting to put an item into a receiving container results occasionally in the player being unable to complete this task, this remains the case for the player until they reconnect to the server, though this does not always fix it. I have attempted to intentionally reproduce the bug to no avail, though it does seem more likely to occur when first attempting to input the items when the container is highlighted green but the player is out of range to place it in, when moving within range again this seems to still be preventing. This is however an unreliable way of reproducing the bug.

I note from Dadspeed's discord server that many Dadspeed players believed this to be a bug particular to Dadspeed, I can confirm that this is not the case and it is, as far as I am aware, present on all servers but I do not know the exact steps to reproduce the bug.

**Comment by D3nnis3n** [comment]
Just to reiterate again: I did not claim it is not happening on other servers and If i was understood like that I'm sorry. I meant we are not able to reproduce the issue in any of the environments suitable for investigation, but that is what we currently need.

Savegames could always be helpful, if its related to anything within the world. Locations of where it appears frequently if there is any difference in that would be helpful as well. Checking with as many users as you can how frequently they have it to identify differences is also helpful (and then compare to their latency, etc.).

**Comment by D3nnis3n** [comment]
> I have attempted to intentionally reproduce the bug to no avail, though it does seem more likely to occur when first attempting to input the items when the container is highlighted green but the player is out of range to place it in, when moving within range again this seems to still be preventing. This is however an unreliable way of reproducing the bug.

This is nontheless exactly the kind of information we are looking for and that was so far unknown. Clear reproduction is often not directly achievable, but any hints on how to trigger something with higher likelyness is already very good.

Also please note that in regard to "reported" we mean reported either here on GitHub, via support mail (often used by people not wanting to use GitHub), directly to one of our staff on Discord (fastest contact for server admins), in the official server channels on our discord or on the Steam boards. While we do monitor discord chats depending on free resources in our free time, it is noted in Discord that it is _not_ monitored for bugs and that they need to be brought up at one of the intended places to be tracked. Our QA and other staff does their best to note issues when they see people talking about them, but it's simply not possible to monitor every channel, especially as Discord is intended as a user-to-user space. Might have been worth to clarify that for anyone interested on how operations here work.

**Comment by WhistleTips2** [comment]
> This is nontheless exactly the kind of information we are looking for and that was so far unknown. Clear reproduction is often not directly achievable, but any hints on how to trigger something with higher likelyness is already very good.

Can I assume that you or someone from QA has logged into the dadspeed server and attempted this? Was is not reproducible for you/QA?

I'll reach out to the server owner to see if we can get the save files to you. Do you only want the save files? How should I get those files to you?

I'll also reach out on the dadspeed discord to see if right click is consistently working for anyone. As excplicit said, it almost never works for me as well. Assuming we can get players that aren't as impacted by this (unlikely), what information should we gather and share with you? Any in-game info? Any chat command responses you'd like? Please advise on what/where/how to get this information.

My additional observations on this:

- Seemed to get worse as the world got older/larger.
- I have the bug now when only 6 players are on. Per the in-game diag. pages, my ping is holding steady at 52ms
- Info/data when viewing the map is missing and is the case for most of the time. Multiple relogs will sometimes fix this as well
- Usually, when first logging in, I get this error message in the chat window: "Failed to handle RPC method: SyncDeltaControllerHashSet"

**Comment by D3nnis3n** [comment]
The issue is that even if we could get it on Dadspeed, that doesn't help, as it doesn't have the necessary environment to debug it. We'd know exactly as much as before - it does happen, but not why. We need to get it on one of the official servers (and if possible, actually not WT, as that is not standard) or locally. Every issue that isn't apparent by code is always debugged locally.

Save files and config files (if necessary for any kind of settlement settings) should suffice.

I do understand you reported that the issue happens on WT as well, but I did just ask around at our resident players and they do not observe the issue, hence the whole "unlikely to find people not impacted" is irritating to me. There is also no reports made by GM's on the matter. Again, I absolutely believe you and other people got it there - but the serverity that is being presented is not something I could confirm with own data.

Thanks for all the additional information so far, devs do check this issue.

**Comment by WhistleTips2** [comment]
> Did the people seeing it on any official server by chance have high latency? Residents on WT are mostly from europe, as the server, so low latency. How's load on your servers? I'll make a public poll later today, I'm currently on vacation until end of april - hence the short answers at the start.

I do not play on WT, so it wasn't me that initially mentioned it not working there. However, I just logged in to WT...

I spawned into what looked like the busier town. I opened my map and the map was missing all of the icons (tables, shops, etc.) This bug is also the norm on dadspeed. I ran a bit outside of town to place down my tent. I grabbed sand and was able to right-click place it into the small stockpile. Same with a sandstone.

I logged out and logged back in. Map is now working. However, right-click is now broken. I am unable to right-click place something I'm carrying into the stockpile. So I can confirm that the same bug(s) are happening on WT.

I'm in the U.S. and my ping is 133ms.

I'll stay logged in to WT for a little bit if you want me to get more information while in this current state but I won't be able to for long.

**Comment by ECO-ExPLiCiT** [comment]
> > Did the people seeing it on any official server by chance have high latency? Residents on WT are mostly from europe, as the server, so low latency. How's load on your servers? I'll make a public poll later today, I'm currently on vacation until end of april - hence the short answers at the start.
> 
> I do not play on WT, so it wasn't me that initially mentioned it not working there. However, I just logged in to WT...
> 
> I spawned into what looked like the busier town. I opened my map and the map was missing all of the icons (tables, shops, etc.) This bug is also the norm on dadspeed. I ran a bit outside of town to place down my tent. I grabbed sand and was able to right-click place it into the small stockpile. Same with a sandstone.
> 
> I logged out and logged back in. Map is working. However, right-click is now broken. I am unable to right-click place something I'm carrying into the stockpile. So I can confirm that the same bug(s) are happening on WT.
> 
> I'm in the U.S. and my ping is 133ms. I'm on a wired connection (not wifi).
> 
> I'll stay logged in to WT for a little bit if you want me to get more information while in this current state but I won't be able to for long.
> 
> [Video of it happening on WT](https://youtu.be/r8E3sGB34fg). I tried to show the right-click not being an option and then I tabbed through the [F2] diag. pages. Also note the proximity voice chat icon stuck on.

Thanks Whistletips for going through all that testing on WT.

I wanted to also mention that I would be surprised if this is directly related to ping or lag unless, that said lag is during the initial loading into the server, and therefore something doesn't get loaded properly. The reason I bring this up is that when you have the issue after you log in, there is nothing you can do to make the issue go away, and we have tried just about everything. The only way that you can get the right-click to start working again is to keep trying to log back into the server until it does. That is why I feel like something didn't load properly while joining the server.

I will also try to see if I can replicate the issue on WT as well.

**Comment by johnkslg** [comment]
Can you explain the bug better? that screenshot showing the debug overlay holds all the relevant information. What is in your selected and carried slot? what is being highlighted? whats the control popup look like? All of that is cropped out.

**Comment by WhistleTips2** [comment]
> Can you explain the bug better? that screenshot showing the debug overlay holds all the relevant information. What is in your selected and carried slot? what is being highlighted? whats the control popup look like? All of that is cropped out.

As posted above, [I uploaded a video of it happening on WT](https://youtu.be/r8E3sGB34fg). Hopefully that should show you that I can't right click to place the item(s) in my hand into the stockpile.

**Comment by ECO-ExPLiCiT** [comment]
> Can you explain the bug better? that screenshot showing the debug overlay holds all the relevant information. What is in your selected and carried slot? what is being highlighted? whats the control popup look like? All of that is cropped out.

John,

Does this screen shop help better?
![20240422085052_1](https://github.com/StrangeLoopGames/EcoIssues/assets/33853005/fdbc0435-8b37-4455-a8df-5d414b66ce38)

**Comment by D3nnis3n** [comment]
Please recheck on Update 10.3. We have not been able to reproduce the issue and the information in the screenshots was unfortunately not useful for that either, but we made some more refactors that hopefully addressed the issue.

**Comment by D3nnis3n** [comment]
Fixed in Update 11.
