### ISSUE TITLE
More Room Related server crashes on Release

### ISSUE THREAD

**Issue by padmanek** [StrangeLoopGames/EcoIssues#25192]
Eco 11.0.6
Diffrent stack trace than in https://github.com/StrangeLoopGames/EcoIssues/issues/25168

[log_241009055016.log](https://github.com/user-attachments/files/17313740/log_241009055016.log)
```
[17:29:27.629] [198] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.GetOutdoorObjects(Deed deed)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.RecalcOutdoorRoom(Deed deed)
   at Eco.Gameplay.Rooms.RoomUpdater.Update(ThreadSafeList`1 rooms, ThreadSafeDictionary`2 posToRooms, IEnumerable`1 positions, IEnumerable`1 roomsToUpdateValue)
   at Eco.Gameplay.Rooms.RoomData.ScanChangesForRooms()
   at Eco.Gameplay.Rooms.RoomPlugin.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass4_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   --- End of inner exception stack trace --- System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.GetOutdoorObjects(Deed deed)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.RecalcOutdoorRoom(Deed deed)
   at Eco.Gameplay.Rooms.RoomUpdater.Update(ThreadSafeList`1 rooms, ThreadSafeDictionary`2 posToRooms, IEnumerable`1 positions, IEnumerable`1 roomsToUpdateValue)
   at Eco.Gameplay.Rooms.RoomData.ScanChangesForRooms()
   at Eco.Gameplay.Rooms.RoomPlugin.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass4_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   ```
   
   and one more (same stack trace)
   
[log_241009055016.log](https://github.com/user-attachments/files/17314041/log_241009055016.log)

**Comment by D3nnis3n** [comment]
Already fixed via https://github.com/StrangeLoopGames/Eco/pull/14520 in staging.

**Comment by padmanek** [comment]
> Already fixed via [StrangeLoopGames/Eco#14520](https://github.com/StrangeLoopGames/Eco/pull/14520) in staging.

[log_241029060021.log](https://github.com/user-attachments/files/17559577/log_241029060021.log)

Still happens on 11.1, same stack trace:

```
[16:16:09.079] [17] [Error] [Eco] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.GetOutdoorObjects(Deed deed)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.RecalcOutdoorRoom(Deed deed)
   at Eco.Gameplay.Rooms.RoomUpdater.Update(ThreadSafeList`1 rooms, ThreadSafeDictionary`2 posToRooms, IEnumerable`1 positions, IEnumerable`1 roomsToUpdateValue)
   at Eco.Gameplay.Rooms.RoomData.ScanChangesForRooms()
   at Eco.Gameplay.Rooms.RoomPlugin.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass4_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
   --- End of inner exception stack trace --- System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.GetOutdoorObjects(Deed deed)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Eco.Gameplay.Rooms.OutdoorRoomUtil.RecalcOutdoorRoom(Deed deed)
   at Eco.Gameplay.Rooms.RoomUpdater.Update(ThreadSafeList`1 rooms, ThreadSafeDictionary`2 posToRooms, IEnumerable`1 positions, IEnumerable`1 roomsToUpdateValue)
   at Eco.Gameplay.Rooms.RoomData.ScanChangesForRooms()
   at Eco.Gameplay.Rooms.RoomPlugin.TickAll()
   at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass4_0.<.ctor>b__0(CancellationToken token)
   at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
   at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
```

**Comment by D3nnis3n** [comment]
Unfortunately the stack trace wasn't helpful to address these crashes and we fixed the issues occuring during playtest through reproduction cases. I fear given there hasn't been success before with just the stacktrace, we will need a concrete reproduction case for any remaining appearances. (On official servers there had been none since the fix in playtest)

So if you are able to find a solid reproduction case (happily with a save) please open a new issue with that data.

**Comment by padmanek** [comment]
So I've grabbed backup that was 7 minutes before a crash like the one above and loaded it on my dev server which is a 1:1 copy of  my live server but the crash did not occur. So it must be players modifying their buildings somehow. 

Any tips on finding a reproduction case? Or is it simply starring at Chron logs from around when it happens? 

It feels like some null checks are missing in the function that crashes out.

```
Oct 30 02:58:07 ubuntu EcoServer[704232]: [02:58:07] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
Oct 30 02:58:07 ubuntu EcoServer[704232]:   Inner Exception:
Oct 30 02:58:07 ubuntu EcoServer[704232]:   System.NullReferenceException: Object reference not set to an instance of an object.
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Gameplay.Rooms.OutdoorRoomUtil.GetOutdoorObjects(Deed deed)+MoveNext()
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Gameplay.Rooms.OutdoorRoomUtil.RecalcOutdoorRoom(Deed deed)
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Gameplay.Rooms.RoomUpdater.Update(ThreadSafeList`1 rooms, ThreadSafeDictionary`2 posToRooms, IEnumerable`1 positions, IEnumerable`1 roomsToUpdateValue)
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Gameplay.Rooms.RoomData.ScanChangesForRooms()
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Gameplay.Rooms.RoomPlugin.TickAll()
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Core.Utils.Threading.EventDrivenWorker.<>c__DisplayClass4_0.<.ctor>b__0(CancellationToken token)
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Core.Utils.Threading.EventDrivenWorker.DoRepeatableWork(CancellationToken token)
Oct 30 02:58:07 ubuntu EcoServer[704232]:      at Eco.Core.Utils.Threading.RepeatableWorkerBase.DoWork(CancellationToken token)
Oct 30 02:58:07 ubuntu EcoServer[704232]:
Oct 30 02:58:08 ubuntu systemd[1]: EcoServer1.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 02:58:08 ubuntu systemd[1]: EcoServer1.service: Failed with result 'exit-code'.
Oct 30 02:58:08 ubuntu systemd[1]: EcoServer1.service: Consumed 22h 38min 19.956s CPU time.
Oct 30 02:58:13 ubuntu systemd[1]: EcoServer1.service: Scheduled restart job, restart counter is at 3.
Oct 30 02:58:13 ubuntu systemd[1]: Stopped Silverleaf Eco 1.
Oct 30 02:58:13 ubuntu systemd[1]: EcoServer1.service: Consumed 22h 38min 19.956s CPU time.
Oct 30 02:58:13 ubuntu systemd[1]: Started Silverleaf Eco 1.
Oct 30 02:58:15 ubuntu EcoServer[711552]: [02:58:15] Logged in to Strange Cloud using username and password.
Oct 30 02:58:15 ubuntu EcoServer[711552]: [02:58:15] Eco Server 0.11.1.0 beta release-750, Logged in as padman
```

**Comment by D3nnis3n** [comment]
The way we found the causes was monitoring what users do and making them aware to report their activity when a crash happens, especially if its a repeated one shortly after another. Null checks had been added as well and since those measures no crashes have resurfaced on any official server, but the internal issue has already been reopened.

**Comment by D3nnis3n** [comment]
We were able to reproduce one more potential cause and added a fix to 11.1.2, maybe that resolves the one you are seeing. (If still the case, given you noted there was hardware problems)
