### ISSUE TITLE
Korean font is broken

### ISSUE THREAD

**Issue by ehduq95** [StrangeLoopGames/EcoIssues#25229]
![image](https://github.com/user-attachments/assets/4ea10bcf-d133-4c89-9d2e-95912fd1130d)
This bug occurred after the 10.0 update. Some characters are printed as ㅁㅁㅁㅁ

**Comment by ehduq95** [comment]
Almost a year later, it is still not fixed

![Image](https://github.com/user-attachments/assets/85785354-862c-4151-b6d1-dfe1d0dc0d71)

<img width="696" height="543" alt="Image" src="https://github.com/user-attachments/assets/79985d63-ffa3-4d72-8ae7-37b9fa0a5e41" />

**Comment by D3nnis3n** [comment]
Fixed in 12.0.3.

**Comment by ehduq95** [comment]
> Fixed in 12.0.3.

some of them are not fixed

<img width="584" height="869" alt="Image" src="https://github.com/user-attachments/assets/cbcd45bc-4558-4614-9761-37219b263d83" />

<img width="1038" height="859" alt="Image" src="https://github.com/user-attachments/assets/55ee66dc-7863-4c3f-a400-e5bba164db24" />

<img width="913" height="511" alt="Image" src="https://github.com/user-attachments/assets/147e72c7-394f-46aa-ad96-a6dfaa985a3d" />
