### ISSUE TITLE
Law UI does not handle some lists

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#2869]
There's a few cases where `<this type="list">` works, but there are still a couple cases in the original design where it seems to do nothing (such as the if, else, otherwise list, as I've mentioned previously), and many new ones seem not to work either.

This should be testable both on master and on marjie-statDatabase

**Comment by MarjieAVolk** [comment]
By the way, as I've also said before, I really think lists should never be inline.  Each list element should have it's own line.  Sometimes list elements get pretty big, and it becomes very unclear what the 'x' is actually going to remove.

**Comment by MarjieAVolk** [comment]
Also by the way, kind of a feature request - I've added the field "MinElements" to lists (anything that has <this type="list">).  Pretty self explanatory, this is the minimum number of elements allowed in the list. 
 Most things require 1, but some require 2 or none.  The server will throw an exception if the user tries to remove an element when it would not be allowed.  But it would be nice if the 'x' were hidden if it wouldn't be allowed.

**Comment by MarjieAVolk** [comment]
Take a look at the format string.  There are several important elements that have '<this type='list'>' and yet have no add button or 'x' buttons.  On marjie-statDatabase, now one of the root nodes is a list - there should be a list of clauses that you can add to and remove from.  It has no add or remove buttons, and furthermore is formatted very strangely, since the list is not meant to be on a single line (each element is visually large and has multiple lines within it).  The same has always been true for conditions, which have always been lists on the server, but we decided not to fix this error at that time in order to meet a deadline.

**Comment by syuzan-yeranosyan** [comment]
fixed: each <this type="list"> appears in a new row, and 'x' remove button is displayed in the top  left side instead of right, so it is more clear what 'x' delets 
pushed on 'marjie-statDatabase' branch.

**Comment by MarjieAVolk** [comment]
These style improvements help.  But the core issue is still not fixed.  The UI is not following the format string.  There are several lists which are not being treated as lists.

Here (on marjie-statDatabase branch) there should be a list of clauses.  That is, the whole section here is a list element, and you should be able to add more clause list elements.
![image](https://user-images.githubusercontent.com/23460210/33781633-41626536-dc0a-11e7-9e7d-624334b07f3d.png)

Here's an example of something that should be possible:
```
(prevent action) When attempting to Craft (all)
    Prevent
(prevent action) When attempting to Pick Up (all)
    Tax 1 Bucks
+
```

Also I am finding the styling of the line breaks to be confusing.  First of all, each 'or' should be on the next line.  (`When attempting to Craft (all) \n or Pick Up (all)`).  Second, I think list elements should be styled more like sections.  Their indentation doesn't look right.

You can also see this same issue on master.  When you select 'condition', there should be a list of if/else if clauses:
![image](https://user-images.githubusercontent.com/23460210/33781656-59d7faae-dc0a-11e7-9add-81c99080e378.png)

It should be able to look like this:
```
If admin
    Then allow
Otherwise if (numeric comparison) current time < (constant) 3
    Then prevent
+
Otherwise tax 1 Bucks
```

**Comment by syuzan-yeranosyan** [comment]
done on marjie-statDatabase branch
