### ISSUE TITLE
Interact Key UI contrast on mouse click buttons is unreadable

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#3277]
Light blue highlighting is not sufficient to read what button to use to interact with. 

![image](https://user-images.githubusercontent.com/6262198/34699485-6ca8bee8-f492-11e7-8bfe-44ba39de5fe6.png)

Recommend something higher contrast

**Comment by MarjieAVolk** [comment]
Also recommend not being transparent, that would help a lot

**Comment by keegan-o** [comment]
I view all these prompts as being wrong ~60% of the time as a more important bug... >.>

**Comment by MarjieAVolk** [comment]
Better to have them be hidden than unreadable.  So I would say yes.

**Comment by Nanders** [comment]
The wrong prompts bug has been fixed since this filing

**Comment by keegan-o** [comment]
The prompts still prompt you to 'Put ______' into world objects which is still wrong, so not all of the wrong prompts have been fixed. Will try out yellow but not close until someone confirms this is better.

![image](https://user-images.githubusercontent.com/14983165/38634589-cf1fc2f0-3d77-11e8-9e10-7895c3b69d05.png)

**Comment by MarjieAVolk** [comment]
Can we have it not be transparent please?  I don't see why it would be transparent.  IMO the icon background should be white, or close to white, not grey, and have a thicker black outline to match the font.

**Comment by keegan-o** [comment]
Made it not transparent (had to kinda re-create the image), should be much more visible now... though this graphic does kinda stick out like a sore thumb.

![image](https://user-images.githubusercontent.com/14983165/38642425-e9610b94-3d8e-11e8-88f0-d8e6b068517a.png)

**Comment by MarjieAVolk** [comment]
Thanks, I think that's going to be a lot easier to read.  Although I do see your point about it looking out of place still.

Back in the day I had been meaning to put a background on this little popup.  The background could be semitransparent.  But I think that will make this look better also.

**Comment by Nanders** [comment]
fwiw I don't think the icon sticks out any more than the text already does.

Probably could use a style pass at some point

**Comment by keegan-o** [comment]
yarr... shalll close this for now anyways.
