### ISSUE TITLE
Roof Builder Inner Corner piece issue

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3786]
![image](https://user-images.githubusercontent.com/23460210/35752524-1f2cd888-0811-11e8-8ad2-0f81b20d7ab6.png)
![image](https://user-images.githubusercontent.com/23460210/35752532-2a666a66-0811-11e8-8de5-560812c2010f.png)
![image](https://user-images.githubusercontent.com/23460210/35752548-3978505a-0811-11e8-8079-9238855b45b3.png)

**Comment by MarjieAVolk** [comment]
It seems this is the case for all roofs, so maybe this is not supported?

**Comment by keegan-o** [comment]
This builder is old and needs updates but this builder was also quite tricky to set up, so I'm gonna file this under enhancement for when I can dive back into it. I do intend to make it better though!

**Comment by WeaselDog** [comment]
This should be fixed with the new building forms?

**Comment by beastyn** [comment]
I would say its still a problem

![bandicam 2020-05-22 16-40-38-299.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/09175993-e696-4590-84a7-4b758452e66b)

**Comment by keegan-o** [comment]
Still a problem till we add the new forms to the old materials like brick, indeed!

**Comment by keegan-o** [comment]
dupe of my recently re-named 'Add New Forms to Old Materials' bug, scheduled for 9.1
