### ISSUE TITLE
Shovel issue 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#428]
http://ecoforum.strangeloopgames.com/topic/644/item-remains-in-shovel-can-t-use-my-shovel

**Comment by mariowenig** [comment]
Should be resolved in 4.2. Close.

**Comment by stormoffires** [comment]
bug still in the game, i can pick up an item say 5 bricks, go to place them but then it says i can not carry more but i no longer have the 5 but the game says i do. so here it shows i cant place the 5 i dont have but it still thinks i have them. 
![broken hammer](https://cloud.githubusercontent.com/assets/20627148/17160711/da132d12-535b-11e6-8d81-1c068e1b7f95.png)

**Comment by mariowenig** [comment]
Nice find, any good reproduction steps? Previous bug was shovel related. This uses the hammer? Gonna test.

**Comment by stormoffires** [comment]
it is the same bug, it is server related, i believe it is the users files. a server restarts this issue. if i reloginto the server my carry is empty, if i use a shovel grab a scoop of dirt and drop it, it still says i have something in my carry. it was not shovel related but carry related didnt matter what i had. but a server restart fixed this issue.

**Comment by metachronism** [comment]
should be fixed in alpha 5
