### ISSUE TITLE
devtool cant delete fallen trees

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4292]
we had a troll on the server at some point while admins were offline and now we have a bunch of fallen trees in the river the devtool wont highlight it so it cant be deleted
![image](https://user-images.githubusercontent.com/29722757/36069506-4c609512-0f3f-11e8-89e4-7758b9d2c7b3.png)

**Comment by MarjieAVolk** [comment]
Don't you want all those valuable logs?? :P

**Comment by ecoemmeck** [comment]
Well yes and no having to clean up 50 something odd trees was slightly annoying especially the trees in the river that was 20 blocks lower than the land

**Comment by SeanAtr0n** [comment]
fixed 7.2

**Comment by ecoemmeck** [comment]
7.3.1 dev tool still isnt targeting fallen trees

![image](https://user-images.githubusercontent.com/29722757/38233226-2e37100c-375d-11e8-94a2-f8cf0c58a067.png)

![image](https://user-images.githubusercontent.com/29722757/38233251-4518372e-375d-11e8-8d8b-762fae7f7800.png)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#276
