### ISSUE TITLE
Player issue signs in under another character

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4296]
I'm getting reports from a few different players on my servers that they are getting logged in as someone else's character when joining the server

Extra info they all seem to be logging in as the same character that's not theirs
[BDG]Voultri is the user they log in as and i know of at least 2 players that when they log in come up as the character 

both have been owned the game since alpha 5 and used the steam link

**Comment by ecoemmeck** [comment]
we have now had this issue with another player while talking to them in discord they logged into the game under a different players name.

it would have been the 1st time login for them but instead they were in the body of another player and have all the inventory of that player

**Comment by MarjieAVolk** [comment]
Do these people always log in as the other person?  Or is it just sometimes?  Could you check /whois both for the person they are logging in as (Voultri) and for the person they should be logging in as, and share that with me?

**Comment by ecoemmeck** [comment]
I will get them to login again when I can.
However I can give a little more info for now we have 2 servers running on the main server he comes up as voultri but on the other server he comes up as himself I was watching the network tabs on both servers to notice this. Also his ping when he signs in on the main server as voultri is like 700+ but on the secondary server when he signs in as himself his ping is under 30

**Comment by KyeEco** [comment]
i can confirm this as it has happened to me, what i had done was restart my game, then reinstalled as restarting the game doesn't help, but for some reason that hasn't worked for us,

**Comment by ecoemmeck** [comment]
/whois PH | Revo 
![image](https://user-images.githubusercontent.com/29722757/36144213-853841be-1101-11e8-97e8-17bcc9ca8739.png)

/whois [BDG]Voultri
![image](https://user-images.githubusercontent.com/29722757/36144173-5aa981ce-1101-11e8-9eef-d427b44bbc8d.png)

**Comment by ecoemmeck** [comment]
this is another player who has had the same thing happen
/whois Dampiir
main server
![image](https://user-images.githubusercontent.com/29722757/36150838-2ce29a56-1119-11e8-93c4-b0e207734f30.png)

2nd server
![image](https://user-images.githubusercontent.com/29722757/36150739-c2e180e0-1118-11e8-847c-81c0fbfa543e.png)

/whois temperor
![image](https://user-images.githubusercontent.com/29722757/36150539-2add5d46-1118-11e8-9f07-8a815fc5055c.png)

**Comment by ecoemmeck** [comment]
hope this helps if you need more info or anything just let me know

**Comment by MarjieAVolk** [comment]
Well this is strange.  Their ids are both the same.

For Voultri and temperor, does /whois show the same thing for them on both servers?

**Comment by ecoemmeck** [comment]
Wow I must have been tired when uploading all of that as I didn't even notice the Id's were the same oops.

Temperor and voultri have only been on the main server, they haven't connected to the secondary server

**Comment by MarjieAVolk** [comment]
Yeah so sounds like these players all have the same id, so whoever logs in first sets the name, then they all share a character.  Do you know if they bought through steam or through our site?

**Comment by ecoemmeck** [comment]
Temperor and voultri I have no clue where they brought the game from. As for revo and dampiir they are alpha backers

**Comment by MarjieAVolk** [comment]
Okay.  We looked up the ids from the first post and found that they belong to Revo, not to Voultri.  Voultri owns the game but has different ids.  So... I am really not sure how this happened.  Is Voultri an active player?  Maybe you can delete their user from the save file.

**Comment by KyeEco** [comment]
Yeah this is a strange one, i dont really want to be deleteing players user files if i can help it :/ but if it will help us weed out this bug then im sure it will be fine we will just compensate the affected :)

**Comment by KyeEco** [comment]
Well if they are hacking please let us know as its a bannable offence on our servers :)

**Comment by ecoemmeck** [comment]
It may well be hacking as we had the require authorization turned off for awhile

**Comment by KyeEco** [comment]
Unless thats the issue? Maybe having the require auth turned off messes with the user files? Instead of actually confirmin it has a bit of a jumble?

**Comment by MarjieAVolk** [comment]
Hmmmmm yeah that is possible.  Still thinking about it.

So has Voultri or temperor logged back in lately?  Do you know if they still log in as their name?  Or do they log in as temperor#2 now?  If it was a weird side effect of turning off require auth, I would expect each person to log in as a different character now (but perhaps with weird names)

**Comment by KyeEco** [comment]
Not that i have seen, when i get home if emmeck hasnt already we will delete the user files and see if it makes a difference

**Comment by ecoemmeck** [comment]
I don't think either of them have been back online recently. Though checking last online time will be difficult S revo and dampiir signed in as them last night so I could get info for the issue

**Comment by KyeEco** [comment]
Not that i have seen, when i get home if emmeck hasnt already we will delete the user files and see if it makes a difference, but when signed in under these names you have no access to anything thats under your own name (obviously) even if its still the same acc id number

**Comment by MarjieAVolk** [comment]
Okay.  Well as always, back up the save before performing surgery :P Deleting user files can break stuff sometimes.  You may want to go and make sure they don't have any property first, for example.

**Comment by MarjieAVolk** [comment]
But at this point it seems likely that it got into a weird state, maybe because of turning off require auth, and if you doctor it it probably won't happen again.

**Comment by ecoemmeck** [comment]
Thanks for your help we will report how we go with fixing this

**Comment by MarjieAVolk** [comment]
I am going to add some better login handling that may prevent this from happening again (if I have guessed right as to what happened).  But let me know what you find.

**Comment by ecoemmeck** [comment]
im having some trouble locating the users in the game.eco file ive been reading the file for the last 10 minutes and can find either of the 2 users by either of their steam id or slg id

![image](https://user-images.githubusercontent.com/29722757/36189298-b81fb8ce-11a5-11e8-9a8e-a75febd39859.png)

could i suggest for the future the users in game is also attached to the id's to make it easier to find them.

**Comment by ClayC90** [comment]
I believe this was closed by accident @metachronism

**Comment by MarjieAVolk** [comment]
This was closed automatically because I marked it as fixed in some code that went in.  That will be released today, and may prevent this from happening in the future.  You can keep posting in this bug and I will see it, if you find more information.

@ecoemmeck sorry about the save file names, we've gone back and forth on what to name them.  It sounds like a reasonable compromise to put both the name and the id in the title, for legibility.

If you don't see a file name with either of the ids.... do you see one that is just '_', or maybe '_' with a bunch of random numbers and letters after it (not an slg id)?  Because now that I think of it, that would fit with my interpretation of what happened.

**Comment by ecoemmeck** [comment]
I think I saw a bunch of weird user id's I will check when I get home

**Comment by KyeEco** [comment]
hey guys the fix didnt work, our players are still getting others names,

**Comment by MarjieAVolk** [comment]
The fix wouldn't fix existing mixups, only prevent new people from getting mixed up.  Are new people getting mixed up that weren't before?

**Comment by ecoemmeck** [comment]
We haven't had any new mixups yet. But still struggling to figure out which users to delete to get the players in.
I thought of something but doubt it would work, copying the users from the server that they have successfully logged into over to the server that has them confused with the other players

**Comment by MarjieAVolk** [comment]
Is it that you don't know which of the two people to delete?  Or you can't find which file is theirs?
