### ISSUE TITLE
USER ISSUE: Admin /help error

### ISSUE THREAD

**Issue by bfc1974** [StrangeLoopGames/EcoIssues#4389]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
as server admin i typed in /help to get in game commands
This was after i had installed clays toolkit and also an admin mod provided by my server provider

**Expected behavior:**
given me in game commands

**Actual behavior:**
Caught exception: Caught exception invoking RPC SendChat on ChatManager!

Exception has been thrown by the target of an invocation.
Value cannot be null.
Parameter name: key

Stack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)

**Comment by bfc1974** [comment]
i have since uninstalled both the admin mod and the clays toolkit

**Comment by pamduncan** [comment]
This is a known issue with AdminUtills and 7.1.0 - please note that mod is not yet been released for 7.1.0

You will need to remove it until you get one for 7.2.0

**Comment by bfc1974** [comment]
so its damaged the install and requires a server wipe?

**Comment by Pradoxzon** [comment]
AdminUtils won't have damaged the install or require a wipe.
Just deleting the mod should solve the issue.
This is a known issue with some servers, and I'm working to find out how to fix it.

**Comment by bfc1974** [comment]
still get the same inability to access the commands /help and /repopulate

**Comment by Pradoxzon** [comment]
did you remove the mod?

**Comment by bfc1974** [comment]
i have reinstalled the server was just way easier

**Comment by Pradoxzon** [comment]
but you were experiencing issues even after you removed the mod?

**Comment by MarjieAVolk** [comment]
Since this is a problem with a mod, closing the issue
