### ISSUE TITLE
USER ISSUE: Plant already exists there bug

### ISSUE THREAD

**Issue by Bugasu** [StrangeLoopGames/EcoIssues#4669]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Planted a tree
2. Restarted server using "exit" command and relaunch at a later time
3. Sapling disappeared
4. When attempting to replant on soil, receive a "Plant already exists there" message

**Expected behavior:**
Either sapling shouldnt have disappeared, or ability to replant should've happened

**Actual behavior:**
Missing sapling and plant already exists there

**Comment by Bugasu** [comment]
Additional info since I now have a soil sampler:
These spots appear to have a "dead" plant there, but it does not physically show, and removing the block and readding, or attempting to put dirt on it and removing it to see if it goes away does not work.

**Comment by MarjieAVolk** [comment]
@craig-jong You might want to examine some of the closed threads for more repro steps, etc ^

**Comment by Teachrawr** [comment]
Also experiencing "Plant already exists there" bug, despite multiple server restarts.  I have a couple of farm areas that are ~75% unusable, due to the bug.  I can plant if I add or subtract a layer of dirt, but moving dirt does not correct the issue on the affect cells.

**Comment by SeanAtr0n** [comment]
should be fixed in 7.3.2

**Comment by purpleypete** [comment]
issue still remains
![eco 09_04_2018 16_01_57](https://user-images.githubusercontent.com/37105142/38505722-c3169c36-3c0f-11e8-8675-907616d13f59.png)
game saves attached:
https://drive.google.com/open?id=1lzj3y5KWgr9SufkPYYxqbYBj9LGCdewp

**Comment by purpleypete** [comment]
No mods and let me restart and try now

**Comment by purpleypete** [comment]
Update 2:
after 24 hours the plots fix themselves, so the problem does correct itself in the end just means you need 2 farms and cycle the growth in the mean time untill the first plot is left 24 hours.
We use a 3 hour growth cycle this is why we encounter the bug i guess.
even though the bug corrects itself within 24 hours or at least it has this time.

**Comment by craig-jong** [comment]
I'm almost positive this bug has been fixed. We've changed how dead plants are removed to, so please let me know if this issue continues - my tests so far have shown it to be fixed.
