### ISSUE TITLE
USER ISSUE: Housing Tooltip failure

### ISSUE THREAD

**Issue by Fazamere** [StrangeLoopGames/EcoIssues#5490]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Hover over housing SP value pie chart. Tooltip disappears very quickly, making it impossible to assess housing in each room for large houses.

**Expected behavior:**
Stay in place while read, able to scroll via scrollbar with mouse, or while scrollwheel rolls

**Actual behavior:**
Click on scrollbar does nothing, if scrolling via scrollwheel the tooltip disappears

**Comment by johnkslg** [comment]
Fixed

**Comment by Fazamere** [comment]
Hi guys, sorry but this issue still occurs as of version 7.2.4 or latest 7.2.5. Let me describe in detail:

I have a house with 12 rooms, 2 of each type. I hover over the house pie chart, and it shows a breakdown. Obviously there are more furniture items than the box can hold. So a scrollbar appears at the side. If I try to move my mouse to the scrollbar, the tooltip disappears. If I move my mouse over one of the furniture items, a sub-tool tip appears and it is stable. If I move my mouse over the general background and use the mouse-scroll wheel it scrolls for a second or too, but then the entire housing tooltip disappears. So that means, I cannot see the full list of rooms I have in my house, or which room is causing the imbalance.

Also, I have a constant issue of housing items selecting the lowest quality item (e.g. latrine), when there are higher quality items available nearby (large rug, medium rug). This causes imbalance every time I logon, and I have to rearrange furniture every time I logon. I'm not the only user who finds this issue a pain to deal with to use housing skill points. I really love the housing mechanic but the user interface issues make it difficult to use in practice.

Can you please: 

(a) fix the tooltip delay so if your mouse is in the housing tooltip area it stays, or make housing skill point breakdown an actual box we can click and stay in to investigate.
(b) fix the housing point allocation so that the highest value item in a room always goes first and gets 100%, while latter items get 75%, etc.

If you have further questions, please email me or contact me on Pam's world server on Discord or something and I can talk you through it.

Fazamere

**Comment by MarjieAVolk** [comment]
I think in this case it was intended to be marked as 'fixed in next release', although I don't personally know much about the issue.
