### ISSUE TITLE
Fertilizer Stacking Bug

### ISSUE THREAD

**Issue by KevinAllbritten** [StrangeLoopGames/EcoIssues#5652]
Fertilizer stacks show as a quantity of 1 in the store regardless of size.
Fertilizer stacks can not be merged with each other.
Single instances of fertilizer cannot be merged to create a stack.

Soil samplers cannot be stacked.

**Comment by MarjieAVolk** [comment]
What version of the game are you play on?  I believe all of these issues have been fixed in 7.2 (see https://github.com/StrangeLoopGames/EcoIssues/issues/3617, https://github.com/StrangeLoopGames/EcoIssues/issues/4687)

**Comment by KevinAllbritten** [comment]
This is not fixed. I am on version 7.2.3.

Here you can see that I can't merge the hide ash fertilizer to 50 nor merge the 4 soil samplers.
![shop storage](https://user-images.githubusercontent.com/37168093/37185170-af358372-2304-11e8-840b-ec0308f1bfc0.jpg)

Previous picture you saw there are 52 hide ash, 20 blood meal, and 20 pelt fertilizers. The store only shows 3, 1, and 1.
![shop](https://user-images.githubusercontent.com/37168093/37185189-ca35f53a-2304-11e8-8d54-cc461a735f67.jpg)

**Comment by MarjieAVolk** [comment]
The soil samplers are not supposed to stack.  The rest are bugs.

**Comment by craig-jong** [comment]
Should work now
