### ISSUE TITLE
Server Crashing 0.7.2.2 - Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#5677]
Thought I would create a new issue for this as the other issue was a different crash/stacktrace

We have had this crash 7 times in the last 12 hours:
https://pastebin.com/XzqapbdJ

**Comment by metachronism** [comment]
should be fixed in 7.2.3

**Comment by Yorkforce** [comment]
Still occuring unfortunately although not as much, 3 times in last 12 hours

--BEGIN DUMP--
Dump Time
03/09/2018 23:35:10

Exception
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: arrayIndex
  at System.Collections.Immutable.Requires.FailRange (System.String parameterName, System.String message) [0x00008] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at System.Collections.Immutable.Requires.Range (System.Boolean condition, System.String parameterName, System.String message) [0x00003] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at System.Collections.Immutable.ImmutableList`1[T].CopyTo (T[] array, System.Int32 arrayIndex) [0x00027] in <bffdd0b30ee64b3f9ebc6a9f353a97c1>:0 
  at Eco.Core.Utils.ThreadSafeList`1[T].CopyTo (T[] array, System.Int32 arrayIndex) [0x00000] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x00021] in <7db1fd4936fd4181accec939c2554b01>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <7db1fd4936fd4181accec939c2554b01>:0 
  at Eco.Gameplay.Systems.Chat.ChatData.get_Messages () [0x00000] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at Eco.Core.Utils.CoreReflectionUtils+<>c__DisplayClass11_0`2[TTarget,TReturn].<FuncMethodHelper>b__0 (TTarget target) [0x00000] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.Serializers.ClassSerializer`1+<>c__DisplayClass11_0[T].<Initialize>b__1 (System.Object obj) [0x00000] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.Serializers.ClassSerializer`1[T].EncodeMembers (System.IO.BinaryWriter writer, System.Object instance) [0x00021] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.Serializers.ObjectSerializer.Encode (System.IO.BinaryWriter writer, System.Object instance) [0x0003e] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.SimpleSerializer.Serialize (System.Object obj) [0x00023] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.CurrentSerializer.Serialize (System.Object obj) [0x00000] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.EcoSerializer.Serialize (System.Object obj) [0x00000] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.ZipBlob.Persist (System.Object obj) [0x00000] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Core.Serialization.ISerializationUtil.Save (Eco.Core.Serialization.IStorage storage) [0x00006] in <9dd4d243d48e4c0cb5bb8fd00ab12543>:0 
  at Eco.Gameplay.Systems.Chat.ChatServer.Run () [0x0000f] in <5a6fe3953ad54612b7e68da0f55f09a8>:0 
  at Eco.Server.PluginManager+<>c__DisplayClass18_0.<StartPlugins>b__0 (System.Object x) [0x00000] in <f5009e60b8244725a694a126bf7211cc>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <997dde78663c4b4bbf4a1f2b8d296905>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <997dde78663c4b4bbf4a1f2b8d296905>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <997dde78663c4b4bbf4a1f2b8d296905>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <997dde78663c4b4bbf4a1f2b8d296905>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <997dde78663c4b4bbf4a1f2b8d296905>:0 

--END DUMP--

**Comment by metachronism** [comment]
for sure fixed in 7.3
