### ISSUE TITLE
USER ISSUE: Stacked Torches aren't moveable.

### ISSUE THREAD

**Issue by geeknessfr** [StrangeLoopGames/EcoIssues#6598]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Have a stack of Torches in your inventory or in a chest
2. Try to place in a chest or in your inventory by Drag'n'Drop

**Expected behavior:**
It should move.

**Actual behavior:**
It stay in place and can't move it...

Screenshot : https://i.imgur.com/gKgf6TG.jpg

**Comment by MarjieAVolk** [comment]
Hmmm since we no longer allow stacking torches, I guess existing stacked torches are messed up

**Comment by craig-jong** [comment]
that's spooky

**Comment by geeknessfr** [comment]
Good luck guys ! You make a great work here !

**Comment by thunderbom** [comment]
I have the same problem - stack of 5 torches occupy 1 slot of my backpack and I can do nothing with them. It's not possible to move them anywhere or use or drop somehow.

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix

**Comment by RallyPanther** [comment]
It seems that the old torch stacks (from prior 0.7.3.x) are still bugged in 0.7.3.2 as I am still unable to move them out of the inventory slot they are using.  This is affecting both a slot in a chest and backpack.

Is there any way to use delete them?

**Comment by MarjieAVolk** [comment]
Got your other bug, looking into it again.  Sorry about that :( https://github.com/StrangeLoopGames/EcoIssues/issues/6994
