### ISSUE TITLE
Parts of wall disappeared after server restart.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6978]
"other players kept losing room integrity, or outright losing parts of their walls each time the server had to be restarted"

Here is the world where it was occurring:
https://drive.google.com/file/d/1ffCwhv8HGHJf5YPvl6o7lIT9SFwAPhuV

Mentioned in follow up to review: http://steamcommunity.com/profiles/76561198014737314/recommended/382310/

**Comment by MarjieAVolk** [comment]
A couple of block disappearing bugs were fixed recently:
https://github.com/StrangeLoopGames/EcoIssues/issues/6892 - Plants causing this, so it would only happen along the ground
https://github.com/StrangeLoopGames/EcoIssues/issues/5900 - This one might be too old

**Comment by jrgriffi** [comment]
I am still seeing this. Occurs along the ground only and not after reboots. I have issues after all clients log off the server (I was on last night, came back this morning and they were missing. No one on server overnight).

**Comment by MarjieAVolk** [comment]
@jrgriffi That does sound related to plants.  I'm going to open a separate bug for your issue: https://github.com/StrangeLoopGames/EcoIssues/issues/7003

**Comment by SeanAtr0n** [comment]
any idea where in that first save they were losing blocks?

**Comment by johnkslg** [comment]
Not sure, the user linked here is incorrect so I cant get in touch with them, oops.

**Comment by SeanAtr0n** [comment]
This is already fixed in 7.3.2.... but the blocks will still disappear on the first load.

In 7.3.3 hopefully there won't be any phantom plants... but if any exist they will get deleted before they can destroy any blocks.
