### ISSUE TITLE
7.5.0 Steam thinks game is stuck open if you crash while playing singleplayer

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7875]

**Comment by elfl0rd** [comment]
@D3nnis3n server killself if main game crashed\closing.
Fixed.

**Comment by D3nnis3n** [comment]
I sometimes still occur this issue, therefore keeping it open.

**Comment by elfl0rd** [comment]
in 0.7.8 too? after mirasrael steam fixes.

**Comment by D3nnis3n** [comment]
Yes.

**Comment by elfl0rd** [comment]
In singleplayer? after crash? Or in different cases?

**Comment by D3nnis3n** [comment]
After Crash and sometimes even after just ending the game.

**Comment by WeaselDog** [comment]
I just experienced this in 8.3. Eco crashed when I pressed Alt+F4 while world was being generated and it left EcoServer.exe running. I would keep this as low priority though because I have closed Eco countless times and this was first time I encountered issue.

**Comment by TwixterZ** [comment]
Following how Todd tested this back in 8.3 as per his comment above, pressed Alt+F4 while loading a local save. ECO.exe was under "Not Responding" status for a while, but both ECO.exe and EcoServer.exe closed down once that dealt with, and steam recognize game is no longer running. 

This is in 0.10.0.0 Develop-712
