### ISSUE TITLE
USER ISSUE: Ramps are disappearing

### ISSUE THREAD

**Issue by twsgermany** [StrangeLoopGames/EcoIssues#7957]
**Version:** 0.7.4.6 beta

**Steps to Reproduce:**
I dont know how and why... im just go away and after minutes they are gone

**Expected behavior:**
they are gone for many players... But you cant place a new ramp there

**Actual behavior:**

<details>
<summary>Log File</summary>(...previous log truncated...)

er, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <0f129097844e485e9930e88ed3c03017>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <0f129097844e485e9930e88ed3c03017>:0 
[07:22] Exception in view notify: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Animator:SetBoolString (UnityEngine.Animator,string,bool)
  at UnityEngine.Animator.SetBool (System.String name, System.Boolean value) [0x00001] in <631a8b01f775461aaefeab8ef216af40>:0 
  at AvatarAnimationManager.UpdateWorking () [0x00016] in <a14c2a2baa3940d0969f235d02df648a>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <cfc149f8218b496788d8493c87de777a>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <cfc149f8218b496788d8493c87de777a>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <cfc149f8218b496788d8493c87de777a>:0 
  at Eco.Shared.View.Subscriber.Invoke () [0x00016] in <0f129097844e485e9930e88ed3c03017>:0 
  at Eco.Shared.View.View.NotifyChanged (System.String propname) [0x0007e] in <0f129097844e485e9930e88ed3c03017>:0 
Couldn't find mapping for object 'StorageClosetObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Core/PlayerClient/PoweredCartObject/PoweredCartObject(Clone)/Chassis/PoweredCart/Driving/MainCartMesh"
 
(Filename:  Line: 0)

Couldn't find mapping for object 'StorageClosetObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Couldn't find mapping for object 'StorageClosetObject'
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can not play a disabled audio source
 
(Filename:  Line: 707)

</details>

**Comment by BlazeGuy2** [comment]
Mentioned in #7974

**Comment by apnotix** [comment]
Stockpiles and Mod Items from "Transport piles" also.. The game is unplayable.. very bad.

**Comment by SeanAtr0n** [comment]
Could you upload the Game.eco file for the server?

Not sure what transport piles are, sounds like a mod?

**Comment by apnotix** [comment]
Yes the transport pipes are mod objects. But the ramps, vehicles and stockpiles disappears too without any mod.

Here is the game.eco file. Cant upload it to github, max size is 10mb.

https://www.file-upload.net/download-13175156/Game.eco.html

**Comment by SeanAtr0n** [comment]
fixed in 7.5

**Comment by apnotix** [comment]
@SeanAtr0n  in the current bleeding staging build (steam) this is not fixed.
