### ISSUE TITLE
USER ISSUE: Room brokes when door placed

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#8147]
**Version:** 0.7.5.0 beta staging-4ba58c84

**Steps to Reproduce:**
1. Set up house with two door spaces
2. Place two doors
3. Room broken
4. Remove and place block in same place. Room repaired

**Expected behavior:**
Room not broken after doors placed

**Actual behavior:**
Room broken when doors placed

**Comment by mirasrael** [comment]
Hi, yes it still reproduces on live servers. But I found another scenario to reproduce this. If you have two rooms with shared block if you remove shared block which broke both rooms and then place it back then only room where you are currently located will be repaired, but another become broken until you "repair" it with block remove-place operation.

**Comment by elfl0rd** [comment]
Fixed)) you can close it :)
![20181205214345_1](https://user-images.githubusercontent.com/4980243/49536163-ed233f00-f8d6-11e8-9bcb-6140ad06f952.jpg)
![20181205214349_1](https://user-images.githubusercontent.com/4980243/49536166-eeed0280-f8d6-11e8-8ad2-4bf51a70604d.jpg)
![20181205214351_1](https://user-images.githubusercontent.com/4980243/49536175-f0b6c600-f8d6-11e8-8df0-e397049634c0.jpg)

**Comment by mirasrael** [comment]
Issue still persists in 8.0
Steps to reproduce:
- build two linked rooms with two empty blocks (as window) next to door between rooms (I have 12m and 18m)
- extend window to 3 blocks (also door space should be affected). You will have two rooms broken
- repair block, now you have 1 room instead of two with total volume 33
- remove block from one of rooms (not linked) and put back. Now you have correct room volume (12m in my case), but another room is broken

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/51615740-a8606f80-1f39-11e9-896f-9830347c3c17.png)
![image](https://user-images.githubusercontent.com/475445/51615766-b615f500-1f39-11e9-9c81-cb19347d51f6.png)
![image](https://user-images.githubusercontent.com/475445/51615783-c29a4d80-1f39-11e9-8630-27e728a7bea8.png)
![image](https://user-images.githubusercontent.com/475445/51615810-ccbc4c00-1f39-11e9-8003-f54689dc60ba.png)
![image](https://user-images.githubusercontent.com/475445/51615838-de9def00-1f39-11e9-8342-22b6c3434c28.png)
![image](https://user-images.githubusercontent.com/475445/51615861-ea89b100-1f39-11e9-9507-27c72cb378b8.png)

**Comment by mirasrael** [comment]
Probably similar to https://github.com/StrangeLoopGames/EcoIssues/issues/10316
