### ISSUE TITLE
Cannot reach any servers

### ISSUE THREAD

**Issue by disfated** [StrangeLoopGames/EcoIssues#8508]
I have a bunch of issues related to public servers.

1. The list of public servers ("Browse" tab) is empty. All filters are off - yet can see none.

![](https://imageshack.com/a/img921/3470/DhPeQq.jpg)

2. Similar, the list of test servers is always empty.

![](https://imageshack.com/a/img923/1364/ECvBl8.jpg)

3. Trying to join my fav server

![](https://imageshack.com/a/img924/8744/Zi4Dku.jpg)

comes to "No response from master server" after long "Connecting..."

![](https://imageshack.com/a/img921/4935/UfMKrf.jpg)

Yet the server is online and if I use it's ip-address (138.201.233.196:3002) to connect it works just fine. After that this shady server appears

![](https://imageshack.com/a/img922/9730/x2q4T7.jpg)

which hardly helps.

In the end, I can only play public servers by constantly copy-paste'ing their ips I had luck to find somewhere out there...

I had the issue starting from 0.7.3 to 0.7.6

I have other pc connected to the same router, the same ISP, having the same Windows version with the same updates, the same steam account, the same Eco version, nearly the same software surroundings, and I HAVE NOT the issue there.

I've tried to completely turn off all firewall, antivirus, all third-party services and apps, my router doesn't have any blocking rules - still having the issue.

Please, help me investigate it, as I am run out of my ways.

**Comment by metachronism** [comment]
@disfated the master server was blocked for a good amount of time in Russia - are you still seeing this currently with 7.6.1+?

**Comment by disfated** [comment]
This is not related to blocking in Russia, `tracert` to masterserver is fine, yet still having this issue with 0.7.6.2.

**Comment by metachronism** [comment]
I believe this is fixed with the token-connect change, which will be in 7.7+

**Comment by disfated** [comment]
@metachronism @johnkslg 
Sadly, the problem remains in 7.7 and in Staging 0.7.8 and current Bleeding Edge.

**Comment by disfated** [comment]
Btw, is there any way to look up the ip-address of the server one is currently playing?

**Comment by elfl0rd** [comment]
As i know - try open "laws" site, then see adress field.

**Comment by disfated** [comment]
Спасибо дракоша :)

**Comment by elfl0rd** [comment]
Вообще насколько я знаю буквально вот-вот должны мастерсервер обновить, возможно поможет.

**Comment by disfated** [comment]
Somehow I've done something, I have no clue what exactly, but the problem has gone away.
I'm really happy :)

**Comment by disfated** [comment]
Argh... It came back out of nowhere with no visible reasons...

**Comment by disfated** [comment]
7.8.1 fixed it. This time for good, I hope.
