### ISSUE TITLE
USER ISSUE: Material rounding error

### ISSUE THREAD

**Issue by carsonbarlow** [StrangeLoopGames/EcoIssues#8685]
**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
At a crafting table, increase the number of items to be crafted to be 5.  The item should take less than 1 or any particular unit to make.

**Expected behavior:**
The resources required shoud be accurate.

**Actual behavior:**
The resoures required are one more than the accurate amount.

**Comment by Deantwo** [comment]
An example would make this a lot easier to understand.

**Comment by seccombew** [comment]
@carsonbarlow Please provide a example with pictures if possible.

**Comment by Deantwo** [comment]
I think I found the issue he is talking about.
![image](https://user-images.githubusercontent.com/2676134/43366461-c13ce36c-933e-11e8-8cd4-52fe1a5c3a25.png)
The recipe call for 0.4 logs, so making 100 hewn logs should show 40, but the little icon is showing 41. When I start the project it does seem to only use 40 logs, so it is just an UI error.

**Comment by Wally1169** [comment]
It's more than this.  See Mortared Stone.  If you make 50, at 80% efficiency, it should require 30 Pitch (3 pitch at 0% efficiency * (1-0.8) * 50.  However, the project requires 31.  The same happens when you try to make 100: 61 pitch are required.  So there's an error in the math behind the scenes as well as the UI.
![image](https://user-images.githubusercontent.com/40220854/44305022-4cb30a00-a33b-11e8-8a2d-05d7452ef84a.png)

**Comment by Splutty** [comment]
I can confirm it's only a display error in the UI. Although an annoying one when it blocks you from actually crafting it due to having the exact amount of materials.

At max efficiency, making glass costs 0.8 sand. So 5 glass should cost 4 sand.

When queueing up 5 glass, it shows it will use 5 sand (should be 4).
https://i.imgur.com/TKC9U9C.png

When ordered, it will actually only use the 4 that it should.
https://i.imgur.com/SRqosTe.png

**Comment by Wally1169** [comment]
I'm going to disagree.  At least on some recipes, it's more than just a display error in the UI.  The recipe I posted will stop and not make the last Mortared Stone or two demanding one additional Pitch.

**Comment by Deantwo** [comment]
@Wally1169, did you try to add the expected about of pitch? I mean does it consume that one extra pitch?

**Comment by Wally1169** [comment]
Yes I did add the 31st Pitch, after it had stopped, and it consumed it and finished the last of the MS recipe.

**Comment by Splutty** [comment]
I'm not sure why your pitch example would be strange, but with all tests I've run so far, it's exactly as I said, only a rounding error in the UI, not in the materials used.

I do know you can't queue a recipe when it thinks you're short, but if you have plenty, it will only use what it should be using, and not what it's displaying.

The only thing I can think of that's different is that your example has 2 input materials, and all the ones I've done so far only had 1.

**Comment by Wally1169** [comment]
I agree - this is the only recipe I've actually seen this happen on.  (I do see the UI bug on many others, of course.)  I did attempt to make excess Pitch one time.  It still consumed 31.  Perhaps it is due to the multiple materials, but there are plenty of other recipes that have multiple input materials that I have not seen have this problem (although most/all of those end up at an even number at max efficiency).  Try this recipe - maybe it's something weird on my end?

**Comment by Wally1169** [comment]
To be thorough, I just verified I have no Sand or Pitch within range of my Masonry Table.  I set up 3 Stone to Sand, the Recipe UI said it would use 3 Stone (interestingly), I clicked Order, and waited for it to complete.  I then set up 15 Masonry Pitch, the Recipe UI said 4 Sand (as others have also noted), clicked Order, and the Project UI confirmed that it only needed the 3 Sand that were available.  Once that completed, I confirmed that there were 30 Pitch available, set up 50 Mortared Stone, the Recipe UI said 31 Pitch and 81 Stone, clicked Order, and all 30 Pitch were consumed along with only 80 Stone (again, as others have noted).  However, the Project UI confirms that one additional Pitch is required, and is keeping the last two Mortared Stone from completing:
![image](https://user-images.githubusercontent.com/40220854/44431756-4a37f680-a56d-11e8-98fc-e4d2c35963bd.png)

**Comment by LiaungYip** [comment]
Attempt to craft items using a whole number of input resources.

![image](https://user-images.githubusercontent.com/2173684/44951259-192bc000-aea3-11e8-8eec-bfa0261f9497.png)

In this case, try to craft 5 Iron Gears, at a cost of 0.4 Iron Bar per Iron Gear.
This should require 2.0 Iron Bars.

![image](https://user-images.githubusercontent.com/2173684/44951262-36608e80-aea3-11e8-8ec1-06c198953f14.png)

When the job is started, 3 Iron Bars are consumed. This is one more Iron Bar than expected.

![image](https://user-images.githubusercontent.com/2173684/44951263-48dac800-aea3-11e8-85d1-3f097933f604.png)

**Comment by Splutty** [comment]
Actually. Only 2 bars are consumed. This is for most recipes with fractional input materials, but not for all, I've found one or two where this is not the case (which I can't remember at the moment of course).

Check the amount of iron bars left after you've queued the order.

**Comment by elfl0rd** [comment]
Bump

**Comment by D3nnis3n** [comment]
Most probably it'll be fixed with https://github.com/StrangeLoopGames/EcoIssues/issues/9903, so you need to have patience until that is refactored.

**Comment by elfl0rd** [comment]
> Most probably it'll be fixed with #9903, so you need to have patience until that is refactored.
Nope, still happens on master and 7.8.6 :(
I hate this, it's terribe...
You see as you can craft 100 from 10, but you need 11 after project started... And you not receive 100 without 11 :(((

**Comment by D3nnis3n** [comment]
Afaik the crafting scrap is not in 8.0 nor planned for it.

**Comment by elfl0rd** [comment]
I would like to see at least 0.8.1

**Comment by elfl0rd** [comment]
For now it's more predictable, but still unconfortable.
![default](https://user-images.githubusercontent.com/4980243/51475359-25051980-1d93-11e9-880b-520dcbca6bb1.png)
0.4x100=40, but in game it's 41
0.8x100=80, but in game it's 81

**Comment by SlayksWood** [comment]
Checked on 0.8.1.3. Wasn't able to reproduce, seems fixed.
![image](https://user-images.githubusercontent.com/45708377/56360758-4341b080-61ee-11e9-9c98-61cede15a8b9.png)
Added 40 Log for crafting and got 100 Hewn Logs.
![image](https://user-images.githubusercontent.com/45708377/56360946-c7943380-61ee-11e9-9df6-920e9a833368.png)

For other craft too.
![image](https://user-images.githubusercontent.com/45708377/56361069-15a93700-61ef-11e9-8a6d-de5a66f05c32.png)
