### ISSUE TITLE
Crafting fees not working?

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9282]
How are they supposed to work?

I set an anvil to 1 Dollar per Minute and 10 per Item.
If i set it to specific users only noone can use it. If i set it to public it says "Tax and Fee waived as of authorization". The guy trying was NOT authed on the property the anvil was on.

I also somehow find it weird it wanted to fee + tax (tax is 15%) a player that made a sawmill (15 minutes) around 85 dollars. The sawmill is one item, makes 10 dollars and 15 minutes, that is 25 dollars total, not 85 dollars, not even with tax. Even if i counted all items that are needed to make the sawmill for "fee per item" (as i dont really know how it works exactly) that would only make around 65 dollars, not 85.

So, either i'm dumb or something does not work as expected.

**Comment by TheeJudge** [comment]
Does he have access to the property, might have been what gave him access to the table. Or like stores when you give someone access to the property they no longer can by from it after being removed. Maybe something like that caused this.

**Comment by D3nnis3n** [comment]
> The guy trying was NOT authed on the property the anvil was on.

Same for this guy: No.

**Comment by johnkslg** [comment]
It should only give it to you free if you have full-rights to the property. If you just have consumer rights, it should charge you.  You can see the difference in AuthorizationManager.

**Comment by D3nnis3n** [comment]
As i've shown in the picture above, that was not the case. The person was not authed at all.

**Comment by johnkslg** [comment]
Fixed

**Comment by D3nnis3n** [comment]
Still happens on [beta 7.8.0 b7709677]. Exact the same problem:
I did auth "Everyone" to the table as otherwise "testalpha" had no access to use the table at all.
Then i did craft some boards but the costs were waived for authorized user.

I don't know if i'm allowed to, but i reopen the issue therefore, as i mention it in the QA Sheet. If that is not okay, please close it again and tell me, thank you!

**Comment by D3nnis3n** [comment]
Seems persisting on the newest bleeding edge version, too.
