### ISSUE TITLE
USER ISSUE: "Claiming land" tutorial not work.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9535]
**Version:** 0.7.8.0 beta staging-b7709677
![20180925161353_1](https://user-images.githubusercontent.com/4980243/46016714-2f155500-c0de-11e8-84da-56ae553889d7.jpg)
[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2415353/output_log.txt)

**Comment by Pradoxzon** [comment]
It seems that sometimes the subtask.Init call to this.Subscription.Add() does not always subscribe to OnPropertyChanged.
Or subtask.DeInit (this.Subscripiton.Remove()) is called too early in some cases but not others.

**Comment by elfl0rd** [comment]
On master too
![default](https://user-images.githubusercontent.com/4980243/46084575-a4e7f200-c1ac-11e8-8e3b-d615f6a0ff80.png)

**Comment by Pradoxzon** [comment]
This bug might be related to [EcoIssues #9527](https://github.com/StrangeLoopGames/EcoIssues/issues/9527).
With the change I made to fix that bug, I can no longer reproduce this bug.

**Comment by seccombew** [comment]
@BlazeGuy2 doublecheck that this is fixed

**Comment by BlazeGuy2** [comment]
Not fixed on Staging, exception is caught in the viewmanager everytime i use the claim stake.  Claim papers seem to deplete, but the visual icon on the screen isn't updating.

**Comment by BlazeGuy2** [comment]
Fix merged in
